# After build the resulting image was pushed to: "quay.io/rhacs-eng/qa:dele-scan-nginx".
#
# The resulting image should ONLY be used by the delegated scanning tests.

FROM docker.io/nginxinc/nginx-unprivileged:1.27.1
