// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"reflect"

	"github.com/stackrox/rox/central/globaldb"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
)

var (
	// CreateTableTestggrandchild1Stmt holds the create statement for table `testggrandchild1`.
	CreateTableTestggrandchild1Stmt = &postgres.CreateStmts{
		Table: `
               create table if not exists testggrandchild1 (
                   Id varchar,
                   Val varchar,
                   serialized bytea,
                   PRIMARY KEY(Id)
               )
               `,
		Indexes:  []string{},
		Children: []*postgres.CreateStmts{},
	}

	// Testggrandchild1Schema is the go schema for table `testggrandchild1`.
	Testggrandchild1Schema = func() *walker.Schema {
		schema := globaldb.GetSchemaForTable("testggrandchild1")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.TestGGrandChild1)(nil)), "testggrandchild1")
		globaldb.RegisterTable(schema)
		return schema
	}()
)
