// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"fmt"
	"reflect"

	"github.com/stackrox/rox/central/globaldb"
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/search"
)

var (
	// CreateTableTestparent3Stmt holds the create statement for table `testparent3`.
	CreateTableTestparent3Stmt = &postgres.CreateStmts{
		Table: `
               create table if not exists testparent3 (
                   Id varchar,
                   ParentId varchar,
                   Val varchar,
                   serialized bytea,
                   PRIMARY KEY(Id),
                   CONSTRAINT fk_parent_table_0 FOREIGN KEY (ParentId) REFERENCES testgrandparent(Id) ON DELETE CASCADE
               )
               `,
		Indexes:  []string{},
		Children: []*postgres.CreateStmts{},
	}

	// Testparent3Schema is the go schema for table `testparent3`.
	Testparent3Schema = func() *walker.Schema {
		schema := globaldb.GetSchemaForTable("testparent3")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.TestParent3)(nil)), "testparent3")
		referencedSchemas := map[string]*walker.Schema{
			"storage.TestGrandparent": TestgrandparentSchema,
		}

		schema.ResolveReferences(func(messageTypeName string) *walker.Schema {
			return referencedSchemas[fmt.Sprintf("storage.%s", messageTypeName)]
		})
		schema.SetOptionsMap(search.Walk(v1.SearchCategory(69), "testparent3", (*storage.TestParent3)(nil)))
		globaldb.RegisterTable(schema)
		return schema
	}()
)
