name: Cache ESLint Results
description: Cache ESLint results to speed up linting on subsequent runs
runs:
  using: composite
  steps:
    - name: Cache ESLint (save)
      if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # ratchet:actions/cache@v6.1.0
      with:
        path: ui/apps/platform/.eslintcache
        key: eslint-v1-${{ github.job }}-${{ hashFiles('ui/apps/platform/package-lock.json', 'ui/apps/platform/eslint.config.js', 'ui/apps/platform/eslint-plugins/**') }}-${{ github.sha }}
        restore-keys: eslint-v1-${{ github.job }}-${{ hashFiles('ui/apps/platform/package-lock.json', 'ui/apps/platform/eslint.config.js', 'ui/apps/platform/eslint-plugins/**') }}-

    - name: Cache ESLint (restore)
      if: ${{ !(github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) }}
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # ratchet:actions/cache/restore@v6.1.0
      with:
        path: ui/apps/platform/.eslintcache
        key: eslint-v1-${{ github.job }}-${{ hashFiles('ui/apps/platform/package-lock.json', 'ui/apps/platform/eslint.config.js', 'ui/apps/platform/eslint-plugins/**') }}-${{ github.sha }}
        restore-keys: eslint-v1-${{ github.job }}-${{ hashFiles('ui/apps/platform/package-lock.json', 'ui/apps/platform/eslint.config.js', 'ui/apps/platform/eslint-plugins/**') }}-
