// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres/pgtest"
	"github.com/stackrox/rox/pkg/protoassert"
	"github.com/stackrox/rox/pkg/sac"
	"github.com/stackrox/rox/pkg/search"
	"github.com/stackrox/rox/pkg/testutils"
	"github.com/stretchr/testify/suite"
)

type TestNoSerializedObjsStoreSuite struct {
	suite.Suite
	store  Store
	testDB *pgtest.TestPostgres
}

func TestTestNoSerializedObjsStore(t *testing.T) {
	suite.Run(t, new(TestNoSerializedObjsStoreSuite))
}

func (s *TestNoSerializedObjsStoreSuite) SetupSuite() {

	s.testDB = pgtest.ForT(s.T())
	s.store = New(s.testDB.DB)
}

func (s *TestNoSerializedObjsStoreSuite) SetupTest() {
	ctx := sac.WithAllAccess(context.Background())
	tag, err := s.testDB.Exec(ctx, "TRUNCATE test_no_serialized_objs CASCADE")
	s.T().Log("test_no_serialized_objs", tag)
	s.store = New(s.testDB.DB)
	s.NoError(err)
}

func (s *TestNoSerializedObjsStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	store := s.store

	testNoSerializedObj := &storage.TestNoSerializedObj{}
	s.NoError(testutils.FullInit(testNoSerializedObj, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundTestNoSerializedObj, exists, err := store.Get(ctx, testNoSerializedObj.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundTestNoSerializedObj)

	withNoAccessCtx := sac.WithNoAccess(ctx)

	s.NoError(store.Upsert(ctx, testNoSerializedObj))
	foundTestNoSerializedObj, exists, err = store.Get(ctx, testNoSerializedObj.GetId())
	s.NoError(err)
	s.True(exists)
	protoassert.Equal(s.T(), testNoSerializedObj, foundTestNoSerializedObj)

	testNoSerializedObjCount, err := store.Count(ctx, search.EmptyQuery())
	s.NoError(err)
	s.Equal(1, testNoSerializedObjCount)
	testNoSerializedObjCount, err = store.Count(withNoAccessCtx, search.EmptyQuery())
	s.NoError(err)
	s.Zero(testNoSerializedObjCount)

	testNoSerializedObjExists, err := store.Exists(ctx, testNoSerializedObj.GetId())
	s.NoError(err)
	s.True(testNoSerializedObjExists)
	s.NoError(store.Upsert(ctx, testNoSerializedObj))
	s.ErrorIs(store.Upsert(withNoAccessCtx, testNoSerializedObj), sac.ErrResourceAccessDenied)

	s.NoError(store.Delete(ctx, testNoSerializedObj.GetId()))
	foundTestNoSerializedObj, exists, err = store.Get(ctx, testNoSerializedObj.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundTestNoSerializedObj)
	s.NoError(store.Delete(withNoAccessCtx, testNoSerializedObj.GetId()))

	var testNoSerializedObjs []*storage.TestNoSerializedObj
	var testNoSerializedObjIDs []string
	for i := 0; i < 200; i++ {
		testNoSerializedObj := &storage.TestNoSerializedObj{}
		s.NoError(testutils.FullInit(testNoSerializedObj, testutils.UniqueInitializer(), testutils.JSONFieldsFilter))
		testNoSerializedObjs = append(testNoSerializedObjs, testNoSerializedObj)
		testNoSerializedObjIDs = append(testNoSerializedObjIDs, testNoSerializedObj.GetId())
	}

	s.NoError(store.UpsertMany(ctx, testNoSerializedObjs))

	foundTestNoSerializedObjs, missing, err := store.GetMany(ctx, testNoSerializedObjIDs)
	s.NoError(err)
	s.Empty(missing)
	protoassert.ElementsMatch(s.T(), testNoSerializedObjs, foundTestNoSerializedObjs)

	testNoSerializedObjCount, err = store.Count(ctx, search.EmptyQuery())
	s.NoError(err)
	s.Equal(200, testNoSerializedObjCount)

	s.NoError(store.DeleteMany(ctx, testNoSerializedObjIDs))

	testNoSerializedObjCount, err = store.Count(ctx, search.EmptyQuery())
	s.NoError(err)
	s.Equal(0, testNoSerializedObjCount)
}
