// Code generated by pg-bindings generator. DO NOT EDIT.
package n51ton52

import (
	"context"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/pkg/errors"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/migrator/migrations"
	"github.com/stackrox/rox/migrator/migrations/loghelper"
	legacy "github.com/stackrox/rox/migrator/migrations/n_51_to_n_52_postgres_sensor_upgrade_configs/legacy"
	pgStore "github.com/stackrox/rox/migrator/migrations/n_51_to_n_52_postgres_sensor_upgrade_configs/postgres"
	"github.com/stackrox/rox/migrator/types"
	pkgSchema "github.com/stackrox/rox/pkg/postgres/schema"
	"github.com/stackrox/rox/pkg/sac"
	bolt "go.etcd.io/bbolt"
	"gorm.io/gorm"
)

var (
	migration = types.Migration{
		StartingSeqNum: 100,
		VersionAfter:   storage.Version{SeqNum: 101},
		Run: func(databases *types.Databases) error {
			legacyStore := legacy.New(databases.BoltDB)
			if err := move(databases.BoltDB, databases.GormDB, databases.PostgresDB, legacyStore); err != nil {
				return errors.Wrap(err,
					"moving sensor_upgrade_configs from rocksdb to postgres")
			}
			return nil
		},
	}
	batchSize = 10000
	schema    = pkgSchema.SensorUpgradeConfigsSchema
	log       = loghelper.LogWrapper{}
)

func move(legacyDB *bolt.DB, gormDB *gorm.DB, postgresDB *pgxpool.Pool, legacyStore legacy.Store) error {
	ctx := sac.WithGlobalAccessScopeChecker(context.Background(), sac.AllowAllAccessScopeChecker())
	store := pgStore.New(ctx, postgresDB)
	pkgSchema.ApplySchemaForTable(context.Background(), gormDB, schema.Table)
	config, found, err := legacyStore.Get(ctx)
	if err != nil {
		log.WriteToStderr("failed to fetch sensorUpgradeConfig")
		return err
	}
	if !found {
		return nil
	}
	if err = store.Upsert(ctx, config); err != nil {
		log.WriteToStderrf("failed to persist configs to store %v", err)
		return err
	}
	return nil
}

func init() {
	migrations.MustRegisterMigration(migration)
}
