apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-controller
  namespace: stackrox
  labels:
    app.kubernetes.io/component: config-controller
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
    app.kubernetes.io/version: 4.10.1
    helm.sh/chart: stackrox-central-services-400.10.1
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-central-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
imagePullSecrets:
- name: "stackrox"
- name: "stackrox-scanner"
