// Code originally generated by pg-bindings generator.

package n41ton42

import (
	"context"

	"github.com/pkg/errors"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/migrator/migrations"
	frozenSchema "github.com/stackrox/rox/migrator/migrations/frozenschema/v73"
	"github.com/stackrox/rox/migrator/migrations/loghelper"
	legacy "github.com/stackrox/rox/migrator/migrations/n_41_to_n_42_postgres_process_baselines/legacy"
	pgStore "github.com/stackrox/rox/migrator/migrations/n_41_to_n_42_postgres_process_baselines/postgres"
	"github.com/stackrox/rox/migrator/types"
	pkgMigrations "github.com/stackrox/rox/pkg/migrations"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/pgutils"
	"gorm.io/gorm"
)

var (
	startingSeqNum = pkgMigrations.BasePostgresDBVersionSeqNum() + 41 // 152

	migration = types.Migration{
		StartingSeqNum: startingSeqNum,
		VersionAfter:   &storage.Version{SeqNum: int32(startingSeqNum + 1)}, // 153
		Run: func(databases *types.Databases) error {
			legacyStore, err := legacy.New(databases.PkgRocksDB)
			if err != nil {
				return err
			}
			if err := move(databases.DBCtx, databases.GormDB, databases.PostgresDB, legacyStore); err != nil {
				return errors.Wrap(err,
					"moving process_baselines from rocksdb to postgres")
			}
			return nil
		},
	}
	batchSize = 10000
	log       = loghelper.LogWrapper{}
)

func move(ctx context.Context, gormDB *gorm.DB, postgresDB postgres.DB, legacyStore legacy.Store) error {
	store := pgStore.New(postgresDB)
	pgutils.CreateTableFromModel(context.Background(), gormDB, frozenSchema.CreateTableProcessBaselinesStmt)

	var processBaselines []*storage.ProcessBaseline
	err := walk(ctx, legacyStore, func(obj *storage.ProcessBaseline) error {
		processBaselines = append(processBaselines, obj)
		if len(processBaselines) == batchSize {
			if err := store.UpsertMany(ctx, processBaselines); err != nil {
				log.WriteToStderrf("failed to persist process_baselines to store %v", err)
				return err
			}
			processBaselines = processBaselines[:0]
		}
		return nil
	})
	if err != nil {
		return err
	}
	if len(processBaselines) > 0 {
		if err = store.UpsertMany(ctx, processBaselines); err != nil {
			log.WriteToStderrf("failed to persist process_baselines to store %v", err)
			return err
		}
	}
	return nil
}

func walk(ctx context.Context, s legacy.Store, fn func(obj *storage.ProcessBaseline) error) error {
	return s.Walk(ctx, fn)
}

func init() {
	migrations.MustRegisterMigration(migration)
}
