package resolvers

// Init registers all GraphQL resolver schemas.
// Called explicitly from getBuilder() in schema.go instead of package init().
func Init() {
	// Register all resolver schemas in alphabetical order
	registerAccessScopesSchema()
	registerClusterCountByTypeSchema()
	registerClusterHealthSchema()
	registerClusterVulnerabilitiesSchema()
	registerClustersSchema()
	registerComplianceSchema()
	registerComplianceManagementSchema()
	registerComponentsSchema()
	registerContainerInstancesSchema()
	registerDeploymentEventsSchema()
	registerDeploymentsSchema()
	registerGroupsSchema()
	registerImageComponentsSchema()
	registerImageCVECoreSchema()
	registerImageScanSchema()
	registerImageSignatureVerificationSchema()
	registerImageVulnerabilitiesSchema()
	registerImagesSchema()
	registerImagesV2Schema()
	registerK8sRolesSchema()
	registerNamespacesSchema()
	registerNodeComponentsSchema()
	registerNodeComponentsV1Schema()
	registerNodeCVECoreSchema()
	registerNodeScanSchema()
	registerNodeVulnerabilitiesSchema()
	registerNodesSchema()
	registerNotifiersSchema()
	registerPermissionSetsSchema()
	registerPlatformCVECoreSchema()
	registerPlatformCVECountByFixabilitySchema()
	registerPlatformCVECountByTypeSchema()
	registerPlottedImageVulnerabilitiesSchema()
	registerPlottedNodeVulnerabilitiesSchema()
	registerPodsSchema()
	registerPoliciesSchema()
	registerPolicyCounterSchema()
	registerResourceCountBySeveritySchema()
	registerRolesSchema()
	registerSearchSchema()
	registerSecretsSchema()
	registerServiceAccountsSchema()
	registerSubjectsSchema()
	registerTokensSchema()
	registerViolationsSchema()
	registerVulMgmtWidgetsSchema()
	registerVulnerabilitiesSchema()
	registerVulnerabilityCounterSchema()
	registerVulnerabilityRequestsSchema()
	registerVulnerabilityVectorsSchema()
}
