spec:
  template:
    spec:
      initContainers:
      - name: init-db
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
          limits:
            cpu: null
            memory: 1Gi
      containers:
      - name: central-db
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
          limits:
            cpu: null
            memory: 1Gi
