spec:
  template:
    spec:
      containers:
      - name: central
        resources:
          requests:
            cpu: 1500m
            memory: 1Gi
          limits:
            cpu: null
            memory: 1Gi
