spec:
  template:
    spec:
      containers:
      - name: matcher
        resources:
          requests:
            cpu: "400m"
            memory: "3Gi"
          limits:
            memory: "3Gi"
