spec:
  template:
    spec:
      containers:
      - name: matcher
        resources:
          requests:
            cpu: "400m"
            memory: "4Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
