ca:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIDFTCCAf2gAwIBAgIUM0nxQR7OkTKNLpUJzOoCU3x97CowDQYJKoZIhvcNAQEL
    BQAwGTEXMBUGA1UEAwwOU3RhY2tSb3ggQ0kgQ0EwIBcNMjYwNTAzMTQzNzE3WhgP
    MjEyNjA0MDkxNDM3MTdaMBkxFzAVBgNVBAMMDlN0YWNrUm94IENJIENBMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvFUtT13IGhtfasCj4Td347tQEOde
    o47tJm93Us+cnDhMDOUc8sRTqEKnIFZwq/Q2iJfZW6+lgtWl5LhDTpsVFvKnkCxF
    DbrVD3J2Y2v3sm6fsrWRmOwfPRevjaJfZZjAy8BgJLmpjcDSaXr8SxgnStQCUMyl
    sdq4p6KSVrkRalI2tle+D2qukYeEvG2TV5XHOFFWEv+9aZwK7KatIYEXglA5zsUF
    pO3lp3DlIwga4bKdyWybvz+25T4uDUxWS6mTuGwkH4J6Hkp3CA/dOuB3MuTMeMUq
    vAZP1NUsono6/lV58zA3ezxYK7a4y9Mv95qZmOnLQsXrD+ngVW+y3eCHKwIDAQAB
    o1MwUTAdBgNVHQ4EFgQUzKq1mqjkrYM/8cmI4ZyrrZmag1gwHwYDVR0jBBgwFoAU
    zKq1mqjkrYM/8cmI4ZyrrZmag1gwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAQEAA1ZZO9elQ/667D9jT1UxmZF7emedMC3PQxfBtRleM8FtR9BJ6fLT
    BeBB4ri+G+Hckr81AZe0L+bz7KwU6wVY2MVkPUEyAIRifMiLodVbdKl+bumywYmU
    yiny+gIztuTzMOQ2Wrg9CkjZwYpPBVsCjFoyFHCSymtc0MkxzQzDCUohaC9lglR6
    jUDTcM0443nthCF3ENJA+smdtaelOKJkwDwOKkgIJBYGfof1JwK43n/UB7q+ijT/
    pn2V6YGN/g2HX8uTn24FYdm6c6wgJYLab8IkaJaQP/BO9c/IeqQna4YDA5EgIunI
    cm+Z0sabGc+6wQsQAOlYvaCC1p98BiqNlA==
    -----END CERTIFICATE-----
sensor:
  serviceTLS:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIUJ3SvtE3Asi6p0mHcGlerfe/8oXAwDQYJKoZIhvcNAQEL
      BQAwGTEXMBUGA1UEAwwOU3RhY2tSb3ggQ0kgQ0EwIBcNMjYwNTAzMTQzNzE3WhgP
      MjEyNjA0MDkxNDM3MTdaMD8xPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAw
      MDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQCDnWXZwwKsV5izdqTDBpG4pF4erBj3oRL+0MPRDTlH
      isOFm/FXg2zqQ5SEaBnHABUILAm7+DBlvgGDF5VzryHvjeuNoQWbQjxz6wr3TJ4D
      bJQEgrd+DkOrhRupCeya5qEa77XR7pDqbK9EKxDntid90DFLENtbDyQQdOkGCzT9
      AB3qatOgXM/NcEmJGTDkvuxDxW1xHVmkTxkNiMp9zTYFqrka+PSIaOI91ehhLYW2
      rLnVEwpG49cYtHVIgsyBacGuaiZPRu4gqu04PEOeMaSF1MeGEc9Z+Bh+dDwwnTuj
      zpLiAJWJWqS0qAjzV0ycGC3OKxnBmyKr1APyh76mZQbFAgMBAAGjQjBAMB0GA1Ud
      DgQWBBTsZKyVTIG9rLTfjvzApekC7Q2S3DAfBgNVHSMEGDAWgBTMqrWaqOStgz/x
      yYjhnKutmZqDWDANBgkqhkiG9w0BAQsFAAOCAQEAf1mZpu+bUf6iHvjGliCAYoH9
      rWTJhzGMjENQHEvYw+6nl7Lv8qmoidyTyPyJXOxum8bB/JOoqkqc50qZmMDS3Kb5
      9dJ0iepqqTyixG2WXFOn56xHIOzEfGsuw1lJgUl51w8e7OYRjM4/CRZhbBln4o5/
      Iy+DwZfkbw6/09X1fnAD7fWg+YSCHv9H8lHOCN+evnOi5H/1ySzQ8zGPh0dBpgln
      JLz50reGMdKGPvT0POqreU1ll5He9kJz5BDPeT4Mm0Tsqsvv+cdZuRChSApcd7sG
      iDhwKxZstQ9Br1UfiWSKJMMzgRzoldp4zoBJyMayDA3AV8KDoMO/1dFtJs9JRQ==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCDnWXZwwKsV5iz
      dqTDBpG4pF4erBj3oRL+0MPRDTlHisOFm/FXg2zqQ5SEaBnHABUILAm7+DBlvgGD
      F5VzryHvjeuNoQWbQjxz6wr3TJ4DbJQEgrd+DkOrhRupCeya5qEa77XR7pDqbK9E
      KxDntid90DFLENtbDyQQdOkGCzT9AB3qatOgXM/NcEmJGTDkvuxDxW1xHVmkTxkN
      iMp9zTYFqrka+PSIaOI91ehhLYW2rLnVEwpG49cYtHVIgsyBacGuaiZPRu4gqu04
      PEOeMaSF1MeGEc9Z+Bh+dDwwnTujzpLiAJWJWqS0qAjzV0ycGC3OKxnBmyKr1APy
      h76mZQbFAgMBAAECggEAB7g0vVyaB0mTAAcH28AtTgm7/dYPwn8iKgEiKcc6B8Ic
      kjVcPDW4mWvx0ICk7xOy6BoMecfb74JrvHM8FZSH1nEPSBe8nbI5RqjvqXjHCtc0
      k6gmwuAWJCpdkzZXuEUp3WEtG6f/vB7i+nSr3D9bmnOaieHY+oK36uGEj7watUfA
      hj4tUptTuReegSLGbCz8fNVmH57cRKxrQ/8osVuD84z3PO3w2UPEef2QouXG/zTC
      WvfXU52klmWhmORRLpVS9AoSEpLTw1fgdreeGyHb/LF5LuefF2LXKuyxuW6zp7/0
      7vV4jImy8OedSPxnSJnZkmOqV/Y1r6hQu7TEjFa2kQKBgQC5EsLvLhem0U2d/XcD
      PkrHH0SC9lFkEcxoQVcKIoIY+eqAyMdlL05ZWIutSCynmV/qGomDJf5R+jIlmDLJ
      2SN4ppOKAoHHbTJE/Fdcf5OrJaJX8koPTl63Nu+S56Vw/nlTvvqeqRbQTHW641+K
      XdO5bpj3h+vNPd3XjeHO/FI39QKBgQC2DeoyubLMawQlEMu0TKsC9jET+CoThGxq
      2jURlt5nXDJRVfu9obBEFP0RWSp6B1xkNklrA/6nLRzmACMHdBl+xKwB9XRqqMXd
      DqEcjGbgv1SU28UWI+xemnLJRvxqE0kdCztSDf8I3P7zQP0TArPc3hIIO3USeS2H
      oF7bv/HhkQKBgAREWXg4QNVYyAhXerH5crHql6LJWREMlADnWMFkEEnRIUX82xQL
      JixLLVU+b8EheSOlnvwGGTn8ocFaI/mhZv72IDqzWhil/N24T69TRa1Rfc+3R1vY
      +7gPrTBe5OKZC2UR5ydXUK5WxPQdH+vJxALneOFkIdymi4HXxJgIG0EtAoGAEeUo
      QjgytRlH3QTboStwG+hrRpU8PZLkvVQZp1L3JZ3QbGJRToCYPPj7Lztei4QxtsAH
      U3efDnvGvW0CBHeLEgTvC3o/KUTRvjrz50R90FW+UKuRoe2CDIKOCe7qXNrscuhp
      ulUZ3psqjGq09atsVqeVii2eAmTa7tv6twsVEaECgYBDsp4A2J1BIpM3+3WhJ2f7
      rdprmHn7t97DOiClzZf3ElPZZ0H8lAazUfkq3og/4jK5KSh3kYutPLH30FFCuBeS
      RRMpMH6SQ7GW4cLp9+e7PiyBtbt3+D/jx+inLvpVCJBW64cZsNS+sCDuuBPdFJNs
      JcVOxxopqFrad8Q7KxE9Mw==
      -----END PRIVATE KEY-----
collector:
  serviceTLS:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDLTCCAhWgAwIBAgIUJ3SvtE3Asi6p0mHcGlerfe/8oXEwDQYJKoZIhvcNAQEL
      BQAwGTEXMBUGA1UEAwwOU3RhY2tSb3ggQ0kgQ0EwIBcNMjYwNTAzMTQzNzE3WhgP
      MjEyNjA0MDkxNDM3MTdaMEIxQDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAw
      MDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEwggEiMA0GCSqGSIb3
      DQEBAQUAA4IBDwAwggEKAoIBAQD94UsBcaT4xrlBu9DOjinjLBJXWzAQR6JUQ2nl
      lI62KOb2dG/ZWmh7gfLwoDZ0WdRoiW1lbWLkUu+vJXgV8evQss3FuLNBHplR0x5d
      xAEp/cfRT0P7n172AQXzEU6vkdb60gFGk12t5h5Lg6Ea8fxmK5zPKvCd7CiWqnas
      yXODrqq1iOnwttJHRzLl5x546bPpE8GE4ultRshNf4spV2jRVfiekihxp+FJfjlg
      4rchubHyMFl2vxb7PBYXnhHm8jjjFTNtk8J1l6ApylfHM8avT7d/CGL5GHyZMFaq
      xuEsAewnrIW/VgQKn7/0xmr60d0BOtS86wym08Y2ija8ii/zAgMBAAGjQjBAMB0G
      A1UdDgQWBBRCSWeeOOIYgC0fAZnw1xzu+16GAjAfBgNVHSMEGDAWgBTMqrWaqOSt
      gz/xyYjhnKutmZqDWDANBgkqhkiG9w0BAQsFAAOCAQEAo8NpaMy9Z/ZaBnSf0pnt
      E8b+ltQYW918WROQgnQfUgvW/EGfsAkXYKPQP1KDzpF/HilqCLLZ/OSsnZ4jY3tM
      clhqx7s4AS4xQODu3qU7reqASW7mE0LkaI+TMfMl6vPf0ursHbQf1QauabHmWq2l
      02XqFxvfm77CSI4BbuIfqFCVE4aR1IsSwspSu7vCdlnxEscxTL4pmcKr7G/f3frY
      zhELzs1Di0xLwrQR7QaZNLfFbmU8H3OewCodpTidAI08IGrJNjz61bu6MxrYsqlf
      CIopInH5b6b7zyDt7HSl8vqFqLB3vT9VUr6IZctHiV5APEYGhfWL1kQz7scnXGpG
      Tg==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQD94UsBcaT4xrlB
      u9DOjinjLBJXWzAQR6JUQ2nllI62KOb2dG/ZWmh7gfLwoDZ0WdRoiW1lbWLkUu+v
      JXgV8evQss3FuLNBHplR0x5dxAEp/cfRT0P7n172AQXzEU6vkdb60gFGk12t5h5L
      g6Ea8fxmK5zPKvCd7CiWqnasyXODrqq1iOnwttJHRzLl5x546bPpE8GE4ultRshN
      f4spV2jRVfiekihxp+FJfjlg4rchubHyMFl2vxb7PBYXnhHm8jjjFTNtk8J1l6Ap
      ylfHM8avT7d/CGL5GHyZMFaqxuEsAewnrIW/VgQKn7/0xmr60d0BOtS86wym08Y2
      ija8ii/zAgMBAAECggEASKPvIZUiJjo55Hh4KLmde43vG4aQTIAqjqCRSqqEYNN4
      LhknrZGEJp6KY9X7brQLJfP4VJaFPp4KTVtTrje/iMG4RbPwuhemt7ZH0H1V9e1S
      gG2FHpg9g/bL/H29vVdlovN2gPqGScz3axTZAkwtsxAUeGQpX44kGOPiO9MSFaFQ
      /Fhpjls9OFLcZMUqqEqhNNtNH5UTrJMHgSrSbaVM7VlMVoj0oVCsfdlIiS5rfmoD
      mgM62HZuivJxiBY05VktKuTUSBpH2uulZN8dx0YJzCQA9WJP4yG+T0iJ4zbSMwbP
      K4c4VC2b29z9g918rrI1uCkZ/ESrPFrr7J0AvQAGNQKBgQD/XgSMZQkEL3TdiZC3
      eHPBKOjdmdi+m9cm0xUGn8USy3RmgVcZLKrB7T7mjtHRGyPzaZe/QLtxDTks06ii
      X3UnhhvPfNFaFoZPV17//oKQ9c2eJLRY0jv8J9RIIxj/q6LcOw3uFSmM2FXVprQ4
      gMr80nveRRjbGcHYpNqheW0UJQKBgQD+glT1mAJ7ZovRD9YbPUAQGKlIdG7iFy69
      l6CeyMWEbMZmdqKd0M+Uza4ZcNCblRLB8/5m+nPbGZwoa5oBwDZuUEHVZ7lkFrC1
      Sd6UVUkXDywBs62ycZlHZYSyeDAanGD4iIzRtWkMA1j5r6oCaxRBjVoCX+S2eAzd
      tGeOTKqsNwKBgEVJx0Yoq9ec4MKzbra5Uf8ZEIYAFlUxh6EbKNtRQnGlDoI5md5U
      xkg0DRsVqUxpZsnG3sufzrwP8HF/RIQ6DlmZA7a6kTs2XV7tv/MJpXebmhzMrLpk
      4K28SNcB3uiQM3I5+7+bslhq4m9D+iZSm8EZg059xQ694GDd6gxiG/yZAoGACwJy
      UGlx+gqWk8WemnEM22VltUesIEWmdPchMJ04xiC6eGY7ZJ5KzIIVPO5/Z6uMMy2t
      3KCK8HhsI+d7swWwlRcNsgCZqXW90SnP4hTKY5/5ZF10bxqw6cC/e8TtN8l5/GZT
      ySKS170xVSO/M/mT174Yna+uQiJxVAngzOwOGgMCgYB1HkmDxjfx0M3n/j9DaSrZ
      QuK1pmlDHm984c+Ya9uxNEjqKmDfJQ5U+/3JpOLSjEXMulqWBETpqb3l6+Njyq+/
      o6TOEjm/ls2Ia0Kd8jGT1SxFfR6qF5oGVlLGH/GQONd3qMORJhNbPsj6zzqZ1W2+
      dsrsZ0vLxlhuVRxZ7bUK+g==
      -----END PRIVATE KEY-----
admissionControl:
  serviceTLS:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDNTCCAh2gAwIBAgIUJ3SvtE3Asi6p0mHcGlerfe/8oXIwDQYJKoZIhvcNAQEL
      BQAwGTEXMBUGA1UEAwwOU3RhY2tSb3ggQ0kgQ0EwIBcNMjYwNTAzMTQzNzE3WhgP
      MjEyNjA0MDkxNDM3MTdaMEoxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NF
      UlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMTCCASIw
      DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJOqgl0TKpUVG7TW63ENhlBF2J/r
      mQry3Bq41i4BsyUdu7blK9vtNQ0QjCdRJ3BEfLqtLWGnO+2SmDltBq9KPkMA3Uuo
      qCrvN/fNMHNOzsiYe+TYsyVsqjstCNLuO2YXLuvdG7XsxHYmGt8FWHIKeQUln+49
      JVcBw+AsU8xTGLmFvjE7cyar69vGiFM+5orfkLhTPFgYiJ57CM5ruKNc7T+UVyF4
      J8QS9Nnfo5TVvxJKYUkWle+XuoScAlWXlKdjDCVfziY88LJU+yn/2+CQlLK4TSMG
      fF1tmBhjEyvUYISHrDfSF1cOqxxpxWa7Og3zOof87AjwyNqNey1ofWGuii8CAwEA
      AaNCMEAwHQYDVR0OBBYEFMHfL+B5bzFFCp4zocGeSsoF+mo7MB8GA1UdIwQYMBaA
      FMyqtZqo5K2DP/HJiOGcq62ZmoNYMA0GCSqGSIb3DQEBCwUAA4IBAQAOsbESjPb5
      8GXOaUmzctVF9EoJjUt/HGPfqEraMP6F/EgUEmWNUVo40bAs+csb6LPYjz3bocfB
      bnYye31k+hSN0BJJRcVCrNMgazi4jXf8PJqPFoL2ec5ZA5SIgYFmq0sceDx4AtVK
      NGh9CfSwFRNCOkosrBW+Ep8pUomYgnNUL6oIjglQUY8EAl5mez08CvoMbUfMK6rb
      VBHLw6f+qpf5FGfp2juWDUjAMXg9UsZ9fpSUoNyJCNNSfu5yb9uV+AtCIGjpa2sS
      7GiIwF1LxkBe3NHPWPokaZ3plZL0sgT0tMzU3AdSfa4Tzzma0yulgpwSakSiy3Ff
      3r6swIlID2lk
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCTqoJdEyqVFRu0
      1utxDYZQRdif65kK8twauNYuAbMlHbu25Svb7TUNEIwnUSdwRHy6rS1hpzvtkpg5
      bQavSj5DAN1LqKgq7zf3zTBzTs7ImHvk2LMlbKo7LQjS7jtmFy7r3Ru17MR2Jhrf
      BVhyCnkFJZ/uPSVXAcPgLFPMUxi5hb4xO3Mmq+vbxohTPuaK35C4UzxYGIieewjO
      a7ijXO0/lFcheCfEEvTZ36OU1b8SSmFJFpXvl7qEnAJVl5SnYwwlX84mPPCyVPsp
      /9vgkJSyuE0jBnxdbZgYYxMr1GCEh6w30hdXDqscacVmuzoN8zqH/OwI8MjajXst
      aH1hroovAgMBAAECggEAFgRQzqbabQMKMALxdNhC4/oeC+4ZUggW6EcR7Ccluk1+
      HQ17Zh2ukMWcWApiGnujq0PB5fME3O3EE5/dZMppkRzyYeMCO/CSBDkMVcz0yPTv
      WBY1U8mpcgxLagPKSHUBcnpztMLaIhGZZRJLdyl3lNxgxalJRXlGZsjFL8xd/d8o
      mNWkLxjaLangcJiVvquM3v21XgNjXzPfkHoenT869Dbr/R87ciKtzbgyxwtE5RRY
      jcNr/7xbXkpkAoeMNtu9sDL5Ohgw7K+6GPDuWYJ+q29DVFCzsKfEzUu23RfwFqCw
      GwgHzS0sAfkch+6uDSDqnJOPEFQCctcKc7OghVbORQKBgQDGA5xvvNdXqb59lHzi
      LhAVQERX5Eklw4EIBGTrk5ZYtzpsXwZFoDdZYrBxBrp4klh/vEExImjmucpqPzn8
      ACeTSOl1PZOrRPhWi8UnfZjM75vnh3gTkl2XRkk1NPQit0H7R2yqD4TGHUz3U68d
      XsuMFCH79eem7400fECW9M43LQKBgQC+6H1jC5fKc9CTpZfrhQEqvJ4whwUmFdNM
      +o4CgqXQRFfDbyqsdmgPTjWrKtNZP7ZrdPediyqHK6RhZlk6U9fdGUc3x2QekJGi
      rMuF6WkIRzTLRPgOIvXEMgOKqGB9+UP+yFW8/xmg5whow1vPCVThg46NTvaQQepT
      vuUdKxHgSwKBgQC028l/2XjKzfR6WSyznaT89AU4Tf9tqaLqArF25geVok2PfD+L
      SqojT1ue8KlSxUBl8zmMOkScMKgr4PICNNXw1dC+T+7XqRg2XFVIG5R74oKAt6A6
      KB6ps/3bxjESoFV4wKUEs0XvegW5hUrVxaaenCjqLJFYTUao4LBR8OmFRQKBgEGn
      HofTUs4y6gX8qrQ6N16FIzm5FVI1q0cL246Nc4yeFDiHoHtS9RJeaSKGRcyploh5
      3zX0yBlYLt24HvNqJhBJQy6xiYLhYNQ67HsO/Cn2ovdMrqnd5/si4AjtQtHPyUxz
      hNjMOfoVudSdapNWuDQd1AZQo4aUxIssWQqg5zLlAoGBALmreZHRL0SaZeSQqJRt
      F4Ds90Cf6LV3Smz+1eJX/HAA+Do9vGrmo7BznkAsbrSObDcQ04MNckq8R1Hwtrce
      MFrT7sT2c9hghhWJgcJsSOPc+msXe8v2kDMGHkQeGDlzfG9ZYYE+cfvTy4ccLRWj
      PmTM/URlU6g0rW52x1SrsVCr
      -----END PRIVATE KEY-----
