name: Cache UI Dependencies
description: Cache UI Dependencies
inputs:
  lockFile:
    description: Where the package lock is written
    required: true
    default: "ui/apps/platform/package-lock.json"
runs:
  using: composite
  steps:
    - name: Cache UI Dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5
      with:
        path: |
          ~/.npm
          ~/.cache/Cypress
        key: npm-v4-${{ hashFiles(inputs.lockFile) }}
        restore-keys: npm-v4-
