#!/usr/bin/env bash

export ORCH="k8s"
export ORCH_CMD="kubectl"
export ORCH_FULLNAME="kubernetes"
export CLUSTER_TYPE="KUBERNETES_CLUSTER"

export ADMISSION_CONTROLLER_POD_EVENTS="${ADMISSION_CONTROLLER_POD_EVENTS:-true}"
echo "ADMISSION_CONTROLLER_POD_EVENTS set to ${ADMISSION_CONTROLLER_POD_EVENTS}"
