#!/usr/bin/env bash

set -euo pipefail

copy_existing () {
    src=$1
    if [ -d "$src" ] && [ "$(ls -A -I "..*" "$src")" ]; then
        cp -v -L "$src"/* /etc/pki/ca-trust/source/anchors
    else
        echo "No certificates found in $src"
    fi
}

copy_existing /usr/local/share/ca-certificates
copy_existing /etc/pki/injected-ca-trust

update-ca-trust
