#!/bin/sh

set -e

. "$(dirname "$0")/db-functions"

BASE="/var/lib/stackrox"
RESTORE="$BASE/.restore"
BACKUP="$BASE/.backup"
CURRENT="$BASE/current"

if [ -d "$RESTORE" ]; then
	echo "Database restore directory found. Moving database files to their desired location."
	mkdir -p "$BACKUP"
	move_dbs "$CURRENT" "$BACKUP"

	rm -rf "$BASE/scorch.bleve" "$BASE/index" # Remove the indexes because a restore needs to rebuild it anyways
	move_dbs "$RESTORE" "$CURRENT"

	if [ ! -z "$(ls -A $RESTORE)" ]; then
	  echo "File(s) are not expected in $RESTORE: $(ls -A $RESTORE)"
	  exit 1
	fi
	rmdir "$RESTORE"
else
	echo "No database restore directory found (this is not an error)."
fi

rm -rf "$BASE/.restore-*" 2>/dev/null || true
