#!/usr/bin/env bash

set -euo pipefail

# Note: Any changes here should be considered for scanner/image/scanner/scripts/restore-all-dir-contents.

[ -d /.init-dirs ] || exit 0

cp -rfP /.init-dirs/* /
