#! /bin/sh

dbpath="/var/lib/stackrox/stackrox.db"
backup_boltdbpath="/var/lib/stackrox/stackrox.db.pre-rocksdb-snapshot"
rm "${backup_boltdbpath}.tmp" 2> /dev/null || true

if [ "${ROX_ROCKSDB}" == "true" ] || [ ! -f "$backup_boltdbpath" ]; then
  exit 0
fi

# If we don't want RocksDB, then copy the backup if it exists back to the original location and we should
# be able to start correctly with a BoltDB and BadgerDB
echo  >&2 "Reverting back from RocksDB to saved snapshot of BoltDB and BadgerDB"

# Archive RocksDB on rollback
if [ -d /var/lib/stackrox/rocksdb ]; then
  rocksdb_backup="/var/lib/stackrox/rocksdb-$(date +"%Y%m%d_%H%M%S")"
  echo >&2 "Archiving existing RocksDB directory. Saving /var/lib/stackrox/rocksdb to ${rocksdb_backup}"
  mv "/var/lib/stackrox/rocksdb" "${rocksdb_backup}"
fi

# Restore from backup taken
echo >&2 "Copying from ${backup_boltdbpath} to ${dbpath}"
mv "$backup_boltdbpath" "$dbpath"
echo >&2 "Removing indexes to force a rebuild"
rm -rf /var/lib/stackrox/scorch.bleve /var/lib/stackrox/index

/stackrox/bin/migrator
