// Code generated by pg-table-bindings. DO NOT EDIT.

package schema

import (
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/pkg/search"
)

var complianceintegrationsSearchFields = map[search.FieldLabel]*search.Field{
	"Cluster ID": {
		FieldPath: "compliance_integrations.cluster_id",
		Type: v1.SearchDataType_SEARCH_STRING,
		Category: v1.SearchCategory_COMPLIANCE_INTEGRATIONS,
		Hidden: true,
	},
	"Compliance Operator Installed": {
		FieldPath: "compliance_integrations.operator_installed",
		Type: v1.SearchDataType_SEARCH_BOOL,
		Category: v1.SearchCategory_COMPLIANCE_INTEGRATIONS,
		Hidden: true,
	},
	"Compliance Operator Integration ID": {
		FieldPath: "compliance_integrations.id",
		Type: v1.SearchDataType_SEARCH_STRING,
		Category: v1.SearchCategory_COMPLIANCE_INTEGRATIONS,
		Hidden: true,
	},
	"Compliance Operator Status": {
		FieldPath: "compliance_integrations.operator_status",
		Type: v1.SearchDataType_SEARCH_ENUM,
		Category: v1.SearchCategory_COMPLIANCE_INTEGRATIONS,
	},
	"Compliance Operator Version": {
		FieldPath: "compliance_integrations.version",
		Type: v1.SearchDataType_SEARCH_STRING,
		Category: v1.SearchCategory_COMPLIANCE_INTEGRATIONS,
		Hidden: true,
	},
}
