// Code generated by generate-schema tool. DO NOT EDIT.

package schema

import (
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
	"github.com/stackrox/rox/pkg/search"
)

var (
	// generatedResourceCollectionSearchFields contains pre-computed search fields for collections
	generatedResourceCollectionSearchFields = map[search.FieldLabel]*search.Field{

		"Collection": {
			FieldPath: "Id",
			Type:      v1.SearchDataType_SEARCH_STRING,
			Store:     false,
			Hidden:    false,
			Category:  v1.SearchCategory_COLLECTIONS,
		},
	}

	// generatedResourceCollectionSchema is the pre-computed schema for collections table
	generatedResourceCollectionSchema = &walker.Schema{
		Table:    "collections",
		Type:     "*storage.ResourceCollection",
		TypeName: "ResourceCollection",
		Fields: []walker.Field{

			{
				Name:       "state",
				ColumnName: "state",
				Type:       "google.golang.org/protobuf/runtime/protoimpl.MessageState",
				SQLType:    "jsonb",
				DataType:   postgres.Map,
			},

			{
				Name:       "Id",
				ColumnName: "id",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,

				Options: walker.PostgresOptions{
					PrimaryKey: true,
				},

				Search: walker.SearchField{
					Enabled:   true,
					FieldName: "Collection",
				},
			},

			{
				Name:       "Name",
				ColumnName: "name",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,

				Search: walker.SearchField{
					Enabled:   true,
					FieldName: "Collection",
				},
			},

			{
				Name:       "Description",
				ColumnName: "description",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
			},

			{
				Name:       "ResourceSelectors",
				ColumnName: "resource_selectors",
				Type:       "[]github.com/stackrox/rox/generated/storage.ResourceSelector",
				SQLType:    "jsonb",
				DataType:   postgres.Map,
			},

			{
				Name:       "EmbeddedCollections",
				ColumnName: "embedded_collections",
				Type:       "[]github.com/stackrox/rox/generated/storage.ResourceCollection_EmbeddedResourceCollection",
				SQLType:    "jsonb",
				DataType:   postgres.Map,
			},

			{
				Name:       "unknownFields",
				ColumnName: "unknown_fields",
				Type:       "google.golang.org/protobuf/runtime/protoimpl.UnknownFields",
				SQLType:    "jsonb",
				DataType:   postgres.Map,
			},

			{
				Name:       "sizeCache",
				ColumnName: "size_cache",
				Type:       "google.golang.org/protobuf/runtime/protoimpl.SizeCache",
				SQLType:    "jsonb",
				DataType:   postgres.Map,
			},
		},

		ScopingResource: resources.WorkflowAdministration,
	}
)

// GetResourceCollectionSchema returns the generated schema for collections
func GetResourceCollectionSchema() *walker.Schema {
	// Set up search options if not already done
	if generatedResourceCollectionSchema.OptionsMap == nil {
		generatedResourceCollectionSchema.SetOptionsMap(search.OptionsMapFromMap(v1.SearchCategory_COLLECTIONS, generatedResourceCollectionSearchFields))
	}
	return generatedResourceCollectionSchema
}
