// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"time"

	"github.com/lib/pq"
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/pkg/features"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
	"github.com/stackrox/rox/pkg/search"
	"github.com/stackrox/rox/pkg/search/enumregistry"
	"github.com/stackrox/rox/pkg/search/postgres/mapping"
)

var (
	// CreateTableImagesV2Stmt holds the create statement for table `images_v2`.
	CreateTableImagesV2Stmt = &postgres.CreateStmts{
		GormModel: (*ImagesV2)(nil),
		Children: []*postgres.CreateStmts{
			&postgres.CreateStmts{
				GormModel: (*ImagesV2Layers)(nil),
				Children:  []*postgres.CreateStmts{},
			},
		},
	}

	// ImagesV2Schema is the go schema for table `images_v2`.
	ImagesV2Schema = func() *walker.Schema {
		schema := GetSchemaForTable("images_v2")
		if schema != nil {
			return schema
		}
		schema = &walker.Schema{
			Table:    "images_v2",
			Type:     "*storage.ImageV2",
			TypeName: "ImageV2",
		}
		child0 := &walker.Schema{
			Parent:       schema,
			Table:        "images_v2_layers",
			Type:         "*storage.ImageLayer",
			TypeName:     "ImageLayer",
			ObjectGetter: "GetMetadata().GetV1().GetLayers()",
		}
		child0.Fields = []walker.Field{
			{Schema: child0, Name: "imageV2ID", ProtoBufName: "", ColumnName: "images_v2_Id", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("imageV2ID", true), Options: walker.PostgresOptions{PrimaryKey: true}},
			{Schema: child0, Name: "idx", ProtoBufName: "", ColumnName: "idx", Type: "int", DataType: postgres.Integer, SQLType: "integer", ModelType: "int", ObjectGetter: walker.MakeObjectGetter("idx", true), Options: walker.PostgresOptions{PrimaryKey: true}},
			{Schema: child0, Name: "Instruction", ProtoBufName: "instruction", ColumnName: "Instruction", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetInstruction()", false), Search: walker.SearchField{FieldName: "Dockerfile Instruction Keyword", Enabled: true}},
			{Schema: child0, Name: "Value", ProtoBufName: "value", ColumnName: "Value", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetValue()", false), Search: walker.SearchField{FieldName: "Dockerfile Instruction Value", Enabled: true}},
		}
		child0.Fields[0].SetParentReference(schema, "Id")
		schema.Children = []*walker.Schema{child0}
		schema.Fields = []walker.Field{
			{Schema: schema, Name: "Id", ProtoBufName: "id", ColumnName: "Id", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetId()", false), Options: walker.PostgresOptions{PrimaryKey: true}, Search: walker.SearchField{FieldName: "Image ID", Enabled: true}},
			{Schema: schema, Name: "Digest", ProtoBufName: "digest", ColumnName: "Digest", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetDigest()", false), Search: walker.SearchField{FieldName: "Image Sha", Enabled: true}, DerivedSearchFields: []walker.DerivedSearchField{{DerivedFrom: "image count", DerivationType: search.CountDerivationType, DerivedDataType: postgres.DataType("")}}},
			{Schema: schema, Name: "Registry", ProtoBufName: "registry", ColumnName: "Name_Registry", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetName().GetRegistry()", false), Search: walker.SearchField{FieldName: "Image Registry", Enabled: true}},
			{Schema: schema, Name: "Remote", ProtoBufName: "remote", ColumnName: "Name_Remote", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetName().GetRemote()", false), Search: walker.SearchField{FieldName: "Image Remote", Enabled: true}},
			{Schema: schema, Name: "Tag", ProtoBufName: "tag", ColumnName: "Name_Tag", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetName().GetTag()", false), Search: walker.SearchField{FieldName: "Image Tag", Enabled: true}},
			{Schema: schema, Name: "FullName", ProtoBufName: "full_name", ColumnName: "Name_FullName", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetName().GetFullName()", false), Search: walker.SearchField{FieldName: "Image", Enabled: true}},
			{Schema: schema, Name: "Created", ProtoBufName: "created", ColumnName: "Metadata_V1_Created", Type: "*timestamppb.Timestamp", DataType: postgres.DateTime, SQLType: "timestamp", ModelType: "*time.Time", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetCreated()", false), Search: walker.SearchField{FieldName: "Image Created Time", Enabled: true}},
			{Schema: schema, Name: "User", ProtoBufName: "user", ColumnName: "Metadata_V1_User", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetUser()", false), Search: walker.SearchField{FieldName: "Image User", Enabled: true}},
			{Schema: schema, Name: "Command", ProtoBufName: "command", ColumnName: "Metadata_V1_Command", Type: "[]string", DataType: postgres.StringArray, SQLType: "text[]", ModelType: "*pq.StringArray", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetCommand()", false), Search: walker.SearchField{FieldName: "Image Command", Enabled: true}},
			{Schema: schema, Name: "Entrypoint", ProtoBufName: "entrypoint", ColumnName: "Metadata_V1_Entrypoint", Type: "[]string", DataType: postgres.StringArray, SQLType: "text[]", ModelType: "*pq.StringArray", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetEntrypoint()", false), Search: walker.SearchField{FieldName: "Image Entrypoint", Enabled: true}},
			{Schema: schema, Name: "Volumes", ProtoBufName: "volumes", ColumnName: "Metadata_V1_Volumes", Type: "[]string", DataType: postgres.StringArray, SQLType: "text[]", ModelType: "*pq.StringArray", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetVolumes()", false), Search: walker.SearchField{FieldName: "Image Volumes", Enabled: true}},
			{Schema: schema, Name: "Labels", ProtoBufName: "labels", ColumnName: "Metadata_V1_Labels", Type: "map[string]string", DataType: postgres.Map, SQLType: "jsonb", ModelType: "map[string]string", ObjectGetter: walker.MakeObjectGetter("GetMetadata().GetV1().GetLabels()", false), Search: walker.SearchField{FieldName: "Image Label", Enabled: true}},
			{Schema: schema, Name: "ScanTime", ProtoBufName: "scan_time", ColumnName: "Scan_ScanTime", Type: "*timestamppb.Timestamp", DataType: postgres.DateTime, SQLType: "timestamp", ModelType: "*time.Time", ObjectGetter: walker.MakeObjectGetter("GetScan().GetScanTime()", false), Search: walker.SearchField{FieldName: "Image Scan Time", Enabled: true}},
			{Schema: schema, Name: "OperatingSystem", ProtoBufName: "operating_system", ColumnName: "Scan_OperatingSystem", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetScan().GetOperatingSystem()", false), Search: walker.SearchField{FieldName: "Image OS", Enabled: true}},
			{Schema: schema, Name: "Fetched", ProtoBufName: "fetched", ColumnName: "Signature_Fetched", Type: "*timestamppb.Timestamp", DataType: postgres.DateTime, SQLType: "timestamp", ModelType: "*time.Time", ObjectGetter: walker.MakeObjectGetter("GetSignature().GetFetched()", false), Search: walker.SearchField{FieldName: "Image Signature Fetched Time", Enabled: true}},
			{Schema: schema, Name: "ComponentCount", ProtoBufName: "component_count", ColumnName: "ScanStats_ComponentCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetComponentCount()", false), Search: walker.SearchField{FieldName: "Image Component Count", Enabled: true}},
			{Schema: schema, Name: "CveCount", ProtoBufName: "cve_count", ColumnName: "ScanStats_CveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetCveCount()", false), Search: walker.SearchField{FieldName: "Image CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableCveCount", ProtoBufName: "fixable_cve_count", ColumnName: "ScanStats_FixableCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableCveCount()", false), Search: walker.SearchField{FieldName: "Fixable CVE Count", Enabled: true}},
			{Schema: schema, Name: "UnknownCveCount", ProtoBufName: "unknown_cve_count", ColumnName: "ScanStats_UnknownCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetUnknownCveCount()", false), Search: walker.SearchField{FieldName: "Unknown CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableUnknownCveCount", ProtoBufName: "fixable_unknown_cve_count", ColumnName: "ScanStats_FixableUnknownCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableUnknownCveCount()", false), Search: walker.SearchField{FieldName: "Fixable Unknown CVE Count", Enabled: true}},
			{Schema: schema, Name: "CriticalCveCount", ProtoBufName: "critical_cve_count", ColumnName: "ScanStats_CriticalCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetCriticalCveCount()", false), Search: walker.SearchField{FieldName: "Critical CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableCriticalCveCount", ProtoBufName: "fixable_critical_cve_count", ColumnName: "ScanStats_FixableCriticalCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableCriticalCveCount()", false), Search: walker.SearchField{FieldName: "Fixable Critical CVE Count", Enabled: true}},
			{Schema: schema, Name: "ImportantCveCount", ProtoBufName: "important_cve_count", ColumnName: "ScanStats_ImportantCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetImportantCveCount()", false), Search: walker.SearchField{FieldName: "Important CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableImportantCveCount", ProtoBufName: "fixable_important_cve_count", ColumnName: "ScanStats_FixableImportantCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableImportantCveCount()", false), Search: walker.SearchField{FieldName: "Fixable Important CVE Count", Enabled: true}},
			{Schema: schema, Name: "ModerateCveCount", ProtoBufName: "moderate_cve_count", ColumnName: "ScanStats_ModerateCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetModerateCveCount()", false), Search: walker.SearchField{FieldName: "Moderate CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableModerateCveCount", ProtoBufName: "fixable_moderate_cve_count", ColumnName: "ScanStats_FixableModerateCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableModerateCveCount()", false), Search: walker.SearchField{FieldName: "Fixable Moderate CVE Count", Enabled: true}},
			{Schema: schema, Name: "LowCveCount", ProtoBufName: "low_cve_count", ColumnName: "ScanStats_LowCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetLowCveCount()", false), Search: walker.SearchField{FieldName: "Low CVE Count", Enabled: true}},
			{Schema: schema, Name: "FixableLowCveCount", ProtoBufName: "fixable_low_cve_count", ColumnName: "ScanStats_FixableLowCveCount", Type: "int32", DataType: postgres.Integer, SQLType: "integer", ModelType: "int32", ObjectGetter: walker.MakeObjectGetter("GetScanStats().GetFixableLowCveCount()", false), Search: walker.SearchField{FieldName: "Fixable Low CVE Count", Enabled: true}},
			{Schema: schema, Name: "LastUpdated", ProtoBufName: "last_updated", ColumnName: "LastUpdated", Type: "*timestamppb.Timestamp", DataType: postgres.DateTime, SQLType: "timestamp", ModelType: "*time.Time", ObjectGetter: walker.MakeObjectGetter("GetLastUpdated()", false), Search: walker.SearchField{FieldName: "Last Updated", Enabled: true}},
			{Schema: schema, Name: "Priority", ProtoBufName: "priority", ColumnName: "Priority", Type: "int64", DataType: postgres.BigInteger, SQLType: "bigint", ModelType: "int64", ObjectGetter: walker.MakeObjectGetter("GetPriority()", false), Search: walker.SearchField{FieldName: "Image Risk Priority", Enabled: true}, Derived: true},
			{Schema: schema, Name: "RiskScore", ProtoBufName: "risk_score", ColumnName: "RiskScore", Type: "float32", DataType: postgres.Numeric, SQLType: "numeric", ModelType: "float32", ObjectGetter: walker.MakeObjectGetter("GetRiskScore()", false), Search: walker.SearchField{FieldName: "Image Risk Score", Enabled: true}, DerivedSearchFields: []walker.DerivedSearchField{{DerivedFrom: "image risk priority", DerivationType: search.SimpleReverseSortDerivationType, DerivedDataType: postgres.DataType("")}}},
			{Schema: schema, Name: "TopCvss", ProtoBufName: "top_cvss", ColumnName: "TopCvss", Type: "float32", DataType: postgres.Numeric, SQLType: "numeric", ModelType: "float32", ObjectGetter: walker.MakeObjectGetter("GetTopCvss()", false), Search: walker.SearchField{FieldName: "Image Top CVSS", Enabled: true}},
			{Schema: schema, Name: "serialized", ProtoBufName: "", ColumnName: "serialized", Type: "[]byte", DataType: postgres.DataType(""), SQLType: "bytea", ModelType: "[]byte", ObjectGetter: walker.MakeObjectGetter("serialized", true)},
		}

		schema.SetOptionsMap(search.OptionsMapFromMap(v1.SearchCategory_IMAGES_V2, map[search.FieldLabel]*search.Field{
			"Advisory Link":                  {FieldPath: "imagev2.scan.components.vulns.advisory.link", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Advisory Name":                  {FieldPath: "imagev2.scan.components.vulns.advisory.name", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"CVE":                            {FieldPath: "imagev2.scan.components.vulns.cve", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"CVE Published On":               {FieldPath: "imagev2.scan.components.vulns.published_on.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Category: v1.SearchCategory_IMAGES_V2},
			"CVE Snoozed":                    {FieldPath: "imagev2.scan.components.vulns.suppressed", Type: v1.SearchDataType_SEARCH_BOOL, Category: v1.SearchCategory_IMAGES_V2},
			"CVSS":                           {FieldPath: "imagev2.scan.components.vulns.cvss", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory_IMAGES_V2},
			"Component":                      {FieldPath: "imagev2.scan.components.name", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Component Risk Score":           {FieldPath: "imagev2.scan.components.risk_score", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Component Version":              {FieldPath: "imagev2.scan.components.version", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Critical CVE Count":             {FieldPath: "imagev2.scan_stats.critical_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Dockerfile Instruction Keyword": {FieldPath: "imagev2.metadata.v1.layers.instruction", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Dockerfile Instruction Value":   {FieldPath: "imagev2.metadata.v1.layers.value", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"EPSS Probability":               {FieldPath: "imagev2.scan.components.vulns.epss.epss_probability", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable CVE Count":              {FieldPath: "imagev2.scan_stats.fixable_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable Critical CVE Count":     {FieldPath: "imagev2.scan_stats.fixable_critical_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable Important CVE Count":    {FieldPath: "imagev2.scan_stats.fixable_important_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable Low CVE Count":          {FieldPath: "imagev2.scan_stats.fixable_low_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable Moderate CVE Count":     {FieldPath: "imagev2.scan_stats.fixable_moderate_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixable Unknown CVE Count":      {FieldPath: "imagev2.scan_stats.fixable_unknown_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Fixed By":                       {FieldPath: "imagev2.scan.components.vulns.SetFixedBy.FixedBy", Type: v1.SearchDataType_SEARCH_STRING, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image":                          {FieldPath: "imagev2.name.full_name", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2, Analyzer: "standard"},
			"Image CVE Count":                {FieldPath: "imagev2.scan_stats.cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Command":                  {FieldPath: "imagev2.metadata.v1.command", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Component Count":          {FieldPath: "imagev2.scan_stats.component_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Created Time":             {FieldPath: "imagev2.metadata.v1.created.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Category: v1.SearchCategory_IMAGES_V2},
			"Image Entrypoint":               {FieldPath: "imagev2.metadata.v1.entrypoint", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image ID":                       {FieldPath: "imagev2.id", Type: v1.SearchDataType_SEARCH_STRING, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Label":                    {FieldPath: "imagev2.metadata.v1.labels", Type: v1.SearchDataType_SEARCH_MAP, Category: v1.SearchCategory_IMAGES_V2},
			"Image OS":                       {FieldPath: "imagev2.scan.operating_system", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Registry":                 {FieldPath: "imagev2.name.registry", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Remote":                   {FieldPath: "imagev2.name.remote", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Risk Priority":            {FieldPath: "imagev2.priority", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Risk Score":               {FieldPath: "imagev2.risk_score", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Scan Time":                {FieldPath: "imagev2.scan.scan_time.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Category: v1.SearchCategory_IMAGES_V2},
			"Image Sha":                      {FieldPath: "imagev2.digest", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Signature Fetched Time":   {FieldPath: "imagev2.signature.fetched.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Image Tag":                      {FieldPath: "imagev2.name.tag", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Top CVSS":                 {FieldPath: "imagev2.top_cvss", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory_IMAGES_V2},
			"Image User":                     {FieldPath: "imagev2.metadata.v1.user", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Image Volumes":                  {FieldPath: "imagev2.metadata.v1.volumes", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory_IMAGES_V2},
			"Important CVE Count":            {FieldPath: "imagev2.scan_stats.important_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Last Updated":                   {FieldPath: "imagev2.last_updated.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Low CVE Count":                  {FieldPath: "imagev2.scan_stats.low_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Moderate CVE Count":             {FieldPath: "imagev2.scan_stats.moderate_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"NVD CVSS":                       {FieldPath: "imagev2.scan.components.vulns.nvd_cvss", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory_IMAGES_V2},
			"Unknown CVE Count":              {FieldPath: "imagev2.scan_stats.unknown_cve_count", Type: v1.SearchDataType_SEARCH_NUMERIC, Hidden: true, Category: v1.SearchCategory_IMAGES_V2},
			"Vulnerability State":            {FieldPath: "imagev2.scan.components.vulns.state", Type: v1.SearchDataType_SEARCH_ENUM, Category: v1.SearchCategory_IMAGES_V2},
		}))
		enumregistry.AddValues("imagev2.notes", map[string]int32{"MISSING_METADATA": 0, "MISSING_SCAN_DATA": 1, "MISSING_SIGNATURE": 2, "MISSING_SIGNATURE_VERIFICATION_DATA": 3})
		enumregistry.AddValues("imagev2.scan.components.source", map[string]int32{"DOTNETCORERUNTIME": 5, "GO": 7, "INFRASTRUCTURE": 6, "JAVA": 2, "NODEJS": 4, "OS": 0, "PYTHON": 1, "RUBY": 3})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.access_complexity", map[string]int32{"ACCESS_HIGH": 0, "ACCESS_LOW": 2, "ACCESS_MEDIUM": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.attack_vector", map[string]int32{"ATTACK_ADJACENT": 1, "ATTACK_LOCAL": 0, "ATTACK_NETWORK": 2})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.authentication", map[string]int32{"AUTH_MULTIPLE": 0, "AUTH_NONE": 2, "AUTH_SINGLE": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.availability", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.confidentiality", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.integrity", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv2.severity", map[string]int32{"HIGH": 3, "LOW": 1, "MEDIUM": 2, "UNKNOWN": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.attack_complexity", map[string]int32{"COMPLEXITY_HIGH": 1, "COMPLEXITY_LOW": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.attack_vector", map[string]int32{"ATTACK_ADJACENT": 1, "ATTACK_LOCAL": 0, "ATTACK_NETWORK": 2, "ATTACK_PHYSICAL": 3})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.availability", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.confidentiality", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.integrity", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.privileges_required", map[string]int32{"PRIVILEGE_HIGH": 2, "PRIVILEGE_LOW": 1, "PRIVILEGE_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.scope", map[string]int32{"CHANGED": 1, "UNCHANGED": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.severity", map[string]int32{"CRITICAL": 5, "HIGH": 4, "LOW": 2, "MEDIUM": 3, "NONE": 1, "UNKNOWN": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.CvssScore.Cvssv3.user_interaction", map[string]int32{"UI_NONE": 0, "UI_REQUIRED": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_metrics.source", map[string]int32{"SOURCE_NVD": 3, "SOURCE_OSV": 2, "SOURCE_RED_HAT": 1, "SOURCE_UNKNOWN": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.access_complexity", map[string]int32{"ACCESS_HIGH": 0, "ACCESS_LOW": 2, "ACCESS_MEDIUM": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.attack_vector", map[string]int32{"ATTACK_ADJACENT": 1, "ATTACK_LOCAL": 0, "ATTACK_NETWORK": 2})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.authentication", map[string]int32{"AUTH_MULTIPLE": 0, "AUTH_NONE": 2, "AUTH_SINGLE": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.availability", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.confidentiality", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.integrity", map[string]int32{"IMPACT_COMPLETE": 2, "IMPACT_NONE": 0, "IMPACT_PARTIAL": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v2.severity", map[string]int32{"HIGH": 3, "LOW": 1, "MEDIUM": 2, "UNKNOWN": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.attack_complexity", map[string]int32{"COMPLEXITY_HIGH": 1, "COMPLEXITY_LOW": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.attack_vector", map[string]int32{"ATTACK_ADJACENT": 1, "ATTACK_LOCAL": 0, "ATTACK_NETWORK": 2, "ATTACK_PHYSICAL": 3})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.availability", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.confidentiality", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.integrity", map[string]int32{"IMPACT_HIGH": 2, "IMPACT_LOW": 1, "IMPACT_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.privileges_required", map[string]int32{"PRIVILEGE_HIGH": 2, "PRIVILEGE_LOW": 1, "PRIVILEGE_NONE": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.scope", map[string]int32{"CHANGED": 1, "UNCHANGED": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.severity", map[string]int32{"CRITICAL": 5, "HIGH": 4, "LOW": 2, "MEDIUM": 3, "NONE": 1, "UNKNOWN": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.cvss_v3.user_interaction", map[string]int32{"UI_NONE": 0, "UI_REQUIRED": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.score_version", map[string]int32{"V2": 0, "V3": 1})
		enumregistry.AddValues("imagev2.scan.components.vulns.severity", map[string]int32{"CRITICAL_VULNERABILITY_SEVERITY": 4, "IMPORTANT_VULNERABILITY_SEVERITY": 3, "LOW_VULNERABILITY_SEVERITY": 1, "MODERATE_VULNERABILITY_SEVERITY": 2, "UNKNOWN_VULNERABILITY_SEVERITY": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.state", map[string]int32{"DEFERRED": 1, "FALSE_POSITIVE": 2, "OBSERVED": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.vulnerability_type", map[string]int32{"IMAGE_VULNERABILITY": 1, "ISTIO_VULNERABILITY": 3, "K8S_VULNERABILITY": 2, "NODE_VULNERABILITY": 4, "OPENSHIFT_VULNERABILITY": 5, "UNKNOWN_VULNERABILITY": 0})
		enumregistry.AddValues("imagev2.scan.components.vulns.vulnerability_types", map[string]int32{"IMAGE_VULNERABILITY": 1, "ISTIO_VULNERABILITY": 3, "K8S_VULNERABILITY": 2, "NODE_VULNERABILITY": 4, "OPENSHIFT_VULNERABILITY": 5, "UNKNOWN_VULNERABILITY": 0})
		enumregistry.AddValues("imagev2.scan.notes", map[string]int32{"CERTIFIED_RHEL_SCAN_UNAVAILABLE": 6, "LANGUAGE_CVES_UNAVAILABLE": 5, "OS_CVES_STALE": 4, "OS_CVES_UNAVAILABLE": 3, "OS_UNAVAILABLE": 1, "PARTIAL_SCAN_DATA": 2, "UNSET": 0})
		enumregistry.AddValues("imagev2.signature.signatures.Signature.Cosign.signature_format", map[string]int32{"DEAD_SIMPLE_SIGNING_ENVELOPE": 2, "SIGNATURE_FORMAT_UNSPECIFIED": 0, "SIMPLE_SIGNING": 1})
		enumregistry.AddValues("imagev2.signature_verification_data.results.status", map[string]int32{"CORRUPTED_SIGNATURE": 4, "FAILED_VERIFICATION": 2, "GENERIC_ERROR": 5, "INVALID_SIGNATURE_ALGO": 3, "UNSET": 0, "VERIFIED": 1})

		schema.SetSearchScope([]v1.SearchCategory{
			v1.SearchCategory_IMAGE_VULNERABILITIES_V2,
			v1.SearchCategory_IMAGE_COMPONENTS_V2,
			v1.SearchCategory_IMAGES_V2,
			v1.SearchCategory_DEPLOYMENTS,
			v1.SearchCategory_NAMESPACES,
			v1.SearchCategory_CLUSTERS,
		}...)
		schema.ScopingResource = resources.Image
		RegisterTable(schema, CreateTableImagesV2Stmt, features.FlattenImageData.Enabled)
		mapping.RegisterCategoryToTable(v1.SearchCategory_IMAGES_V2, schema)
		return schema
	}()
)

const (
	// ImagesV2TableName specifies the name of the table in postgres.
	ImagesV2TableName = "images_v2"
	// ImagesV2LayersTableName specifies the name of the table in postgres.
	ImagesV2LayersTableName = "images_v2_layers"
)

// ImagesV2 holds the Gorm model for Postgres table `images_v2`.
type ImagesV2 struct {
	ID                                string            `gorm:"column:id;type:varchar;primaryKey"`
	Digest                            string            `gorm:"column:digest;type:varchar"`
	NameRegistry                      string            `gorm:"column:name_registry;type:varchar"`
	NameRemote                        string            `gorm:"column:name_remote;type:varchar"`
	NameTag                           string            `gorm:"column:name_tag;type:varchar"`
	NameFullName                      string            `gorm:"column:name_fullname;type:varchar"`
	MetadataV1Created                 *time.Time        `gorm:"column:metadata_v1_created;type:timestamp"`
	MetadataV1User                    string            `gorm:"column:metadata_v1_user;type:varchar"`
	MetadataV1Command                 *pq.StringArray   `gorm:"column:metadata_v1_command;type:text[]"`
	MetadataV1Entrypoint              *pq.StringArray   `gorm:"column:metadata_v1_entrypoint;type:text[]"`
	MetadataV1Volumes                 *pq.StringArray   `gorm:"column:metadata_v1_volumes;type:text[]"`
	MetadataV1Labels                  map[string]string `gorm:"column:metadata_v1_labels;type:jsonb"`
	ScanScanTime                      *time.Time        `gorm:"column:scan_scantime;type:timestamp"`
	ScanOperatingSystem               string            `gorm:"column:scan_operatingsystem;type:varchar"`
	SignatureFetched                  *time.Time        `gorm:"column:signature_fetched;type:timestamp"`
	ScanStatsComponentCount           int32             `gorm:"column:scanstats_componentcount;type:integer"`
	ScanStatsCveCount                 int32             `gorm:"column:scanstats_cvecount;type:integer"`
	ScanStatsFixableCveCount          int32             `gorm:"column:scanstats_fixablecvecount;type:integer"`
	ScanStatsUnknownCveCount          int32             `gorm:"column:scanstats_unknowncvecount;type:integer"`
	ScanStatsFixableUnknownCveCount   int32             `gorm:"column:scanstats_fixableunknowncvecount;type:integer"`
	ScanStatsCriticalCveCount         int32             `gorm:"column:scanstats_criticalcvecount;type:integer"`
	ScanStatsFixableCriticalCveCount  int32             `gorm:"column:scanstats_fixablecriticalcvecount;type:integer"`
	ScanStatsImportantCveCount        int32             `gorm:"column:scanstats_importantcvecount;type:integer"`
	ScanStatsFixableImportantCveCount int32             `gorm:"column:scanstats_fixableimportantcvecount;type:integer"`
	ScanStatsModerateCveCount         int32             `gorm:"column:scanstats_moderatecvecount;type:integer"`
	ScanStatsFixableModerateCveCount  int32             `gorm:"column:scanstats_fixablemoderatecvecount;type:integer"`
	ScanStatsLowCveCount              int32             `gorm:"column:scanstats_lowcvecount;type:integer"`
	ScanStatsFixableLowCveCount       int32             `gorm:"column:scanstats_fixablelowcvecount;type:integer"`
	LastUpdated                       *time.Time        `gorm:"column:lastupdated;type:timestamp"`
	Priority                          int64             `gorm:"column:priority;type:bigint"`
	RiskScore                         float32           `gorm:"column:riskscore;type:numeric"`
	TopCvss                           float32           `gorm:"column:topcvss;type:numeric"`
	Serialized                        []byte            `gorm:"column:serialized;type:bytea"`
}

// ImagesV2Layers holds the Gorm model for Postgres table `images_v2_layers`.
type ImagesV2Layers struct {
	ImagesV2ID  string   `gorm:"column:images_v2_id;type:varchar;primaryKey"`
	Idx         int      `gorm:"column:idx;type:integer;primaryKey"`
	Instruction string   `gorm:"column:instruction;type:varchar"`
	Value       string   `gorm:"column:value;type:varchar"`
	ImagesV2Ref ImagesV2 `gorm:"foreignKey:images_v2_id;references:id;belongsTo;constraint:OnDelete:CASCADE"`
}
