// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/schema/internal"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
)

var (
	// CreateTableSignatureIntegrationsStmt holds the create statement for table `signature_integrations`.
	CreateTableSignatureIntegrationsStmt = &postgres.CreateStmts{
		GormModel: (*SignatureIntegrations)(nil),
		Children:  []*postgres.CreateStmts{},
	}

	// SignatureIntegrationsSchema is the go schema for table `signature_integrations`.
	SignatureIntegrationsSchema = func() *walker.Schema {
		schema := GetSchemaForTable("signature_integrations")
		if schema != nil {
			return schema
		}
		schema = internal.GetSignatureIntegrationSchema()
		schema.ScopingResource = resources.Integration
		RegisterTable(schema, CreateTableSignatureIntegrationsStmt)
		return schema
	}()
)

const (
	// SignatureIntegrationsTableName specifies the name of the table in postgres.
	SignatureIntegrationsTableName = "signature_integrations"
)

// SignatureIntegrations holds the Gorm model for Postgres table `signature_integrations`.
type SignatureIntegrations struct {
	ID         string `gorm:"column:id;type:varchar;primaryKey"`
	Name       string `gorm:"column:name;type:varchar;unique"`
	Serialized []byte `gorm:"column:serialized;type:bytea"`
}
