// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"reflect"
	"time"

	"github.com/lib/pq"
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
	"github.com/stackrox/rox/pkg/search"
	"github.com/stackrox/rox/pkg/search/postgres/mapping"
)

var (
	// CreateTableTestNoSerializedObjsStmt holds the create statement for table `test_no_serialized_objs`.
	CreateTableTestNoSerializedObjsStmt = &postgres.CreateStmts{
		GormModel: (*TestNoSerializedObjs)(nil),
		Children:  []*postgres.CreateStmts{},
	}

	// TestNoSerializedObjsSchema is the go schema for table `test_no_serialized_objs`.
	TestNoSerializedObjsSchema = func() *walker.Schema {
		schema := GetSchemaForTable("test_no_serialized_objs")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.TestNoSerializedObj)(nil)), "test_no_serialized_objs", walker.WithNoSerialized())
		schema.SetOptionsMap(search.Walk(v1.SearchCategory_TEST_NO_SERIALIZED, "testnoserializedobj", (*storage.TestNoSerializedObj)(nil)))
		schema.ScopingResource = resources.Namespace
		RegisterTable(schema, CreateTableTestNoSerializedObjsStmt)
		mapping.RegisterCategoryToTable(v1.SearchCategory_TEST_NO_SERIALIZED, schema)
		return schema
	}()
)

const (
	// TestNoSerializedObjsTableName specifies the name of the table in postgres.
	TestNoSerializedObjsTableName = "test_no_serialized_objs"
)

// TestNoSerializedObjs holds the Gorm model for Postgres table `test_no_serialized_objs`.
type TestNoSerializedObjs struct {
	ID          string                              `gorm:"column:id;type:uuid;primaryKey"`
	Name        string                              `gorm:"column:name;type:varchar"`
	ValueInt32  int32                               `gorm:"column:valueint32;type:integer"`
	ValueInt64  int64                               `gorm:"column:valueint64;type:bigint"`
	ValueUint32 uint32                              `gorm:"column:valueuint32;type:bigint"`
	ValueUint64 uint64                              `gorm:"column:valueuint64;type:numeric"`
	ValueBool   bool                                `gorm:"column:valuebool;type:bool"`
	ValueFloat  float32                             `gorm:"column:valuefloat;type:numeric"`
	ValueEnum   storage.TestNoSerializedEnum        `gorm:"column:valueenum;type:integer"`
	CreatedAt   *time.Time                          `gorm:"column:createdat;type:timestamp"`
	NestedLabel string                              `gorm:"column:nested_label;type:varchar"`
	NestedScore int64                               `gorm:"column:nested_score;type:bigint"`
	Tags        *pq.StringArray                     `gorm:"column:tags;type:text[]"`
	Metadata    []*storage.TestNoSerializedMetadata `gorm:"column:metadata;type:bytea"`
}
