// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"time"

	"github.com/lib/pq"
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
	"github.com/stackrox/rox/pkg/search"
	"github.com/stackrox/rox/pkg/search/enumregistry"
	"github.com/stackrox/rox/pkg/search/postgres/mapping"
)

var (
	// CreateTableTestSingleUUIDKeyStructsStmt holds the create statement for table `test_single_uuid_key_structs`.
	CreateTableTestSingleUUIDKeyStructsStmt = &postgres.CreateStmts{
		GormModel: (*TestSingleUUIDKeyStructs)(nil),
		Children:  []*postgres.CreateStmts{},
		Indexes: []*postgres.IndexDefinition{
			{Name: "testsingleuuidkeystructs_key", CreateSQL: "CREATE INDEX CONCURRENTLY IF NOT EXISTS testsingleuuidkeystructs_key ON test_single_uuid_key_structs USING hash (key)"},
		},
	}

	// TestSingleUUIDKeyStructsSchema is the go schema for table `test_single_uuid_key_structs`.
	TestSingleUUIDKeyStructsSchema = func() *walker.Schema {
		schema := GetSchemaForTable("test_single_uuid_key_structs")
		if schema != nil {
			return schema
		}
		schema = &walker.Schema{
			Table:    "test_single_uuid_key_structs",
			Type:     "*storage.TestSingleUUIDKeyStruct",
			TypeName: "TestSingleUUIDKeyStruct",
		}
		schema.Fields = []walker.Field{
			{Schema: schema, Name: "Key", ProtoBufName: "key", ColumnName: "Key", Type: "string", DataType: postgres.String, SQLType: "uuid", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetKey()", false), Options: walker.PostgresOptions{PrimaryKey: true, ColumnType: "uuid"}, Search: walker.SearchField{FieldName: "Test Key", Enabled: true}},
			{Schema: schema, Name: "Name", ProtoBufName: "name", ColumnName: "Name", Type: "string", DataType: postgres.String, SQLType: "varchar", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetName()", false), Options: walker.PostgresOptions{Unique: true}, Search: walker.SearchField{FieldName: "Test Name", Enabled: true}},
			{Schema: schema, Name: "StringSlice", ProtoBufName: "string_slice", ColumnName: "StringSlice", Type: "[]string", DataType: postgres.StringArray, SQLType: "text[]", ModelType: "*pq.StringArray", ObjectGetter: walker.MakeObjectGetter("GetStringSlice()", false), Search: walker.SearchField{FieldName: "Test String Slice", Enabled: true}},
			{Schema: schema, Name: "Bool", ProtoBufName: "bool", ColumnName: "Bool", Type: "bool", DataType: postgres.Bool, SQLType: "bool", ModelType: "bool", ObjectGetter: walker.MakeObjectGetter("GetBool()", false), Search: walker.SearchField{FieldName: "Test Bool", Enabled: true}},
			{Schema: schema, Name: "Uint64", ProtoBufName: "uint64", ColumnName: "Uint64", Type: "uint64", DataType: postgres.Numeric, SQLType: "numeric", ModelType: "uint64", ObjectGetter: walker.MakeObjectGetter("GetUint64()", false), Search: walker.SearchField{FieldName: "Test Uint64", Enabled: true}},
			{Schema: schema, Name: "Int64", ProtoBufName: "int64", ColumnName: "Int64", Type: "int64", DataType: postgres.BigInteger, SQLType: "bigint", ModelType: "int64", ObjectGetter: walker.MakeObjectGetter("GetInt64()", false), Search: walker.SearchField{FieldName: "Test Int64", Enabled: true}},
			{Schema: schema, Name: "Float", ProtoBufName: "float", ColumnName: "Float", Type: "float32", DataType: postgres.Numeric, SQLType: "numeric", ModelType: "float32", ObjectGetter: walker.MakeObjectGetter("GetFloat()", false), Search: walker.SearchField{FieldName: "Test Float", Enabled: true}},
			{Schema: schema, Name: "Labels", ProtoBufName: "labels", ColumnName: "Labels", Type: "map[string]string", DataType: postgres.Map, SQLType: "jsonb", ModelType: "map[string]string", ObjectGetter: walker.MakeObjectGetter("GetLabels()", false), Search: walker.SearchField{FieldName: "Test Labels", Enabled: true}},
			{Schema: schema, Name: "Timestamp", ProtoBufName: "timestamp", ColumnName: "Timestamp", Type: "*timestamppb.Timestamp", DataType: postgres.DateTime, SQLType: "timestamp", ModelType: "*time.Time", ObjectGetter: walker.MakeObjectGetter("GetTimestamp()", false), Search: walker.SearchField{FieldName: "Test Timestamp", Enabled: true}},
			{Schema: schema, Name: "Enum", ProtoBufName: "enum", ColumnName: "Enum", Type: "storage.TestSingleUUIDKeyStruct_Enum", DataType: postgres.Enum, SQLType: "integer", ModelType: "storage.TestSingleUUIDKeyStruct_Enum", ObjectGetter: walker.MakeObjectGetter("GetEnum()", false), Search: walker.SearchField{FieldName: "Test Enum", Enabled: true}, DerivedSearchFields: []walker.DerivedSearchField{{DerivedFrom: "test string affected by enum2", DerivationType: search.CustomFieldType, DerivedDataType: postgres.Integer}, {DerivedFrom: "invalid test string affected by enum1", DerivationType: search.CustomFieldType, DerivedDataType: postgres.Integer}, {DerivedFrom: "test string affected by enum1", DerivationType: search.CustomFieldType, DerivedDataType: postgres.Integer}}},
			{Schema: schema, Name: "Enums", ProtoBufName: "enums", ColumnName: "Enums", Type: "[]storage.TestSingleUUIDKeyStruct_Enum", DataType: postgres.EnumArray, SQLType: "int[]", ModelType: "*pq.Int32Array", ObjectGetter: walker.MakeObjectGetter("GetEnums()", false), Search: walker.SearchField{FieldName: "Test Enum Slice", Enabled: true}},
			{Schema: schema, Name: "OptionalUuid", ProtoBufName: "optional_uuid", ColumnName: "OptionalUuid", Type: "string", DataType: postgres.String, SQLType: "uuid", ModelType: "string", ObjectGetter: walker.MakeObjectGetter("GetOptionalUuid()", false), Options: walker.PostgresOptions{ColumnType: "uuid"}, Search: walker.SearchField{FieldName: "Test UUID", Enabled: true}},
			{Schema: schema, Name: "serialized", ProtoBufName: "", ColumnName: "serialized", Type: "[]byte", DataType: postgres.DataType(""), SQLType: "bytea", ModelType: "[]byte", ObjectGetter: walker.MakeObjectGetter("serialized", true)},
		}

		schema.SetOptionsMap(search.OptionsMapFromMap(v1.SearchCategory(115), map[search.FieldLabel]*search.Field{
			"Test Bool":         {FieldPath: "testsingleuuidkeystruct.bool", Type: v1.SearchDataType_SEARCH_BOOL, Category: v1.SearchCategory(115)},
			"Test Enum":         {FieldPath: "testsingleuuidkeystruct.enum", Type: v1.SearchDataType_SEARCH_ENUM, Category: v1.SearchCategory(115)},
			"Test Enum Slice":   {FieldPath: "testsingleuuidkeystruct.enums", Type: v1.SearchDataType_SEARCH_ENUM, Category: v1.SearchCategory(115)},
			"Test Float":        {FieldPath: "testsingleuuidkeystruct.float", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory(115)},
			"Test Int64":        {FieldPath: "testsingleuuidkeystruct.int64", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory(115)},
			"Test Key":          {FieldPath: "testsingleuuidkeystruct.key", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory(115)},
			"Test Labels":       {FieldPath: "testsingleuuidkeystruct.labels", Type: v1.SearchDataType_SEARCH_MAP, Category: v1.SearchCategory(115)},
			"Test Name":         {FieldPath: "testsingleuuidkeystruct.name", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory(115)},
			"Test String Slice": {FieldPath: "testsingleuuidkeystruct.string_slice", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory(115)},
			"Test Timestamp":    {FieldPath: "testsingleuuidkeystruct.timestamp.seconds", Type: v1.SearchDataType_SEARCH_DATETIME, Category: v1.SearchCategory(115)},
			"Test UUID":         {FieldPath: "testsingleuuidkeystruct.optional_uuid", Type: v1.SearchDataType_SEARCH_STRING, Category: v1.SearchCategory(115)},
			"Test Uint64":       {FieldPath: "testsingleuuidkeystruct.uint64", Type: v1.SearchDataType_SEARCH_NUMERIC, Category: v1.SearchCategory(115)},
		}))
		enumregistry.AddValues("testsingleuuidkeystruct.enum", map[string]int32{"ENUM0": 0, "ENUM1": 1, "ENUM2": 2})
		enumregistry.AddValues("testsingleuuidkeystruct.enums", map[string]int32{"ENUM0": 0, "ENUM1": 1, "ENUM2": 2})

		schema.ScopingResource = resources.Namespace
		RegisterTable(schema, CreateTableTestSingleUUIDKeyStructsStmt)
		mapping.RegisterCategoryToTable(v1.SearchCategory(115), schema)
		return schema
	}()
)

const (
	// TestSingleUUIDKeyStructsTableName specifies the name of the table in postgres.
	TestSingleUUIDKeyStructsTableName = "test_single_uuid_key_structs"
)

// TestSingleUUIDKeyStructs holds the Gorm model for Postgres table `test_single_uuid_key_structs`.
type TestSingleUUIDKeyStructs struct {
	Key          string                               `gorm:"column:key;type:uuid;primaryKey"`
	Name         string                               `gorm:"column:name;type:varchar;unique"`
	StringSlice  *pq.StringArray                      `gorm:"column:stringslice;type:text[]"`
	Bool         bool                                 `gorm:"column:bool;type:bool"`
	Uint64       uint64                               `gorm:"column:uint64;type:numeric"`
	Int64        int64                                `gorm:"column:int64;type:bigint"`
	Float        float32                              `gorm:"column:float;type:numeric"`
	Labels       map[string]string                    `gorm:"column:labels;type:jsonb"`
	Timestamp    *time.Time                           `gorm:"column:timestamp;type:timestamp"`
	Enum         storage.TestSingleUUIDKeyStruct_Enum `gorm:"column:enum;type:integer"`
	Enums        *pq.Int32Array                       `gorm:"column:enums;type:int[]"`
	OptionalUUID string                               `gorm:"column:optionaluuid;type:uuid"`
	Serialized   []byte                               `gorm:"column:serialized;type:bytea"`
}
