# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  scanner:
    name: scanner-v4
    image:
      registry: quay.io/stackrox-io
      name: scanner-v4
      tag: latest
    # Vulnerability bundle URL
    # Default: Use ci-minimal bundle from GitHub for fast CI testing
    # Nightlies use values-full.yaml to retain the versioned production bundle default.
    vulnerabilitiesUrl: "https://raw.githubusercontent.com/stackrox/stackrox/5ad57fb2849616a8db4878c5647a280ac822b5f5/scanner/image/scanner/bundles/ci-minimal/vulnerabilities.zip"
  db:
    name: scanner-v4-db
    image:
      registry: quay.io/stackrox-io
      name: scanner-v4-db
      tag: latest
    persistence:
      hostPath: null
