#!/bin/sh
set -eu

user_name='roxbot'
user_email='roxbot@stackrox.com'
local_subdirectory="${1}"
remote_repository="git@github.com:stackrox/helm-charts"

main() {
    echo "Pushing directory ${local_subdirectory} to repo ${remote_repository}"

    tmp_remote_repository="$(mktemp -d)"
    cd "$tmp_remote_repository"

    git clone "$remote_repository" .  # mind the .!
    cp -r "$local_subdirectory" "$tmp_remote_repository"
    git add -A
    git -c "user.name=${user_name}" -c "user.email=${user_email}" commit -m "Update repository"
    git push origin master
}

main "$@"
