name: Cache QA Tests Dependencies
description: Cache QA Tests Dependencies
runs:
  using: composite
  steps:
    - name: Cache Gradle Dependencies
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # ratchet:actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.m2/repository
        key: gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-v2-
