apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-controller
  namespace: stackrox
  labels:
    app: config-controller
    app.kubernetes.io/component: config-controller
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
    app.kubernetes.io/version: 4.10.1
    helm.sh/chart: stackrox-central-services-400.10.1
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-central-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: config-controller
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: stackrox
      labels:
        app: config-controller
        app.kubernetes.io/component: config-controller
        app.kubernetes.io/instance: stackrox-central-services
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: stackrox
        app.kubernetes.io/part-of: stackrox-central-services
        app.kubernetes.io/version: 4.10.1
        helm.sh/chart: stackrox-central-services-400.10.1
      annotations:
        email: support@stackrox.com
        meta.helm.sh/release-name: stackrox-central-services
        meta.helm.sh/release-namespace: stackrox
        owner: stackrox
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: NotIn
                values:
                - "true"
            weight: 100
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 50
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/compute
                operator: Exists
            weight: 25
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
            weight: 100
      serviceAccountName: config-controller
      securityContext:
        fsGroup: 4000
        runAsUser: 4000
      
      containers:
      - name: manager
        image: "registry.redhat.io/advanced-cluster-security/rhacs-main-rhel8:4.10.1"
        command:
          - /stackrox/config-controller
        args:
          - --health-probe-bind-address=:8081
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROX_CENTRAL_ENDPOINT
          value: central.stackrox.svc:443
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 50
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /run/secrets/stackrox.io/certs/
          name: central-certs-volume
          readOnly: true
        - name: additional-ca-volume
          mountPath: /usr/local/share/ca-certificates/
          readOnly: true
        - name: etc-ssl-volume
          mountPath: /etc/ssl
        - name: etc-pki-volume
          mountPath: /etc/pki/ca-trust
      terminationGracePeriodSeconds: 10
      volumes:
      - name: central-certs-volume
        secret:
          defaultMode: 420
          items:
          - key: ca.pem
            path: ca.pem
          secretName: central-tls
      - name: additional-ca-volume
        secret:
          secretName: additional-ca
          optional: true
      - name: etc-ssl-volume
        emptyDir: {}
      - name: etc-pki-volume
        emptyDir: {}
