// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/stackrox/stackrox/generated/storage"
	"github.com/stackrox/stackrox/pkg/features"
	"github.com/stackrox/stackrox/pkg/postgres/pgtest"
	"github.com/stackrox/stackrox/pkg/sac"
	"github.com/stackrox/stackrox/pkg/testutils"
	"github.com/stackrox/stackrox/pkg/testutils/envisolator"
	"github.com/stretchr/testify/suite"
)

type SensorUpgradeConfigsStoreSuite struct {
	suite.Suite
	envIsolator *envisolator.EnvIsolator
	store       Store
	pool        *pgxpool.Pool
}

func TestSensorUpgradeConfigsStore(t *testing.T) {
	suite.Run(t, new(SensorUpgradeConfigsStoreSuite))
}

func (s *SensorUpgradeConfigsStoreSuite) SetupTest() {
	s.envIsolator = envisolator.NewEnvIsolator(s.T())
	s.envIsolator.Setenv(features.PostgresDatastore.EnvVar(), "true")

	if !features.PostgresDatastore.Enabled() {
		s.T().Skip("Skip postgres store tests")
		s.T().SkipNow()
	}

	ctx := sac.WithAllAccess(context.Background())

	source := pgtest.GetConnectionString(s.T())
	config, err := pgxpool.ParseConfig(source)
	s.Require().NoError(err)
	pool, err := pgxpool.ConnectConfig(ctx, config)
	s.Require().NoError(err)

	Destroy(ctx, pool)

	s.pool = pool
	s.store = New(ctx, pool)
}

func (s *SensorUpgradeConfigsStoreSuite) TearDownTest() {
	if s.pool != nil {
		s.pool.Close()
	}
	s.envIsolator.RestoreAll()
}

func (s *SensorUpgradeConfigsStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	store := s.store

	sensorUpgradeConfig := &storage.SensorUpgradeConfig{}
	s.NoError(testutils.FullInit(sensorUpgradeConfig, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundSensorUpgradeConfig, exists, err := store.Get(ctx)
	s.NoError(err)
	s.False(exists)
	s.Nil(foundSensorUpgradeConfig)

	withNoAccessCtx := sac.WithNoAccess(ctx)

	s.NoError(store.Upsert(ctx, sensorUpgradeConfig))
	foundSensorUpgradeConfig, exists, err = store.Get(ctx)
	s.NoError(err)
	s.True(exists)
	s.Equal(sensorUpgradeConfig, foundSensorUpgradeConfig)

	foundSensorUpgradeConfig, exists, err = store.Get(ctx)
	s.NoError(err)
	s.True(exists)
	s.Equal(sensorUpgradeConfig, foundSensorUpgradeConfig)

	s.NoError(store.Delete(ctx))
	foundSensorUpgradeConfig, exists, err = store.Get(ctx)
	s.NoError(err)
	s.False(exists)
	s.Nil(foundSensorUpgradeConfig)

	s.ErrorIs(store.Delete(withNoAccessCtx), sac.ErrResourceAccessDenied)

	sensorUpgradeConfig = &storage.SensorUpgradeConfig{}
	s.NoError(testutils.FullInit(sensorUpgradeConfig, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))
	s.NoError(store.Upsert(ctx, sensorUpgradeConfig))

	foundSensorUpgradeConfig, exists, err = store.Get(ctx)
	s.NoError(err)
	s.True(exists)
	s.Equal(sensorUpgradeConfig, foundSensorUpgradeConfig)

	sensorUpgradeConfig = &storage.SensorUpgradeConfig{}
	s.NoError(testutils.FullInit(sensorUpgradeConfig, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))
	s.NoError(store.Upsert(ctx, sensorUpgradeConfig))

	foundSensorUpgradeConfig, exists, err = store.Get(ctx)
	s.NoError(err)
	s.True(exists)
	s.Equal(sensorUpgradeConfig, foundSensorUpgradeConfig)
}
