// Code generated by genny. DO NOT EDIT.
// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package fixtures

import (
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/sac/testconsts"
	"github.com/stackrox/rox/pkg/uuid"
)

// *storage.K8SRoleBinding represents a generic type that we use in the function below.

// GetSACTestStorageK8SRoleBindingSet returns a set of mock *storage.K8SRoleBinding that can be used
// for scoped access control sets.
// It will include:
// 9 *storage.K8SRoleBinding scoped to Cluster1, 3 to each Namespace A / B / C.
// 9 *storage.K8SRoleBinding scoped to Cluster2, 3 to each Namespace A / B / C.
// 9 *storage.K8SRoleBinding scoped to Cluster3, 3 to each Namespace A / B / C.
func GetSACTestStorageK8SRoleBindingSet(scopedStorageK8SRoleBindingCreator func(id string, clusterID string, namespace string) *storage.K8SRoleBinding) []*storage.K8SRoleBinding {
	clusters := []string{testconsts.Cluster1, testconsts.Cluster2, testconsts.Cluster3}
	namespaces := []string{testconsts.NamespaceA, testconsts.NamespaceB, testconsts.NamespaceC}
	const numberOfAccounts = 3
	storageK8SRoleBindings := make([]*storage.K8SRoleBinding, 0, len(clusters)*len(namespaces)*numberOfAccounts)
	for _, cluster := range clusters {
		for _, namespace := range namespaces {
			for i := 0; i < numberOfAccounts; i++ {
				storageK8SRoleBindings = append(storageK8SRoleBindings, scopedStorageK8SRoleBindingCreator(uuid.NewV4().String(), cluster, namespace))
			}
		}
	}
	return storageK8SRoleBindings
}
