proto_library(
    name = "v1",
    # srcs = glob(["*.proto"]),
    srcs = [],
    visibility = ["//visibility:public"],
    deps = [
        "@googleapi//:annotations_proto",
        "@com_google_protobuf//:descriptor_proto",
        "@com_google_protobuf//:timestamp_proto",
    ]
)
