// Code generated by pg-bindings generator. DO NOT EDIT.
package schema

import (
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/protocompat"
)

// ConvertProcessIndicatorFromProto converts a `*storage.ProcessIndicator` to Gorm model
func ConvertProcessIndicatorFromProto(obj *storage.ProcessIndicator) (*ProcessIndicators, error) {
	serialized, err := obj.MarshalVT()
	if err != nil {
		return nil, err
	}
	model := &ProcessIndicators{
		ID:                 obj.GetId(),
		DeploymentID:       obj.GetDeploymentId(),
		ContainerName:      obj.GetContainerName(),
		PodID:              obj.GetPodId(),
		PodUID:             obj.GetPodUid(),
		SignalContainerID:  obj.GetSignal().GetContainerId(),
		SignalTime:         protocompat.NilOrTime(obj.GetSignal().GetTime()),
		SignalName:         obj.GetSignal().GetName(),
		SignalArgs:         obj.GetSignal().GetArgs(),
		SignalExecFilePath: obj.GetSignal().GetExecFilePath(),
		SignalUID:          obj.GetSignal().GetUid(),
		ClusterID:          obj.GetClusterId(),
		Namespace:          obj.GetNamespace(),
		ContainerStartTime: protocompat.NilOrTime(obj.GetContainerStartTime()),
		Serialized:         serialized,
	}
	return model, nil
}

// ConvertProcessIndicatorToProto converts Gorm model `ProcessIndicators` to its protobuf type object
func ConvertProcessIndicatorToProto(m *ProcessIndicators) (*storage.ProcessIndicator, error) {
	var msg storage.ProcessIndicator
	if err := msg.UnmarshalVTUnsafe(m.Serialized); err != nil {
		return nil, err
	}
	return &msg, nil
}
