apiVersion: v1
kind: Service
metadata:
  name: scanner-v4-db
  namespace: stackrox
  labels:
    app.kubernetes.io/component: scanner-v4
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
    app.kubernetes.io/version: 4.10.1
    helm.sh/chart: stackrox-central-services-400.10.1
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-central-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
spec:
  type: ClusterIP
  ports:
  - name: tcp-db
    port: 5432
    targetPort: 5432
  selector:
    app: scanner-v4-db
