// Code generated by pg-bindings generator. DO NOT EDIT.
package n33ton34

import (
	"context"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/pkg/errors"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/migrator/migrations"
	"github.com/stackrox/rox/migrator/migrations/loghelper"
	legacy "github.com/stackrox/rox/migrator/migrations/n_33_to_n_34_postgres_networkpolicyapplicationundorecords/legacy"
	pgStore "github.com/stackrox/rox/migrator/migrations/n_33_to_n_34_postgres_networkpolicyapplicationundorecords/postgres"
	"github.com/stackrox/rox/migrator/types"
	pkgMigrations "github.com/stackrox/rox/pkg/migrations"
	pkgSchema "github.com/stackrox/rox/pkg/postgres/schema"
	"github.com/stackrox/rox/pkg/sac"
	bolt "go.etcd.io/bbolt"
	"gorm.io/gorm"
)

var (
	migration = types.Migration{
		StartingSeqNum: pkgMigrations.CurrentDBVersionSeqNum() + 33,
		VersionAfter:   storage.Version{SeqNum: int32(pkgMigrations.CurrentDBVersionSeqNum()) + 34},
		Run: func(databases *types.Databases) error {
			legacyStore := legacy.New(databases.BoltDB)
			if err := move(databases.BoltDB, databases.GormDB, databases.PostgresDB, legacyStore); err != nil {
				return errors.Wrap(err,
					"moving networkpolicyapplicationundorecords from rocksdb to postgres")
			}
			return nil
		},
	}
	batchSize = 10000
	schema    = pkgSchema.NetworkpolicyapplicationundorecordsSchema
	log       = loghelper.LogWrapper{}
)

func move(legacyDB *bolt.DB, gormDB *gorm.DB, postgresDB *pgxpool.Pool, legacyStore legacy.Store) error {
	ctx := sac.WithAllAccess(context.Background())
	store := pgStore.New(postgresDB)
	pkgSchema.ApplySchemaForTable(context.Background(), gormDB, schema.Table)
	var networkpolicyapplicationundorecords []*storage.NetworkPolicyApplicationUndoRecord
	var err error
	legacyStore.Walk(ctx, func(obj *storage.NetworkPolicyApplicationUndoRecord) error {
		networkpolicyapplicationundorecords = append(networkpolicyapplicationundorecords, obj)
		if len(networkpolicyapplicationundorecords) == 10*batchSize {
			if err := store.UpsertMany(ctx, networkpolicyapplicationundorecords); err != nil {
				log.WriteToStderrf("failed to persist networkpolicyapplicationundorecords to store %v", err)
				return err
			}
			networkpolicyapplicationundorecords = networkpolicyapplicationundorecords[:0]
		}
		return nil
	})
	if len(networkpolicyapplicationundorecords) > 0 {
		if err = store.UpsertMany(ctx, networkpolicyapplicationundorecords); err != nil {
			log.WriteToStderrf("failed to persist networkpolicyapplicationundorecords to store %v", err)
			return err
		}
	}
	return nil
}

func init() {
	migrations.MustRegisterMigration(migration)
}
