import {
    lifecycleStageLabels,
    portExposureLabels,
    envVarSrcLabels,
    rbacPermissionLabels,
    policyCriteriaCategories,
    mountPropagationLabels,
    seccompProfileTypeLabels,
    severityRatings,
} from 'messages/common';
import { resourceTypes } from 'constants/entityTypes';
import { knownBackendFlags, isBackendFeatureFlagEnabled } from 'utils/featureFlags';
import { clientOnlyExclusionFieldNames } from './whitelistFieldNames';

const equalityOptions = [
    { label: 'Is greater than', value: '>' },
    {
        label: 'Is greater than or equal to',
        value: '>=',
    },
    { label: 'Is equal to', value: '=' },
    {
        label: 'Is less than or equal to',
        value: '<=',
    },
    { label: 'Is less than', value: '<' },
];

const cpuResource = (label) => ({
    label,
    name: label,
    category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
    type: 'group',
    subComponents: [
        {
            type: 'select',
            options: equalityOptions,
            subpath: 'key',
        },
        {
            type: 'number',
            placeholder: '# of cores',
            min: 0,
            step: 0.1,
            subpath: 'value',
        },
    ],
    required: false,
    canBooleanLogic: true,
    entityType: resourceTypes.DEPLOYMENT,
});

const capabilities = [
    'AUDIT_CONTROL',
    'AUDIT_READ',
    'AUDIT_WRITE',
    'BLOCK_SUSPEND',
    'CHOWN',
    'DAC_OVERRIDE',
    'DAC_READ_SEARCH',
    'FOWNER',
    'FSETID',
    'IPC_LOCK',
    'IPC_OWNER',
    'KILL',
    'LEASE',
    'LINUX_IMMUTABLE',
    'MAC_ADMIN',
    'MAC_OVERRIDE',
    'MKNOD',
    'NET_ADMIN',
    'NET_BIND_SERVICE',
    'NET_BROADCAST',
    'NET_RAW',
    'SETGID',
    'SETFCAP',
    'SETPCAP',
    'SETUID',
    'SYS_ADMIN',
    'SYS_BOOT',
    'SYS_CHROOT',
    'SYS_MODULE',
    'SYS_NICE',
    'SYS_PACCT',
    'SYS_PTRACE',
    'SYS_RAWIO',
    'SYS_RESOURCE',
    'SYS_TIME',
    'SYS_TTY_CONFIG',
    'SYSLOG',
    'WAKE_ALARM',
].map((cap) => ({ label: cap, value: cap }));

const memoryResource = (label) => ({
    label,
    name: label,
    category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
    type: 'group',
    subComponents: [
        {
            type: 'select',
            options: equalityOptions,
            subpath: 'key',
        },
        {
            type: 'number',
            placeholder: '# MB',
            min: 0,
            subpath: 'value',
        },
    ],
    required: false,
    canBooleanLogic: true,
    entityType: resourceTypes.DEPLOYMENT,
});

// A descriptor for every option on the policy creation page.

const policyDetailsFormDescriptor = [
    {
        label: 'Name',
        hideInnerLabel: true,
        jsonpath: 'name',
        type: 'text',
        required: true,
    },
    {
        label: 'Severity',
        hideInnerLabel: true,
        jsonpath: 'severity',
        type: 'select',
        options: [
            { label: 'Critical', value: 'CRITICAL_SEVERITY' },
            { label: 'High', value: 'HIGH_SEVERITY' },
            { label: 'Medium', value: 'MEDIUM_SEVERITY' },
            { label: 'Low', value: 'LOW_SEVERITY' },
        ],
        placeholder: 'Select a severity level',
        required: true,
    },
    {
        label: 'Lifecycle Stages',
        jsonpath: 'lifecycleStages',
        type: 'multiselect',
        options: Object.keys(lifecycleStageLabels).map((key) => ({
            label: lifecycleStageLabels[key],
            value: key,
        })),
        required: true,
    },
    {
        label: 'Event Sources',
        hideInnerLabel: true,
        jsonpath: 'eventSource',
        type: 'select',
        options: [
            {
                label: 'Deployment',
                value: 'DEPLOYMENT',
            },
            { label: 'Audit Log', value: 'AUDIT_LOG' },
        ],
        featureFlag: knownBackendFlags.ROX_K8S_AUDIT_LOG_DETECTION,
    },
    {
        label: 'Description',
        jsonpath: 'description',
        type: 'textarea',
        placeholder: 'What does this policy do?',
        required: false,
    },
    {
        label: 'Rationale',
        jsonpath: 'rationale',
        type: 'textarea',
        placeholder: 'Why does this policy exist?',
        required: false,
    },
    {
        label: 'Remediation',
        jsonpath: 'remediation',
        type: 'textarea',
        placeholder: 'What can an operator do to resolve any violations?',
        required: false,
    },
    {
        label: 'Categories',
        jsonpath: 'categories',
        type: 'multiselect-creatable',
        options: [],
        required: true,
        default: true,
    },
    {
        label: 'Notifications',
        jsonpath: 'notifiers',
        type: 'multiselect',
        options: [],
        required: false,
    },
    {
        label: 'Restrict to Scope',
        jsonpath: 'scope',
        type: 'scope',
        options: [],
        required: false,
    },
    {
        label: 'Exclude by Scope',
        jsonpath: clientOnlyExclusionFieldNames.EXCLUDED_DEPLOYMENT_SCOPES,
        type: 'whitelistScope',
        options: [],
        required: false,
    },
    {
        label: 'Excluded Images (Build Lifecycle only)',
        jsonpath: clientOnlyExclusionFieldNames.EXCLUDED_IMAGE_NAMES,
        type: 'multiselect-creatable',
        options: [],
        required: false,
    },
];

const policyConfigurationDescriptor = [
    {
        label: 'Image Registry',
        name: 'Image Registry',
        longName: 'Image pulled from registry',
        negatedName: 'Image not pulled from registry',
        category: policyCriteriaCategories.IMAGE_REGISTRY,
        type: 'text',
        placeholder: 'docker.io',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Image Remote',
        name: 'Image Remote',
        longName: 'Image name in the registry',
        negatedName: `Image name in the registry doesn't match`,
        category: policyCriteriaCategories.IMAGE_REGISTRY,
        type: 'text',
        placeholder: 'library/nginx',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Image Tag',
        name: 'Image Tag',
        negatedName: `Image tag doesn't match`,
        category: policyCriteriaCategories.IMAGE_REGISTRY,
        type: 'text',
        placeholder: 'latest',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Days since image was created',
        name: 'Image Age',
        longName: 'Minimum days since image was built',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'number',
        placeholder: '1',
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Days since image was last scanned',
        name: 'Image Scan Age',
        longName: 'Minimum days since last image scan',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'number',
        placeholder: '1',
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Image User',
        name: 'Image User',
        negatedName: `Image user is not`,
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'text',
        placeholder: '0',
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Dockerfile Line',
        name: 'Dockerfile Line',
        longName: 'Disallowed Dockerfile line',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        subComponents: [
            {
                type: 'select',
                options: [
                    { label: 'FROM', value: 'FROM' },
                    { label: 'LABEL', value: 'LABEL' },
                    { label: 'RUN', value: 'RUN' },
                    { label: 'CMD', value: 'CMD' },
                    { label: 'EXPOSE', value: 'EXPOSE' },
                    { label: 'ENV', value: 'ENV' },
                    { label: 'ADD', value: 'ADD' },
                    { label: 'COPY', value: 'COPY' },
                    { label: 'ENTRYPOINT', value: 'ENTRYPOINT' },
                    { label: 'VOLUME', value: 'VOLUME' },
                    { label: 'USER', value: 'USER' },
                    { label: 'WORKDIR', value: 'WORKDIR' },
                    { label: 'ONBUILD', value: 'ONBUILD' },
                ],
                label: 'Instruction',
                subpath: 'key',
            },
            {
                name: 'value',
                type: 'text',
                label: 'Arguments',
                placeholder: 'Any',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Image is NOT Scanned',
        name: 'Unscanned Image',
        longName: 'Image Scan Status',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Scanned',
                value: false,
            },
            {
                text: 'Not scanned',
                value: true,
            },
        ],
        required: false,
        defaultValue: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'CVSS',
        name: 'CVSS',
        longName: 'Common Vulnerability Scoring System (CVSS) Score',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        subComponents: [
            {
                type: 'select',
                options: equalityOptions,
                subpath: 'key',
            },
            {
                type: 'number',
                placeholder: '0-10',
                max: 10,
                min: 0,
                step: 0.1,
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Severity',
        name: 'Severity',
        longName: 'Vulnerability Severity Rating',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        jsonpaths: [
            {
                type: 'select',
                options: equalityOptions,
                subpath: 'key',
            },
            {
                type: 'select',
                options: Object.keys(severityRatings).map((key) => ({
                    label: severityRatings[key],
                    value: key,
                })),
                subpath: 'value',
            },
        ],
        required: false,
        default: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Fixed By',
        name: 'Fixed By',
        longName: 'Version in which vulnerability is fixed',
        negatedName: `Version in which vulnerability is fixed doesn't match`,
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'text',
        placeholder: '.*',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.NODE,
    },
    {
        label: 'CVE',
        name: 'CVE',
        longName: 'Common Vulnerabilities and Exposures (CVE) identifier',
        negatedName: `Common Vulnerabilities and Exposures (CVE) identifier doesn't match`,
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'text',
        placeholder: 'CVE-2017-11882',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.NODE,
    },
    {
        label: 'Image Component',
        name: 'Image Component',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Component Name',
                placeholder: 'example',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Version',
                placeholder: 'Any',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Image OS',
        name: 'Image OS',
        longName: 'Image Operating System',
        negatedName: `Image Operating System doesn't match`,
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'text',
        placeholder: 'ubuntu:19.04',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Environment Variable',
        name: 'Environment Variable',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'Any',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: 'Any',
                subpath: 'value',
            },
            {
                type: 'select',
                options: Object.keys(envVarSrcLabels).map((key) => ({
                    label: envVarSrcLabels[key],
                    value: key,
                })),
                label: 'Value From',
                placeholder: 'Select one',
                subpath: 'source',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Disallowed Annotation',
        name: 'Disallowed Annotation',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'Any',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: 'Any',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Required Label',
        name: 'Required Label',
        longName: 'Required Deployment Label',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'owner',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: '.*',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Required Annotation',
        name: 'Required Annotation',
        longName: 'Required Deployment Annotation',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'owner',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: '.*',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Volume Name',
        name: 'Volume Name',
        negatedName: `Volume name doesn't match`,
        category: policyCriteriaCategories.STORAGE,
        type: 'text',
        placeholder: 'docker-socket',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Volume Source',
        name: 'Volume Source',
        negatedName: `Volume source doesn't match`,
        category: policyCriteriaCategories.STORAGE,
        type: 'text',
        placeholder: '/var/run/docker.sock',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Volume Destination',
        name: 'Volume Destination',
        negatedName: `Volume destination doesn't match`,
        category: policyCriteriaCategories.STORAGE,
        type: 'text',
        placeholder: '/var/run/docker.sock',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Volume Type',
        name: 'Volume Type',
        negatedName: `Volume type doesn't match`,
        category: policyCriteriaCategories.STORAGE,
        type: 'text',
        placeholder: 'bind, secret',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Writable Mounted Volume',
        name: 'Writable Mounted Volume',
        longName: 'Mounted Volume Writability',
        category: policyCriteriaCategories.STORAGE,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Writable',
                value: true,
            },
            {
                text: 'Read-only',
                value: false,
            },
        ],
        required: false,
        defaultValue: false,
        reverse: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Mount Propagation',
        name: 'Mount Propagation',
        negatedName: 'Mount Propagation is not',
        category: policyCriteriaCategories.STORAGE,
        type: 'multiselect',
        options: Object.keys(mountPropagationLabels).map((key) => ({
            label: mountPropagationLabels[key],
            value: key,
        })),
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Protocol',
        name: 'Exposed Port Protocol',
        negatedName: `Exposed Port Protocol doesn't match`,
        category: policyCriteriaCategories.NETWORKING,
        type: 'text',
        placeholder: 'tcp',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Exposed Node Port',
        name: 'Exposed Node Port',
        negatedName: `Exposed node port doesn't match`,
        category: policyCriteriaCategories.NETWORKING,
        type: 'number',
        placeholder: '22',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Port',
        name: 'Exposed Port',
        negatedName: `Exposed port doesn't match`,
        category: policyCriteriaCategories.NETWORKING,
        type: 'number',
        placeholder: '22',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    cpuResource('Container CPU Request'),
    cpuResource('Container CPU Limit'),
    memoryResource('Container Memory Request'),
    memoryResource('Container Memory Limit'),
    {
        label: 'Privileged',
        name: 'Privileged Container',
        longName: 'Privileged Container Status',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Privileged Container',
                value: true,
            },
            {
                text: 'Not a Privileged Container',
                value: false,
            },
        ],
        required: false,
        defaultValue: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Read-Only Root Filesystem',
        name: 'Read-Only Root Filesystem',
        longName: 'Root Filesystem Writability',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Read-Only',
                value: true,
            },
            {
                text: 'Writable',
                value: false,
            },
        ],
        required: false,
        defaultValue: false,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Seccomp Profile Type',
        name: 'Seccomp Profile Type',
        negatedName: 'Seccomp Profile Type is not',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'radioGroup',
        radioButtons: Object.keys(seccompProfileTypeLabels).map((key) => ({
            text: seccompProfileTypeLabels[key],
            value: key,
        })),
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Share Host Network Namespace',
        name: 'Host Network',
        longName: 'Host Network',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Uses Host Network Namespace',
                value: true,
            },
            {
                text: 'Does Not Use Host Network Namespace',
                value: false,
            },
        ],
        required: false,
        defaultValue: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Share Host PID Namespace',
        name: 'Host PID',
        longName: 'Host PID',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Uses Host PID namespace',
                value: true,
            },
            {
                text: 'Does Not Use Host PID namespace',
                value: false,
            },
        ],
        required: false,
        defaultValue: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Share Host IPC Namespace',
        name: 'Host IPC',
        longName: 'Host IPC',
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Uses Host IPC namespace',
                value: true,
            },
            {
                text: 'Does Not Use Host IPC namespace',
                value: false,
            },
        ],
        required: false,
        defaultValue: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Drop Capabilities',
        name: 'Drop Capabilities',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'select',
        options: [...capabilities],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Add Capabilities',
        name: 'Add Capabilities',
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'select',
        options: [...capabilities],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Process Name',
        name: 'Process Name',
        negatedName: `Process name doesn't match`,
        category: policyCriteriaCategories.PROCESS_ACTIVITY,
        type: 'text',
        placeholder: 'apt-get',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Process Ancestor',
        name: 'Process Ancestor',
        negatedName: `Process ancestor doesn't match`,
        category: policyCriteriaCategories.PROCESS_ACTIVITY,
        type: 'text',
        placeholder: 'java',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Process Args',
        name: 'Process Arguments',
        negatedName: `Process arguments don't match`,
        category: policyCriteriaCategories.PROCESS_ACTIVITY,
        type: 'text',
        placeholder: 'install nmap',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Process UID',
        name: 'Process UID',
        negatedName: `Process UID doesn't match`,
        category: policyCriteriaCategories.PROCESS_ACTIVITY,
        type: 'text',
        placeholder: '0',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Port Exposure',
        name: 'Port Exposure Method',
        negatedName: 'Port Exposure Method is not',
        category: policyCriteriaCategories.NETWORKING,
        type: 'select',
        options: Object.keys(portExposureLabels)
            .filter((key) => key !== 'INTERNAL')
            .map((key) => ({
                label: portExposureLabels[key],
                value: key,
            })),
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Writable Host Mount',
        name: 'Writable Host Mount',
        longName: 'Host Mount Writability',
        category: policyCriteriaCategories.STORAGE,
        type: 'radioGroup',
        radioButtons: [
            {
                text: 'Writable',
                value: true,
            },
            {
                text: 'Read-only',
                value: false,
            },
        ],
        required: false,
        defaultValue: false,
        reverse: true,
        disabled: true,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Process Baselining Enabled',
        name: 'Unexpected Process Executed',
        longName: 'Process Baselining Status',
        category: policyCriteriaCategories.PROCESS_ACTIVITY,
        type: 'radioGroup',
        radioButtons: [
            { text: 'Unexpected Process', value: true },
            { text: 'Expected Process', value: false },
        ],
        required: false,
        defaultValue: false,
        reverse: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Service Account',
        name: 'Service Account',
        longName: 'Service Account Name',
        negatedName: `Service Account Name doesn't match`,
        category: policyCriteriaCategories.KUBERNETES_ACCESS,
        type: 'text',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Minimum RBAC Permissions',
        name: 'Minimum RBAC Permissions',
        longName: 'RBAC permission level is at least',
        negatedName: 'RBAC permission level is less than',
        category: policyCriteriaCategories.KUBERNETES_ACCESS,
        type: 'select',
        options: Object.keys(rbacPermissionLabels).map((key) => ({
            label: rbacPermissionLabels[key],
            value: key,
        })),
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Required Image Label',
        name: 'Required Image Label',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'requiredLabelKey.*',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: 'requiredValue.*',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Disallowed Image Label',
        name: 'Disallowed Image Label',
        category: policyCriteriaCategories.IMAGE_CONTENTS,
        type: 'group',
        subComponents: [
            {
                type: 'text',
                label: 'Key',
                placeholder: 'disallowedLabelKey.*',
                subpath: 'key',
            },
            {
                type: 'text',
                label: 'Value',
                placeholder: 'disallowedValue.*',
                subpath: 'value',
            },
        ],
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Namespace',
        name: 'Namespace',
        longName: 'Namespace',
        negatedName: `Namespace doesn't match`,
        category: policyCriteriaCategories.DEPLOYMENT_METADATA,
        type: 'text',
        placeholder: 'default',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Container Name',
        name: 'Container Name',
        longName: 'Container Name',
        negatedName: `Container name doesn't match`,
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'text',
        placeholder: 'default',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'AppArmor Profile',
        name: 'AppArmor Profile',
        longName: 'AppArmor Profile',
        negatedName: `AppArmor Profile doesn't match`,
        category: policyCriteriaCategories.CONTAINER_CONFIGURATION,
        type: 'text',
        placeholder: 'default',
        required: false,
        canBooleanLogic: true,
        entityType: resourceTypes.DEPLOYMENT,
    },
    {
        label: 'Kubernetes Action',
        name: 'Kubernetes Resource',
        longName: 'Kubernetes Action',
        shortName: 'Kubernetes Action',
        category: policyCriteriaCategories.KUBERNETES_EVENTS,
        type: 'select',
        options: [
            {
                label: 'Pod Exec',
                value: 'PODS_EXEC',
            },
            {
                label: 'Pods Port Forward',
                value: 'PODS_PORTFORWARD',
            },
        ],
        required: false,
        canBooleanLogic: false,
        entityType: resourceTypes.CLUSTER,
    },
];

const networkDetectionDescriptor = [
    {
        label: 'Network Baselining Enabled',
        name: 'Unexpected Network Flow Detected',
        longName: 'Network Baselining Status',
        category: policyCriteriaCategories.NETWORKING,
        type: 'radioGroup',
        radioButtons: [
            { text: 'Unexpected Network Flow', value: true },
            { text: 'Expected Network Flow', value: false },
        ],
        required: false,
        defaultValue: false,
        reverse: false,
        canBooleanLogic: false,
        entityType: resourceTypes.DEPLOYMENT,
    },
];

export const policyDetails = {
    header: 'Policy Summary',
    descriptor: policyDetailsFormDescriptor,
    dataTestId: 'policyDetailsFields',
};

export const policyConfiguration = {
    header: 'Policy Criteria',
    descriptor: policyConfigurationDescriptor,
    dataTestId: 'policyConfigurationFields',
};

let isFirstLoad = true;

export const getPolicyDetails = (featureFlags) => {
    const newPolicyDetails = { ...policyDetails };
    // these feature flags are structured differently than the ones in getPolicyConfiguration
    // because this is data directly from the featureflags endpoint
    if (!isBackendFeatureFlagEnabled(featureFlags, knownBackendFlags.ROX_K8S_AUDIT_LOG_DETECTION)) {
        newPolicyDetails.descriptor = policyDetails.descriptor.filter((field) => {
            return field.featureFlag !== knownBackendFlags.ROX_K8S_AUDIT_LOG_DETECTION;
        });
    }
    return newPolicyDetails;
};

export const getPolicyConfiguration = (featureFlags) => {
    const newPolicyConfiguration = { ...policyConfiguration };
    if (featureFlags[knownBackendFlags.ROX_NETWORK_DETECTION_BASELINE_VIOLATION] && isFirstLoad) {
        newPolicyConfiguration.descriptor.push(...networkDetectionDescriptor);
    }
    isFirstLoad = false;
    return newPolicyConfiguration;
};
