// Code generated by pg-bindings generator. DO NOT EDIT.
package internal

import (
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/search"
)

var (
	// TestParent3SearchFields contains pre-computed search fields for test_parent3
	TestParent3SearchFields = map[search.FieldLabel]*search.Field{}

	// TestParent3Schema is the pre-computed schema for test_parent3 table
	TestParent3Schema = &walker.Schema{
		Table:    "test_parent3",
		Type:     "*storage.TestParent3",
		TypeName: "TestParent3",
		Fields: []walker.Field{
			{
				Name:       "Id",
				ColumnName: "Id",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
				Options: walker.PostgresOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:       "ParentId",
				ColumnName: "ParentId",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
			},
			{
				Name:       "Val",
				ColumnName: "Val",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
			},
			{
				Name:       "serialized",
				ColumnName: "serialized",
				Type:       "[]byte",
				SQLType:    "bytea",
			},
		},
	}
)

// GetTestParent3Schema returns the generated schema for test_parent3
func GetTestParent3Schema() *walker.Schema {
	// Set up search options if not already done
	if TestParent3Schema.OptionsMap == nil {
		TestParent3Schema.SetOptionsMap(search.OptionsMapFromMap(v1.SearchCategory(112), TestParent3SearchFields))
	}
	// Set Schema back-reference on all fields
	for i := range TestParent3Schema.Fields {
		TestParent3Schema.Fields[i].Schema = TestParent3Schema
	}
	// Set Schema back-reference on all child schema fields
	var setChildSchemaReferences func(*walker.Schema)
	setChildSchemaReferences = func(schema *walker.Schema) {
		for _, child := range schema.Children {
			for i := range child.Fields {
				child.Fields[i].Schema = child
			}
			setChildSchemaReferences(child)
		}
	}
	setChildSchemaReferences(TestParent3Schema)
	return TestParent3Schema
}
