// Code generated by pg-bindings generator. DO NOT EDIT.
package internal

import (
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/search"
)

var (
	// TestGGrandChild1SearchFields contains pre-computed search fields for test_g_grand_child1
	TestGGrandChild1SearchFields = map[search.FieldLabel]*search.Field{}

	// TestGGrandChild1Schema is the pre-computed schema for test_g_grand_child1 table
	TestGGrandChild1Schema = &walker.Schema{
		Table:    "test_g_grand_child1",
		Type:     "*storage.TestGGrandChild1",
		TypeName: "TestGGrandChild1",
		Fields: []walker.Field{
			{
				Name:       "Id",
				ColumnName: "Id",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
				Options: walker.PostgresOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:       "Val",
				ColumnName: "Val",
				Type:       "string",
				SQLType:    "varchar",
				DataType:   postgres.String,
			},
			{
				Name:       "serialized",
				ColumnName: "serialized",
				Type:       "[]byte",
				SQLType:    "bytea",
			},
		},
	}
)

// GetTestGGrandChild1Schema returns the generated schema for test_g_grand_child1
func GetTestGGrandChild1Schema() *walker.Schema {
	// Set up search options if not already done
	if TestGGrandChild1Schema.OptionsMap == nil {
		TestGGrandChild1Schema.SetOptionsMap(search.OptionsMapFromMap(v1.SearchCategory(107), TestGGrandChild1SearchFields))
	}
	// Set Schema back-reference on all fields
	for i := range TestGGrandChild1Schema.Fields {
		TestGGrandChild1Schema.Fields[i].Schema = TestGGrandChild1Schema
	}
	// Set Schema back-reference on all child schema fields
	var setChildSchemaReferences func(*walker.Schema)
	setChildSchemaReferences = func(schema *walker.Schema) {
		for _, child := range schema.Children {
			for i := range child.Fields {
				child.Fields[i].Schema = child
			}
			setChildSchemaReferences(child)
		}
	}
	setChildSchemaReferences(TestGGrandChild1Schema)
	return TestGGrandChild1Schema
}
