package runner

import (
	// Import these packages to trigger the registration.
	_ "github.com/stackrox/rox/migrator/migrations/m_0_to_m_1_create_version_bucket"
	_ "github.com/stackrox/rox/migrator/migrations/m_10_to_11_processwhitelist_cluster_namespace"
	_ "github.com/stackrox/rox/migrator/migrations/m_11_to_m_12_rewrite_alerts_and_deployments"
	_ "github.com/stackrox/rox/migrator/migrations/m_12_to_m_13_default_retention_duration"
	_ "github.com/stackrox/rox/migrator/migrations/m_13_to_m_14_flow_fixes_and_pruning"
	_ "github.com/stackrox/rox/migrator/migrations/m_14_to_m_15_purge_debugmetrics"
	_ "github.com/stackrox/rox/migrator/migrations/m_15_m_16_delete_orphaned_list_alerts"
	_ "github.com/stackrox/rox/migrator/migrations/m_16_to_m_17_add_scan_stats"
	_ "github.com/stackrox/rox/migrator/migrations/m_17_to_m_18_alert_retention_config"
	_ "github.com/stackrox/rox/migrator/migrations/m_18_to_m_19_badger_migration"
	_ "github.com/stackrox/rox/migrator/migrations/m_19_to_m_20_badgerdb_duplication"
	_ "github.com/stackrox/rox/migrator/migrations/m_1_to_2_alert_violation"
	_ "github.com/stackrox/rox/migrator/migrations/m_20_to_m_21_group_colon_migration"
	_ "github.com/stackrox/rox/migrator/migrations/m_21_to_m_22_default_tolerations_disabled"
	_ "github.com/stackrox/rox/migrator/migrations/m_22_to_m_23_delete_cis_docker_1_1_0_cis_k8s_1_2_0"
	_ "github.com/stackrox/rox/migrator/migrations/m_23_to_m_24_delete_cis_k8s_1_4_1"
	_ "github.com/stackrox/rox/migrator/migrations/m_24_to_m_25_update_policy_texts"
	_ "github.com/stackrox/rox/migrator/migrations/m_25_to_m_26_starttls_auth"
	_ "github.com/stackrox/rox/migrator/migrations/m_26_to_m_27_prune_orphaned_process_whitelists"
	_ "github.com/stackrox/rox/migrator/migrations/m_27_to_m_28_dackbox"
	_ "github.com/stackrox/rox/migrator/migrations/m_28_to_m_29_img_scan_stats"
	_ "github.com/stackrox/rox/migrator/migrations/m_29_to_m_30_alert_deployment_ns_id"
	_ "github.com/stackrox/rox/migrator/migrations/m_2_to_3_network_flows_in_badger"
	_ "github.com/stackrox/rox/migrator/migrations/m_30_to_m_31_group_key_format"
	_ "github.com/stackrox/rox/migrator/migrations/m_31_to_m_32_remove_unique_indicators"
	_ "github.com/stackrox/rox/migrator/migrations/m_3_to_4_cluster_spec_to_status"
	_ "github.com/stackrox/rox/migrator/migrations/m_4_to_5_auth_provider_default_group"
	_ "github.com/stackrox/rox/migrator/migrations/m_5_to_6_collection_method"
	_ "github.com/stackrox/rox/migrator/migrations/m_6_to_7_image_update_time"
	_ "github.com/stackrox/rox/migrator/migrations/m_7_to_8_sac_cluster_namespace"
	_ "github.com/stackrox/rox/migrator/migrations/m_8_to_m_9_list_alert_cluster"
	_ "github.com/stackrox/rox/migrator/migrations/m_9_to_m_10_image_component"
)
