package m37tom38

const (
	addCaps                = "Add Capabilities"
	cve                    = "CVE"
	cvss                   = "CVSS"
	containerCPULimit      = "Container CPU Limit"
	containerCPURequest    = "Container CPU Request"
	containerMemLimit      = "Container Memory Limit"
	containerMemRequest    = "Container Memory Request"
	disallowedAnnotation   = "Disallowed Annotation"
	disallowedImageLabel   = "Disallowed Image Label"
	dockerfileLine         = "Dockerfile Line"
	dropCaps               = "Drop Capabilities"
	environmentVariable    = "Environment Variable"
	fixedBy                = "Fixed By"
	imageAge               = "Image Age"
	imageComponent         = "Image Component"
	imageRegistry          = "Image Registry"
	imageRemote            = "Image Remote"
	imageScanAge           = "Image Scan Age"
	imageTag               = "Image Tag"
	minimumRBACPermissions = "Minimum RBAC Permissions"
	port                   = "Port"
	portExposure           = "Port Exposure Method"
	privileged             = "Privileged"
	processAncestor        = "Process Ancestor"
	processArguments       = "Process Arguments"
	processName            = "Process Name"
	processUID             = "Process UID"
	protocol               = "Protocol"
	readOnlyRootFS         = "Read-Only Root Filesystem"
	requiredAnnotation     = "Required Annotation"
	requiredImageLabel     = "Required Image Label"
	requiredLabel          = "Required Label"
	unscannedImage         = "Unscanned Image"
	volumeDestination      = "Volume Destination"
	volumeName             = "Volume Name"
	volumeSource           = "Volume Source"
	volumeType             = "Volume Type"
	whitelistsEnabled      = "Unexpected Process Executed"
	writableHostMount      = "Writable Host Mount"
	writableVolume         = "Writable Volume"
)
