{
 "title": "Core Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Operation", "label": "Operation", "query": { "query": "label_values(Operation)" } },
   { "name": "Type", "label": "Type", "query": { "query": "label_values(Type)" } }
  ]
 },
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Pod CPU seconds over the last minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  increase(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=~\"(collector|sensor|compliance|admission-control|node-inventory|central|central-db|scanner|scanner-db)\"}[1m])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod)(\ncontainer_memory_usage_bytes{namespace=\"stackrox\", container=~\"(collector|sensor|compliance|admission-control|node-inventory|central|central-db|scanner|scanner-db)\"}\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Process CPU seconds over the last minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=~\"$Instance\",job!=\"kubernetes-pods\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"} / 1024^2",
     "legendFormat": "{{job}}: alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"} / 1024^2",
     "legendFormat": "{{job}}: inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"} / 1024^2",
     "legendFormat": "{{job}}: idle"
    }
   ]
  },
  { "title": "DB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bolt Object Count",
   "type": "timeseries",
   "description": "Number of key/value pairs in each bucket.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rox_central_bolt_bucket_key_n", "legendFormat": "{{Bucket}}" }
   ]
  },
  {
   "title": "RocksDB Object Count",
   "type": "timeseries",
   "description": "RocksDB prefix size (equivalent to bolt bucket).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_rocksdb_prefix_size",
     "legendFormat": "{{Prefix}}"
    }
   ]
  },
  {
   "title": "Bolt Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_bolt_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "RocksDB Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_rocksdb_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "Bolt Avg Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_bolt_op_duration_sum{Operation=~\"$Operation\", Type=~\"$Type\"} / rox_central_bolt_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "RocksDB Avg Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_rocksdb_op_duration_sum{Operation=~\"$Operation\", Type=~\"$Type\"} / rox_central_rocksdb_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "Indexer Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_index_op_duration_sum{Operation=~\"$Operation\", Type=~\"$Type\"} / rox_central_index_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "DB and Index Disk Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_bolt_db_size / 1024^2",
     "legendFormat": "Bolt"
    },
    {
     "expr": "rox_central_rocksdb_db_size / 1024^2",
     "legendFormat": "RocksDB"
    },
    {
     "expr": "rox_central_bleve_index_CurOnDiskBytes / 1024^2",
     "legendFormat": "Bleve, Index: {{Index}}"
    }
   ]
  },
  { "title": "Sensor Event Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Avg Sensor Event Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_sensor_event_duration_sum / rox_central_sensor_event_duration_count",
     "legendFormat": "Action: {{Action}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "Sensor Event Queue Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_sensor_event_queue{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  }
 ]
}