{
 "title": "Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Deployment status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Missing replicas",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_replicaset_spec_replicas - kube_replicaset_status_ready_replicas > 0",
     "legendFormat": "{{ exported_namespace }}::{{ replicaset }}"
    }
   ]
  },
  { "title": "Pod status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[5m]) > 0",
     "legendFormat": "{{ exported_namespace }}:{{ exported_pod }}:{{ container }}"
    }
   ]
  },
  {
   "title": "OOMKills",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}[10m]) == 1",
     "legendFormat": "{{ exported_namespace }}::{{ exported_pod }}::{{ container }}"
    }
   ]
  }
 ]
}