{
 "title": "CO metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Max Number of parallel scans in a time-block",
   "type": "piechart",
   "description": "Count the number of time-blocks of 1 minute (default 15 minutes) where the given number of active scan watchers were observed.\n\nE.g., a value of \"30 scans = 28\" means that there were 28 1-minute long time-windows, in which there were up to 29 scans running (29 is the next integer smaller than 30).\n\nIt may be interpreted that, for example, 29 scans could run once for 28 minutes, or there were 28 executions that each took less than a minute.",
   "gridPos": { "h": 21, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_central_complianceoperator_num_scans_running_in_parallel_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current number of scan watchers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rox_central_complianceoperator_scan_watchers_current",
     "legendFormat": "Number of scanWatchers in the map"
    }
   ]
  },
  {
   "title": "ScanWatcher activity time (minutes)",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rox_central_complianceoperator_scan_watchers_active_time_minutes_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}