{
 "title": "RHACS Dataplane - Central Debug Metrics",
 "tags": [
  "rhacs",
  "gRPC",
  "go"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes,job)"
    }
   },
   { "name": "interval", "label": "Summary Interval", "query": "1m,5m,10m,15m,30m,1h,8h,24h" },
   { "name": "Operation", "query": { "query": "label_values(Operation)" } },
   { "name": "Type", "query": { "query": "label_values(Type)" } }
  ]
 },
 "panels": [
  { "title": "gRPC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Internal\"}[$interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unknown\"}[$interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unavailable\"}[$interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unimplemented\"}[$interval]))) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval]))) OR on() vector(1)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(process_cpu_seconds_total{namespace=\"$namespace\",job=~\"$job\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(go_memstats_alloc_bytes{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "avg(go_memstats_stack_inuse_bytes{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(go_goroutines{namespace=\"$namespace\",job=\"$job\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{namespace=\"$namespace\",job=\"$job\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"OK\"}[$interval]))\n/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "OK"
      },
      {
       "expr": "(sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"AlreadyExists\"}[$interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unauthenticated\"}[$interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"FailedPrecondition\"}[$interval]))\n)/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "ClientError"
      },
      {
       "expr": "(sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Internal\"}[$interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unknown\"}[$interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unavailable\"}[$interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\",grpc_code=\"Unimplemented\"}[$interval]))\n)/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "ServerError"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"$job\"}[$interval])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Request Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"$job\"}[$interval])) by (grpc_service) \n/ ignoring(grpc_service) group_left sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"$job\"}[$interval]))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency P95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_service,le)\n)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "RPC Stream Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_msg_sent_total{namespace=\"$namespace\",job=\"$job\",grpc_type!=\"unary\"}[$interval]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(rate(grpc_server_msg_received_total{namespace=\"$namespace\",job=\"$job\",grpc_type!=\"unary\"}[$interval]))",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "RPC Type Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\"}[$interval])) by (grpc_type)\n/ ignoring(grpc_type) group_left sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"$job\"}[$interval]))",
       "legendFormat": "{{grpc_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bolt Object Count",
     "type": "timeseries",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rox_central_bolt_bucket_key_n{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{Bucket}}"
      }
     ]
    },
    {
     "title": "RocksDB Object Count",
     "type": "timeseries",
     "description": "RocksDB prefix size (equivalent to bolt bucket).",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rox_central_rocksdb_prefix_size{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{Prefix}}"
      }
     ]
    },
    {
     "title": "Bolt Operation Count",
     "type": "timeseries",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rox_central_bolt_op_duration_count{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "RocksDB Operation Count",
     "type": "timeseries",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rox_central_rocksdb_op_duration_count{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "Bolt Avg Operation Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rox_central_bolt_op_duration_sum{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_bolt_op_duration_count{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "RocksDB Avg Operation Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rox_central_rocksdb_op_duration_sum{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_rocksdb_op_duration_count{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "Indexer Operation Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rox_central_index_op_duration_sum{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_index_op_duration_count{namespace=\"$namespace\",job=\"$job\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "DB and Index Disk Consumption",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rox_central_bolt_db_size{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "Bolt"
      },
      {
       "expr": "rox_central_rocksdb_db_size{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "RocksDB"
      },
      {
       "expr": "rox_central_bleve_index_CurOnDiskBytes{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "Bleve, Index: {{Index}}"
      }
     ]
    }
   ]
  }
 ]
}