{
 "title": "Enrichment of Endpoints",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rate of objects incoming from Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rox_sensor_host_connections_incoming_objects_total[$__rate_interval])",
     "legendFormat": "{{object}} closedTS={{closedTS}}"
    }
   ]
  },
  {
   "title": "Purger runtime histogram (hostConns)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in ms but slower than the next threshold.\nE.g.: 5 for 1024 mean that there were 5 runs that took between 512 and 1024 ms.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_ms_bucket{object=\"hostConns\"}",
     "legendFormat": "<{{le}}ms"
    }
   ]
  },
  {
   "title": "Purger runtime histogram (activeEndpoints)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in ms but slower than the next threshold.\nE.g.: 5 for 1024 mean that there were 5 runs that took between 512 and 1024 ms.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_ms_bucket{object=\"activeEndpoints\"}",
     "legendFormat": "<{{le}}ms"
    }
   ]
  },
  {
   "title": "Number of purger runs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (rox_sensor_network_flow_manager_purger_duration_ms_count) by (object)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purger Events (host connections)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the host connection from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"hostConnection\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger Events (host endpoint)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the host endpoint from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"hostEndpoint\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger Events (active endpoints)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the activeEndpoint from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"activeEndpoint\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Current number of active endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_active_endpoints_current",
     "legendFormat": "Endpoints"
    }
   ]
  },
  {
   "title": "Rate of adding/removing endpoints to process enrichment",
   "type": "timeseries",
   "description": "How many endpoints (per unit of time) are added to `enrichProcessesListening`.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(rox_sensor_network_flow_manager_processes_listening_on_port_events_total[$__rate_interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Rate of processes enrichment events",
   "type": "timeseries",
   "description": "How the enrichment of listening processes has ended.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum (rate(rox_sensor_network_flow_manager_processes_listening_on_port_enrichment_events_total[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of endpoint enrichments",
   "type": "timeseries",
   "description": "How many endpoints were enriched (for network graph) per unit of time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rox_sensor_network_flow_manager_enrichments_total{object=\"endpoint\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Rate of enrichment for non-historical endpoints",
   "type": "timeseries",
   "description": "What was the outcome of enrichment of non-historical endpoints (per unit of time).",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate((rox_sensor_network_flow_manager_enrichment_endpoint_events_total{isHistorical=\"false\"}[$__rate_interval]))",
     "legendFormat": "action={{action}} reason={{reason}} containerIDfound={{containerIDfound}} historical={{isHistorical}} fresh={{fresh}} rotten={{rotten}} lastSeenSet={{lastSeenSet}} mature={{mature}}"
    }
   ]
  },
  {
   "title": "Rate of enrichment for historical endpoints",
   "type": "timeseries",
   "description": "What was the outcome of enrichment of historical endpoints (per unit of time).",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate((rox_sensor_network_flow_manager_enrichment_endpoint_events_total{isHistorical=\"true\"}[$__rate_interval]))",
     "legendFormat": "action={{action}} reason={{reason}} containerIDfound={{containerIDfound}} historical={{isHistorical}} fresh={{fresh}} rotten={{rotten}} lastSeenSet={{lastSeenSet}} mature={{mature}}"
    }
   ]
  }
 ]
}