{
 "title": "Enrichment Update Computer",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Updates and transitions of the update computer (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(rox_sensor_update_computer_update_events_total[1m])",
     "legendFormat": "{{action}} {{entity}} {{transition}}"
    }
   ]
  },
  {
   "title": "Number of updates sent to Central",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_num_sent_to_central_current",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Byte-size of dedupers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rox_sensor_host_connections_collections_size_current_bytes",
     "legendFormat": "{{Name}} {{Type}}"
    }
   ]
  },
  {
   "title": "Size of collection used in enrichment (number of elements)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_host_connections_collections_size_current",
     "legendFormat": "{{Name}} {{Type}}"
    }
   ]
  }
 ]
}