{
 "title": "Enrichment of Connections",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total number of network flows processed in Sensor",
   "type": "timeseries",
   "description": "during entire lifetime of this sensor",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_total_network_flows_sensor_received_counter",
     "legendFormat": "Received from Collector"
    },
    {
     "expr": "rox_sensor_network_flow_manager_num_sent_to_central_total{object=\"connections\"}",
     "legendFormat": "Updates sent to Central"
    }
   ]
  },
  {
   "title": "Total number of network flows received from Collector (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(rox_sensor_total_network_flows_sensor_received_counter[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of collections holding Connections ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_host_connections_collections_size_current{Type=\"connections\"}",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Connection enrichment actions",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rox_sensor_network_flow_manager_enrichment_connection_events_total) by (action, result, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host connections operations",
   "type": "piechart",
   "description": "Number with op=enrich is the size of the hostConnections.Connections map.",
   "gridPos": { "h": 11, "w": 6, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rox_sensor_host_connections_operations_total{object=\"connections\"}) by (op)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections per 1m incoming from Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(rox_sensor_host_connections_incoming_objects_total{object=\"connections\"}[1m])",
     "legendFormat": "{{object}} closedTS={{closedTS}}"
    }
   ]
  },
  {
   "title": "Rate of size increase of hostConnections.Connections per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rox_sensor_host_connections_operations_total{object=\"connections\", op=\"enrich\"}[1m])",
     "legendFormat": "num new connections per minute"
    }
   ]
  },
  {
   "title": "Number of purger runs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (rox_sensor_network_flow_manager_purger_duration_seconds_count{object!=\"activeEndpoints\"}) by (object)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purger Events (host connections)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the host connection from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"hostConnection\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger runtime histogram for hostConns (s)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in s but slower than the next threshold.\nE.g.: 5 for 1 mean that there were 5 runs that took between 0.5 and 1s.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_seconds_bucket{object=\"hostConns\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "Purger Events (active connections)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the activeConnection from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"activeConnection\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger runtime histogram for activeConnections (s)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in s but slower than the next threshold.\nE.g.: 5 for 1 mean that there were 5 runs that took between 0.5 and 1s.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_seconds_bucket{object=\"activeConnections\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_active_network_flows_current",
     "legendFormat": "Active Network Flows"
    }
   ]
  },
  {
   "title": "Rate of enrichment for non-historical connections (per minute)",
   "type": "piechart",
   "description": "What was the outcome of enrichment of non-historical connections (per unit of time).",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate((rox_sensor_network_flow_manager_enrichment_connection_events_total{isHistorical=\"false\"}[1m]))) by (action, result, checkRemoveResult, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of enrichment for historical connections",
   "type": "piechart",
   "description": "What was the outcome of enrichment of historical connections (per unit of time).",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate((rox_sensor_network_flow_manager_enrichment_connection_events_total{isHistorical=\"true\"}[$__rate_interval]))) by (action, result, checkRemoveResult, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of connections sent to central per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "rate(rox_sensor_network_flow_manager_num_sent_to_central_total{object=\"connections\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}