{
 "title": "Enrichment of Endpoints",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Size of collections holding endpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_sensor_host_connections_collections_size_current{Type=\"endpoints\"}",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Endpoint enrichment actions",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rox_sensor_network_flow_manager_enrichment_endpoint_events_total) by (action, result, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host connections operations ratio",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rox_sensor_host_connections_operations_total{object=\"endpoints\"}) by (op)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of objects incoming from Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(rox_sensor_host_connections_incoming_objects_total[1m])",
     "legendFormat": "{{object}} closedTS={{closedTS}}"
    }
   ]
  },
  {
   "title": "Number of purger runs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (rox_sensor_network_flow_manager_purger_duration_seconds_count) by (object)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purger runtime histogram for hostConns (s)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in s but slower than the next threshold.\nE.g.: 5 for 1 mean that there were 5 runs that took between 0.5 and 1s.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_seconds_bucket{object=\"hostConns\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "Purger runtime histogram for activeEndpoints (s)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in s but slower than the next threshold.\nE.g.: 5 for 10 mean that there were 5 runs that took between 2.5 and 5s.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_seconds_bucket{object=\"activeEndpoints\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "Purger runtime histogram for activeConnections (s)",
   "type": "piechart",
   "description": "Number of runs that execute faster than a given value in s but slower than the next threshold.\nE.g.: 5 for 1 mean that there were 5 runs that took between 0.5 and 1s.",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_duration_seconds_bucket{object=\"activeConnections\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "Purger Events (host connections)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the host connection from memory.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"hostConnection\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger Events (host endpoint)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the host endpoint from memory.",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"hostEndpoint\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger Events (active endpoints)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the activeEndpoint from memory.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"activeEndpoint\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Purger Events (active connections)",
   "type": "piechart",
   "description": "What kind of event lead to purging of the activeConnection from memory.",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_network_flow_manager_purger_events_total{object=\"activeConnection\"}",
     "legendFormat": "{{purgeReason}}"
    }
   ]
  },
  {
   "title": "Rate of endpoint enrichments (per minute)",
   "type": "timeseries",
   "description": "How many endpoints were enriched (for network graph) per unit of time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rox_sensor_network_flow_manager_enrichment_endpoint_events_total[1m]))"
    }
   ]
  },
  {
   "title": "Rate of enrichment for non-historical endpoints",
   "type": "piechart",
   "description": "What was the outcome of enrichment of non-historical endpoints (per unit of time).",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate((rox_sensor_network_flow_manager_enrichment_endpoint_events_total{isHistorical=\"false\"}[1m]))) by (action, result, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of enrichment for historical endpoints",
   "type": "piechart",
   "description": "What was the outcome of enrichment of historical endpoints (per unit of time).",
   "gridPos": { "h": 14, "w": 10, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate((rox_sensor_network_flow_manager_enrichment_endpoint_events_total{isHistorical=\"true\"}[1m]))) by (action, result, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(PLOP) Rate of adding/removing endpoints to process enrichment",
   "type": "piechart",
   "description": "How many endpoints (per unit of time) are added to `enrichProcessesListening`.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rox_sensor_network_flow_manager_processes_listening_on_port_events_total[1m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "(PLOP) Rate of processes enrichment events",
   "type": "piechart",
   "description": "How the enrichment of listening processes has ended.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(rox_sensor_network_flow_manager_processes_listening_on_port_enrichment_events_total[1m])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}