{
 "title": "Node Inventory Status",
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Average Node Scan Duration",
   "type": "bargauge",
   "description": "Based on rox_compliance_call_node_inventory_duration_seconds. Aggregated over selected time range.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rox_compliance_call_node_inventory_duration_seconds_sum[$__range])/rate(rox_compliance_call_node_inventory_duration_seconds_count[$__range])",
     "legendFormat": "{{exported_node_name}}"
    }
   ]
  },
  {
   "title": "Average Inventory Scan gRPC Message Size",
   "type": "stat",
   "description": "Based on rox_compliance_protobuf_inventory_message_size_bytes. Aggregated over selected time range.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rox_compliance_protobuf_inventory_message_size_bytes_sum[$__range])/rate(rox_compliance_protobuf_inventory_message_size_bytes_count[$__range])",
     "legendFormat": "{{exported_node_name}}"
    }
   ]
  },
  {
   "title": "Processed Node Scans per Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_node_scan_processed_total{job=\"sensor\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Number of Discovered Content Sets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_content_sets_in_inventory",
     "legendFormat": "{{exported_node_name}}"
    }
   ]
  },
  {
   "title": "Number of Discovered RHEL Packages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_packages_in_inventory",
     "legendFormat": "{{exported_node_name}}"
    }
   ]
  },
  {
   "title": "Inventory Rescan Interval",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_rescan_interval_seconds",
     "legendFormat": "{{exported_node_name}}"
    }
   ]
  }
 ]
}