{
 "title": "Node Scanning Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Average Inventory Scan Duration",
   "type": "graph",
   "description": "Aggregated over 5m windows",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(rox_compliance_inventory_scan_duration_seconds_sum[5m])/rate(rox_compliance_inventory_scan_duration_seconds_count[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Average Inventory Scan gRPC Message Size",
   "type": "graph",
   "description": "Aggregated over 5m windows",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(rox_compliance_protobuf_inventory_message_size_bytes_sum[5m])/rate(rox_compliance_protobuf_inventory_message_size_bytes_count[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Received Node Inventories per Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_sensor_node_inventories_received_total{job=\"sensor\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total number of received scans per pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_inventory_scans_total",
     "legendFormat": "{{node_name}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Configured Inventory Rescan Interval",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_rescan_interval_seconds",
     "legendFormat": "{{node_name}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Discovered RHEL Packages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_packages_in_inventory",
     "legendFormat": "{{node_name}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Discovered Content Sets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rox_compliance_content_sets_in_inventory",
     "legendFormat": "{{node_name}}/{{pod}}"
    }
   ]
  }
 ]
}