{
 "title": "Core Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Operation", "label": "Operation", "query": { "query": "label_values(Operation)" } },
   { "name": "Type", "label": "Type", "query": { "query": "label_values(Type)" } }
  ]
 },
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Central Pod CPU Usage",
   "type": "timeseries",
   "description": "Central Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"central\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Central Pod Memory Usage",
   "type": "timeseries",
   "description": "Central Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"stackrox\", container=\"central\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Central-db Pod CPU Usage",
   "type": "timeseries",
   "description": "Central-db Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"central-db\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Central-db Pod Memory Usage",
   "type": "timeseries",
   "description": "Central-db Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"stackrox\", container=\"central-db\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V4 Indexer Pod CPU Usage",
   "type": "timeseries",
   "description": "Scanner V4 Indexer Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", pod=~\"scanner-v4-indexer.*\", container=\"indexer\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scanner V4 Indexer Pod Memory Usage",
   "type": "timeseries",
   "description": "Scanner V4 Indexer Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  container_memory_usage_bytes{namespace=\"stackrox\", pod=~\"scanner-v4-indexer.*\", container=\"indexer\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scanner V4 Matcher Pod CPU Usage",
   "type": "timeseries",
   "description": "Scanner V4 Matcher Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", pod=~\"scanner-v4-matcher.*\", container=\"matcher\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scanner V4 Matcher Pod Memory Usage",
   "type": "timeseries",
   "description": "Scanner V4 Matcher Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  container_memory_usage_bytes{namespace=\"stackrox\", pod=~\"scanner-v4-matcher.*\", container=\"matcher\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scanner V4 DB Pod CPU Usage",
   "type": "timeseries",
   "description": "Scanner V4 DB Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", pod=~\"scanner-v4-db.*\", container=\"db\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V4 DB Pod Memory Usage",
   "type": "timeseries",
   "description": "Scanner V4 DB Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"stackrox\", pod=~\"scanner-v4-db.*\", container=\"db\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Sensor Pod CPU Usage",
   "type": "timeseries",
   "description": "Pod CPU seconds over the last minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"sensor\"}[$__rate_interval])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Sensor Pod Memory Usage",
   "type": "timeseries",
   "description": "Sensor Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(\ncontainer_memory_usage_bytes{namespace=\"stackrox\", container=\"sensor\"}\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Collector Pod CPU Usage",
   "type": "timeseries",
   "description": "Collector Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=~\"(collector|compliance|node-inventory)\"}[$__rate_interval])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Collector Pod Memory Usage",
   "type": "timeseries",
   "description": "Collector Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(\ncontainer_memory_usage_bytes{namespace=\"stackrox\", container=~\"(collector|compliance|node-inventory)\"}\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Admission Control Pod CPU Usage",
   "type": "timeseries",
   "description": "Admission Control Pod CPU Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(\n  rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"admission-control\"}[$__rate_interval])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Admission Control Pod Memory Usage",
   "type": "timeseries",
   "description": "Admission Control Pod Memory Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(\ncontainer_memory_usage_bytes{namespace=\"stackrox\", container=\"admission-control\"}\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V2 Pod CPU Usage (deprecated)",
   "type": "timeseries",
   "description": "Scanner V2 Pod CPU Usage (deprecated)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"scanner\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V2 Pod Memory Usage (deprecated)",
   "type": "timeseries",
   "description": "Scanner V2 Pod Memory Usage (deprecated)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"stackrox\", container=\"scanner\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V2 DB Pod CPU Usage (deprecated)",
   "type": "timeseries",
   "description": "Scanner V2 DB Pod CPU Usage (deprecated)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"stackrox\", container=\"scanner-db\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scanner V2 DB Pod Memory Usage (deprecated)",
   "type": "timeseries",
   "description": "Scanner V2 DB Pod Memory Usage (deprecated)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"stackrox\", container=\"scanner-db\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"}",
     "legendFormat": "{{job}}: alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"}",
     "legendFormat": "{{job}}: inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$Instance\",job!=\"kubernetes-pods\"}",
     "legendFormat": "{{job}}: idle"
    }
   ]
  },
  { "title": "DB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Indexer Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_index_op_duration_sum{Operation=~\"$Operation\", Type=~\"$Type\"} / rox_central_index_op_duration_count{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "DB and Index Disk Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_bolt_db_size / 1024^2",
     "legendFormat": "Bolt"
    },
    {
     "expr": "rox_central_rocksdb_db_size / 1024^2",
     "legendFormat": "RocksDB"
    },
    {
     "expr": "rox_central_bleve_index_CurOnDiskBytes / 1024^2",
     "legendFormat": "Bleve, Index: {{Index}}"
    }
   ]
  },
  { "title": "Sensor Event Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Avg Sensor Event Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_sensor_event_duration_sum / rox_central_sensor_event_duration_count",
     "legendFormat": "Action: {{Action}}, Type: {{Type}}"
    }
   ]
  },
  {
   "title": "Sensor Event Queue Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rox_central_sensor_event_queue{Operation=~\"$Operation\", Type=~\"$Type\"}",
     "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
    }
   ]
  }
 ]
}