---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.scanner.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: tcp-{{ .Values.app.scanner.name }}
    port: 8443
    targetPort: grpc
  selector:
    app: {{ .Values.app.scanner.name }}
  type: ClusterIP
