import static util.Helpers.withRetry

import orchestratormanager.OrchestratorTypes
import io.stackrox.proto.api.v2.ReportServiceOuterClass

import services.CollectionsService
import services.ReportV2Service

import spock.lang.Tag
import spock.lang.Shared

@Tag("CentralWorker")
class CentralWorkerTest extends BaseSpecification {

    @Shared
    private String collectionId

    def setupSpec() {
        // Create a collection scoped to the stackrox namespace for report tests
        def collection = CollectionsService.createCollection([], ["stackrox"])
        collectionId = collection.getId()
        assert collectionId
        LOG.info("Created test collection: ${collectionId}")
    }

    def cleanupSpec() {
        if (collectionId) {
            CollectionsService.deleteCollection(collectionId)
        }
    }

    def "central-worker pod should be running"() {
        expect:
        "exactly one worker pod should be running"
        withRetry(10, 3) {
            def pods = orchestrator.getPods("stackrox", "central-worker")
            assert pods.size() == 1
        }
    }

    def "Central should skip pruning when worker is enabled"() {
        expect:
        "Central should log that pruning is managed by central-worker"
        withRetry(10, 3) {
            def centralLog = orchestrator.getPodLog("stackrox",
                    orchestrator.getPods("stackrox", "central").first().metadata.name)
            assert centralLog.contains("Pruning is managed by central-worker")
        }
    }

    def "Central should skip report scheduling when worker is enabled"() {
        expect:
        "Central should log that report scheduling is managed by central-worker"
        withRetry(10, 3) {
            def centralLog = orchestrator.getPodLog("stackrox",
                    orchestrator.getPods("stackrox", "central").first().metadata.name)
            assert centralLog.contains("Report scheduling is managed by central-worker")
        }
    }

    def "Worker should run pruning cycle"() {
        expect:
        "worker should have completed a pruning cycle"
        withRetry(30, 5) {
            def workerPodName = orchestrator.getPods("stackrox", "central-worker")
                    .first().metadata.name
            def workerLog = orchestrator.getPodLog("stackrox", workerPodName)
            assert workerLog.contains("Finished garbage collection cycle")
        }
    }

    def "Worker should acquire advisory lock for pruning"() {
        expect:
        "worker should acquire and release pruning advisory lock"
        withRetry(30, 5) {
            def workerPodName = orchestrator.getPods("stackrox", "central-worker")
                    .first().metadata.name
            def workerLog = orchestrator.getPodLog("stackrox", workerPodName)
            assert workerLog.contains("Advisory lock 7293581046138294017 acquired")
            assert workerLog.contains("Advisory lock 7293581046138294017 released")
        }
    }

    def "Worker should start LISTEN/NOTIFY listener"() {
        expect:
        "worker should be listening on report channels"
        withRetry(10, 3) {
            def workerPodName = orchestrator.getPods("stackrox", "central-worker")
                    .first().metadata.name
            def workerLog = orchestrator.getPodLog("stackrox", workerPodName)
            assert workerLog.contains("Notification listener started on channels: " +
                    "[notifier_changed report_config_changed report_request_submitted report_request_cancelled]")
        }
    }

    def "On-demand report should be generated by worker"() {
        given:
        "a report configuration"
        def config = ReportV2Service.createReportConfig(
                ReportServiceOuterClass.ReportConfiguration.newBuilder()
                        .setName("e2e-worker-test-${UUID.randomUUID()}")
                        .setDescription("E2E test for central-worker report generation")
                        .setType(ReportServiceOuterClass.ReportConfiguration.ReportType.VULNERABILITY)
                        .setVulnReportFilters(
                                ReportServiceOuterClass.VulnerabilityReportFilters.newBuilder()
                                        .setFixability(
                                                ReportServiceOuterClass.VulnerabilityReportFilters
                                                        .Fixability.BOTH)
                                        .addSeverities(
                                                ReportServiceOuterClass.VulnerabilityReportFilters
                                                        .VulnerabilitySeverity.CRITICAL_VULNERABILITY_SEVERITY)
                                        .addImageTypes(
                                                ReportServiceOuterClass.VulnerabilityReportFilters
                                                        .ImageType.DEPLOYED)
                                        .setAllVuln(true)
                                        .build())
                        .setResourceScope(
                                ReportServiceOuterClass.ResourceScope.newBuilder()
                                        .setCollectionScope(
                                                ReportServiceOuterClass.CollectionReference
                                                        .newBuilder()
                                                        .setCollectionId(collectionId)
                                                        .build())
                                        .build())
                        .build())

        when:
        "submitting an on-demand report"
        def runResponse = ReportV2Service.runReport(config.getId(),
                ReportServiceOuterClass.NotificationMethod.DOWNLOAD)
        def reportId = runResponse.getReportId()

        then:
        "report should be generated successfully"
        withRetry(10, 3) {
            def status = ReportV2Service.getReportStatus(reportId)
            assert status.getStatus().getRunState() ==
                    ReportServiceOuterClass.ReportStatus.RunState.GENERATED ||
                    status.getStatus().getRunState() ==
                    ReportServiceOuterClass.ReportStatus.RunState.DELIVERED
        }

        and:
        "worker logs should show report execution"
        withRetry(10, 3) {
            def workerPodName = orchestrator.getPods("stackrox", "central-worker")
                    .first().metadata.name
            def workerLog = orchestrator.getPodLog("stackrox", workerPodName)
            assert workerLog.contains("Executing report")
        }

        cleanup:
        if (config?.getId()) {
            ReportV2Service.deleteReportConfig(config.getId())
        }
    }

    def "Worker should recover after pod restart"() {
        when:
        "killing the worker pod"
        def workerPods = orchestrator.getPods("stackrox", "central-worker")
        assert workerPods.size() == 1
        def oldPodName = workerPods.first().metadata.name
        orchestrator.deletePod("stackrox", oldPodName, 0L)

        then:
        "a new worker pod should start and complete initialization"
        withRetry(20, 5) {
            def pods = orchestrator.getPods("stackrox", "central-worker")
            assert pods.size() == 1
            def newPodName = pods.first().metadata.name
            assert newPodName != oldPodName
            def log = orchestrator.getPodLog("stackrox", newPodName)
            assert log.contains("central-worker is ready")
            assert log.contains("Finished garbage collection cycle")
        }
    }
}
