package m225tom226

import (
	"fmt"

	"github.com/stackrox/rox/migrator/types"
	"github.com/stackrox/rox/pkg/logging"
)

var (
	log = logging.LoggerForModule()

	// indexesToDrop are standalone btree indexes on the `idx` column of child tables.
	// These are redundant with the composite primary key (parent_id, idx) and are
	// never used by any application query. They were auto-generated by the walker
	// framework's getIdxField() function.
	indexesToDrop = []string{
		"authmachinetomachineconfigsmappings_idx",
		"baseimageslayers_idx",
		"collectionsembeddedcollections_idx",
		"complianceoperatorprofilev2rules_idx",
		"complianceoperatorreportsnapshotv2scans_idx",
		"complianceoperatorrulev2controls_idx",
		"complianceoperatorscanconfigurationv2clusters_idx",
		"complianceoperatorscanconfigurationv2notifiers_idx",
		"complianceoperatorscanconfigurationv2profiles_idx",
		"deploymentscontainers_idx",
		"deploymentscontainersenvs_idx",
		"deploymentscontainerssecrets_idx",
		"deploymentscontainersvolumes_idx",
		"deploymentsports_idx",
		"deploymentsportsexposureinfos_idx",
		"imageslayers_idx",
		"imagesv2layers_idx",
		"nodestaints_idx",
		"podsliveinstances_idx",
		"reportconfigurationsnotifiers_idx",
		"rolebindingssubjects_idx",
		"secretsfiles_idx",
		"secretsfilesregistries_idx",
		"vulnerabilityrequestsapprovers_idx",
		"vulnerabilityrequestsapproversv2_idx",
		"vulnerabilityrequestscomments_idx",
	}
)

func migrate(database *types.Databases) error {
	for _, name := range indexesToDrop {
		stmt := fmt.Sprintf("DROP INDEX IF EXISTS %s", name)
		if _, err := database.PostgresDB.Exec(database.DBCtx, stmt); err != nil {
			return fmt.Errorf("dropping index %s: %w", name, err)
		}
	}
	log.Infof("Dropped %d unused child-table idx indexes", len(indexesToDrop))
	return nil
}
