// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackrox/rox/central/cluster/store (interfaces: Store)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	storage "github.com/stackrox/rox/generated/storage"
	reflect "reflect"
	time "time"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddCluster mocks base method
func (m *MockStore) AddCluster(arg0 *storage.Cluster) (string, error) {
	ret := m.ctrl.Call(m, "AddCluster", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCluster indicates an expected call of AddCluster
func (mr *MockStoreMockRecorder) AddCluster(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCluster", reflect.TypeOf((*MockStore)(nil).AddCluster), arg0)
}

// CountClusters mocks base method
func (m *MockStore) CountClusters() (int, error) {
	ret := m.ctrl.Call(m, "CountClusters")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountClusters indicates an expected call of CountClusters
func (mr *MockStoreMockRecorder) CountClusters() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountClusters", reflect.TypeOf((*MockStore)(nil).CountClusters))
}

// GetCluster mocks base method
func (m *MockStore) GetCluster(arg0 string) (*storage.Cluster, bool, error) {
	ret := m.ctrl.Call(m, "GetCluster", arg0)
	ret0, _ := ret[0].(*storage.Cluster)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCluster indicates an expected call of GetCluster
func (mr *MockStoreMockRecorder) GetCluster(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockStore)(nil).GetCluster), arg0)
}

// GetClusters mocks base method
func (m *MockStore) GetClusters() ([]*storage.Cluster, error) {
	ret := m.ctrl.Call(m, "GetClusters")
	ret0, _ := ret[0].([]*storage.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusters indicates an expected call of GetClusters
func (mr *MockStoreMockRecorder) GetClusters() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusters", reflect.TypeOf((*MockStore)(nil).GetClusters))
}

// RemoveCluster mocks base method
func (m *MockStore) RemoveCluster(arg0 string) error {
	ret := m.ctrl.Call(m, "RemoveCluster", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCluster indicates an expected call of RemoveCluster
func (mr *MockStoreMockRecorder) RemoveCluster(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCluster", reflect.TypeOf((*MockStore)(nil).RemoveCluster), arg0)
}

// UpdateCluster mocks base method
func (m *MockStore) UpdateCluster(arg0 *storage.Cluster) error {
	ret := m.ctrl.Call(m, "UpdateCluster", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCluster indicates an expected call of UpdateCluster
func (mr *MockStoreMockRecorder) UpdateCluster(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockStore)(nil).UpdateCluster), arg0)
}

// UpdateClusterContactTime mocks base method
func (m *MockStore) UpdateClusterContactTime(arg0 string, arg1 time.Time) error {
	ret := m.ctrl.Call(m, "UpdateClusterContactTime", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClusterContactTime indicates an expected call of UpdateClusterContactTime
func (mr *MockStoreMockRecorder) UpdateClusterContactTime(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterContactTime", reflect.TypeOf((*MockStore)(nil).UpdateClusterContactTime), arg0, arg1)
}
