export type VulnerabilitySeverity =
    | 'LOW_VULNERABILITY_SEVERITY'
    | 'MODERATE_VULNERABILITY_SEVERITY'
    | 'IMPORTANT_VULNERABILITY_SEVERITY'
    | 'CRITICAL_VULNERABILITY_SEVERITY';

export type VulnerabilityState = 'OBSERVED' | 'DEFERRED' | 'FALSE_POSITIVE';
