// Feature flags should be listed in alpha order
export type FeatureFlagEnvVar =
    | 'ROX_DECOMMISSIONED_CLUSTER_RETENTION'
    | 'ROX_ECR_AUTO_INTEGRATION'
    | 'ROX_FRONTEND_VM_UPDATES'
    | 'ROX_NETPOL_FIELDS'
    | 'ROX_NEW_POLICY_CATEGORIES'
    | 'ROX_SECURITY_METRICS_PHASE_ONE'
    | 'ROX_SYSTEM_HEALTH_PF'
    | 'ROX_VERIFY_IMAGE_SIGNATURE';
