apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: stackrox-operator
  name: stackrox-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
