# Pushed to: "quay.io/rhacs-eng/qa:lineage-jdk-17.0.11".

FROM registry.access.redhat.com/ubi8/openjdk-17:1.19

USER root

COPY --chown=root:root dummy.txt /dummy.txt

USER jboss

ENTRYPOINT [ "/bin/sh", "-c"]
CMD [ "trap : TERM INT; sleep 9999999999d & wait" ]