apiVersion: v1
kind: Service
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-central-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    cloud.google.com/app-protocols: '{"api": "HTTPS"}'
    service.alpha.kubernetes.io/app-protocols: '{"api": "HTTPS"}'
  name: central-loadbalancer
  namespace: stackrox
  labels:
    app.kubernetes.io/component: central
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
    app.kubernetes.io/version: 4.10.1
    helm.sh/chart: stackrox-central-services-400.10.1
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: api
  selector:
    app: central
---
