package m2m

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGetKubeServiceAccountIssuer(t *testing.T) {
	fetcher := kubeServiceAccountIssuerFetcher{
		reader: &mockServiceAccountTokenReader{},
	}
	issuer, err := fetcher.GetServiceAccountIssuer()
	assert.NoError(t, err, "Did not expect error extracting issuer from token")
	assert.Equal(t, "https://kubernetes.default.svc.cluster.local", issuer)
}

const STATIC_TOKEN string = `eyJhbGciOiJSUzI1NiIsImtpZCI6InlnWGFLSGdzY0lSZ1pxQzJ2aTRoS3hSRnh0bEI2N2w3TUpsVDFYRmZTLXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUzODE3Mzk5LCJpYXQiOjE3MjIyODEzOTksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNzVhOGJhY2MtZTY5ZS00NTBlLWFmOGMtNTNmMjZjMzg0NTllIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJzdGFja3JveCIsIm5vZGUiOnsibmFtZSI6ImtpbmQtY29udHJvbC1wbGFuZSIsInVpZCI6IjI3MzVlNzM2LTI3ZGItNDZmYy1hOGFhLTExODJhZTdlMTY2ZiJ9LCJwb2QiOnsibmFtZSI6ImNlbnRyYWwtNTk2ZmY1N2ZmLWs3bjk4IiwidWlkIjoiOTA4YmIwZmQtZWJhMi00MzYzLTliNWEtNDA2ZDNkZTExMDJkIn0sInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZW50cmFsIiwidWlkIjoiODcyNDc1ZDQtNDRmOC00Nzg3LWJiYjctZWJjMGFhMzFmODc3In0sIndhcm5hZnRlciI6MTcyMjI4NTAwNn0sIm5iZiI6MTcyMjI4MTM5OSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN0YWNrcm94OmNlbnRyYWwifQ.SRV7qj2dQDrV78qRauNNdAkBp57FH1adB5eepwrBAfcwdCDRVXEG20ZXrX1U-988k2kCYIfesKuAgkbtIlNQOEWU1L7hju1Fuh_NSvwc5h4wP_5VWFS7XGszm1T8c3n3c_dkbfpjebQjFU1gMm8GHjbTMYhcSnnUZZkl5GkSTThh2d37oS5wJDd56QyS3139laOLkSziMt2h9_25luV5TlYC6QTT42SXC_65nZuOXZqqzWtTdjMX6OC4jur30u_JKcW9uwUoPoUbhbBvIMCXHqIu-pvc923VSAPWjJgjkJ8KCiR7gp1XYPVuSCh1pHJV-NsWRwYCXZIagWvD8QvF_w` // #nosec G101 -- notsecret

type mockServiceAccountTokenReader struct{}

func (k *mockServiceAccountTokenReader) readToken() (string, error) {
	return STATIC_TOKEN, nil
}
