package postgres

//go:generate pg-table-bindings-wrapper --type=storage.Image --search-category IMAGES --schema-only --search-scope IMAGE_VULNERABILITIES,IMAGE_VULNERABILITIES_V2,COMPONENT_VULN_EDGE,IMAGE_COMPONENTS,IMAGE_COMPONENTS_V2,IMAGE_COMPONENT_EDGE,IMAGE_VULN_EDGE,IMAGES,DEPLOYMENTS,NAMESPACES,CLUSTERS
