// Code generated by pg-bindings generator. DO NOT EDIT.

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/stackrox/rox/central/metrics"
	v1 "github.com/stackrox/rox/generated/api/v1"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/logging"
	ops "github.com/stackrox/rox/pkg/metrics"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/pgutils"
	pkgSchema "github.com/stackrox/rox/pkg/postgres/schema"
	"github.com/stackrox/rox/pkg/sac/resources"
	"github.com/stackrox/rox/pkg/search"
	pgSearch "github.com/stackrox/rox/pkg/search/postgres"
)

const (
	baseTable = "permission_sets"
	storeName = "PermissionSet"
)

var (
	log            = logging.LoggerForModule()
	schema         = pkgSchema.PermissionSetsSchema
	targetResource = resources.Access
)

type (
	storeType = storage.PermissionSet
	callback  = func(obj *storeType) error
)

// Store is the interface to interact with the storage for storage.PermissionSet
type Store interface {
	Upsert(ctx context.Context, obj *storeType) error
	UpsertMany(ctx context.Context, objs []*storeType) error
	Delete(ctx context.Context, id string) error
	DeleteByQuery(ctx context.Context, q *v1.Query) error
	DeleteByQueryWithIDs(ctx context.Context, q *v1.Query) ([]string, error)
	DeleteMany(ctx context.Context, identifiers []string) error
	PruneMany(ctx context.Context, identifiers []string) error

	Count(ctx context.Context, q *v1.Query) (int, error)
	Exists(ctx context.Context, id string) (bool, error)
	Search(ctx context.Context, q *v1.Query) ([]search.Result, error)

	Get(ctx context.Context, id string) (*storeType, bool, error)
	GetMany(ctx context.Context, identifiers []string) ([]*storeType, []int, error)
	GetIDs(ctx context.Context) ([]string, error)

	Walk(ctx context.Context, fn callback) error
	WalkByQuery(ctx context.Context, query *v1.Query, fn callback) error
}

// New returns a new Store instance using the provided sql instance.
func New(db postgres.DB) Store {
	// Use of pgSearch.NewGloballyScopedGenericStoreWithCache can be dangerous with high cardinality stores,
	// and be the source of memory pressure. Think twice about the need for in-memory caching
	// of the whole store.
	return pgSearch.NewGloballyScopedGenericStoreWithCache[storeType, *storeType](
		db,
		schema,
		pkGetter,
		insertIntoPermissionSets,
		copyFromPermissionSets,
		metricsSetAcquireDBConnDuration,
		metricsSetPostgresOperationDurationTime,
		metricsSetCacheOperationDurationTime,
		targetResource,
		nil,
		nil,
	)
}

// region Helper functions

func pkGetter(obj *storeType) string {
	return obj.GetId()
}

func metricsSetPostgresOperationDurationTime(start time.Time, op ops.Op) {
	metrics.SetPostgresOperationDurationTime(start, op, storeName)
}

func metricsSetAcquireDBConnDuration(start time.Time, op ops.Op) {
	metrics.SetAcquireDBConnDuration(start, op, storeName)
}

func metricsSetCacheOperationDurationTime(start time.Time, op ops.Op) {
	metrics.SetCacheOperationDurationTime(start, op, storeName)
}

func insertIntoPermissionSets(batch *pgx.Batch, obj *storage.PermissionSet) error {

	serialized, marshalErr := obj.MarshalVT()
	if marshalErr != nil {
		return marshalErr
	}

	values := []interface{}{
		// parent primary keys start
		pgutils.NilOrUUID(obj.GetId()),
		obj.GetName(),
		serialized,
	}

	finalStr := "INSERT INTO permission_sets (Id, Name, serialized) VALUES($1, $2, $3) ON CONFLICT(Id) DO UPDATE SET Id = EXCLUDED.Id, Name = EXCLUDED.Name, serialized = EXCLUDED.serialized"
	batch.Queue(finalStr, values...)

	return nil
}

var copyColsPermissionSets = []string{
	"id",
	"name",
	"serialized",
}

func copyFromPermissionSets(ctx context.Context, s pgSearch.Deleter, tx *postgres.Tx, objs ...*storage.PermissionSet) error {
	if len(objs) == 0 {
		return nil
	}

	{
		// CopyFrom does not upsert, so delete existing rows first to achieve upsert behavior.
		// Parent deletion cascades to children, so only the top-level parent needs deletion.
		deletes := make([]string, 0, len(objs))
		for _, obj := range objs {
			deletes = append(deletes, obj.GetId())
		}
		if err := s.DeleteMany(ctx, deletes); err != nil {
			return err
		}
	}

	idx := 0
	inputRows := pgx.CopyFromFunc(func() ([]any, error) {
		if idx >= len(objs) {
			return nil, nil
		}
		obj := objs[idx]
		idx++

		serialized, marshalErr := obj.MarshalVT()
		if marshalErr != nil {
			return nil, marshalErr
		}

		return []interface{}{
			pgutils.NilOrUUID(obj.GetId()),
			obj.GetName(),
			serialized,
		}, nil
	})

	if _, err := tx.CopyFrom(ctx, pgx.Identifier{"permission_sets"}, copyColsPermissionSets, inputRows); err != nil {
		return err
	}

	return nil
}

// endregion Helper functions
