{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable -}}

apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "service" "scanner") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "service" "scanner") | nindent 4 }}
spec:
  ports:
    - name: https-scanner
      port: 8080
      targetPort: 8080
    - name: grpcs-scanner
      port: 8443
      targetPort: 8443
    {{ if ._rox.scanner.exposeMonitoring -}}
    - name: monitoring
      port: 9090
      targetPort: monitoring
    {{- end}}
  selector:
    app: scanner
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: scanner-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "service" "scanner-db") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "service" "scanner-db") | nindent 4 }}
spec:
  ports:
    - name: tcp-db
      port: 5432
      targetPort: 5432
  selector:
    app: scanner-db
  type: ClusterIP

{{ end -}}
