apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/stackrox?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-comment: "/konflux-retest go-mod-validation"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      (has(body.pull_request) && has(body.pull_request.labels) &&
       body.pull_request.labels.exists(l, l.name == "go-mod-check")) &&
      body.action != "ready_for_review"
    pipelinesascode.tekton.dev/on-label: "[]"
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: go-mod-validation
    pipelines.appstudio.openshift.io/type: build
  name: go-mod-validation-on-push
  namespace: rh-acs-tenant

spec:

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image-repo
    # TODO: Change to quay.io/rhacs-eng/go-mod-validation once dedicated service account is created
    value: quay.io/rhacs-eng/release-roxctl
  - name: clone-depth
    value: '1'
  - name: clone-fetch-tags
    value: 'false'
  - name: oci-artifact-expires-after
    value: '1d'
  - name: hermetic
    value: "true"

  pipelineRef:
    name: go-mod-validation-pipeline

  taskRunTemplate:
    # TODO: Change to build-pipeline-go-mod-validation once created
    serviceAccountName: build-pipeline-roxctl

  timeouts:
    tasks: 10m
    finally: 2m
    pipeline: 12m

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
