apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/stackrox?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-comment: "/konflux-retest roxctl-tars-on-push"
    # TODO(ROX-21073): re-enable for all PR branches
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        event == "push" && target_branch.matches("^(master|release-.*|refs/tags/.*)$")
      ) || (
        event == "pull_request" && (
          target_branch.startsWith("release-") ||
          source_branch.matches("(konflux|renovate|appstudio|rhtap)") ||
          (has(body.pull_request) && has(body.pull_request.labels) && body.pull_request.labels.exists(l, l.name == "konflux-build"))
        ) && body.action != "ready_for_review"
      )
    # The empty `on-label` annotation is a workaround to make sure the pipeline gets triggered when the label gets first
    # added to the PR. See the Slack tread linked from ROX-30580.
    pipelinesascode.tekton.dev/on-label: "[]"
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: roxctl-tars
    pipelines.appstudio.openshift.io/type: build
  name: roxctl-tars-on-push
  namespace: rh-acs-tenant

spec:

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image-repo
    value: quay.io/rhacs-eng/release-roxctl-tars
  - name: main-image-repo
    value: quay.io/rhacs-eng/release-main
  - name: image-expires-after
    value: '13w'
  - name: output-tag-suffix
    value: '-fast'
  - name: rebuild
    value: 'true'
  - name: skip-checks
    value: 'false'
  - name: extra-labels
    value:
    # X.Y in the cpe label must be adjusted for every version stream.
    - "cpe=cpe:/a:redhat:advanced_cluster_security:X.Y::el9"

  taskRunTemplate:
    serviceAccountName: build-pipeline-roxctl

  # IMPORTANT: when changing timeouts here, read and follow timeout instructions in operator-bundle-build.yaml.
  # The wait-for-main-image task must accommodate the full main image build time (~2h30m).
  timeouts:
    tasks: 3h
    finally: 10m
    pipeline: 3h10m

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  pipelineSpec:

    finally:
    - name: slack-notification
      params:
      - name: message
        value: ':x: `{{event_type}}` pipeline for <https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/$(context.pipelineRun.namespace)/pipelinerun/$(context.pipelineRun.name)|$(context.pipelineRun.name)> (`$(params.output-image-repo)`, revision <$(params.git-url)/commit/$(params.revision)|$(params.revision)>) has failed.'
      - name: key-name
        value: 'acs-konflux-notifications'
      when:
      - input: $(tasks.status)
        operator: in
        values: ["Failed"]
      taskRef:
        params:
        - name: name
          value: slack-webhook-notification
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:02842e9c752056c47a409f69ed462cfd38cbd6b15facb796564a610b549222ea
        - name: kind
          value: task
        resolver: bundles

    - name: post-metric-end
      params:
      - name: AGGREGATE_TASKS_STATUS
        value: $(tasks.status)
      taskRef: &post-bigquery-metrics-ref
        params:
        - name: name
          value: post-bigquery-metrics
        - name: bundle
          value: quay.io/rhacs-eng/konflux-tasks:latest@sha256:d6819ce66939d63ae878e97ab26665872570179ccd43843b93b3009f44f7e401
        - name: kind
          value: task
        resolver: bundles

    params:
    - name: git-url
      type: string
    - name: revision
      type: string
    - name: output-image-repo
      type: string
    - name: main-image-repo
      type: string
    - name: image-expires-after
      type: string
    - name: output-tag-suffix
      type: string
    - name: rebuild
      type: string
    - name: skip-checks
      type: string
      default: "false"
    - name: extra-labels
      type: array

    results:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)

    workspaces:
    - name: git-auth

    tasks:

    - name: post-metric-start
      taskRef: *post-bigquery-metrics-ref

    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      - name: depth
        value: '0'
      - name: fetchTags
        value: 'true'
      - name: ociStorage
        value: $(params.output-image-repo):konflux-$(params.revision).git
      - name: ociArtifactExpiresAfter
        value: 1d
      taskRef:
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.2.6@sha256:3bcd4c39a346d29617013f4c47d245d38f020cdbf814cf3ce095911c528f5003
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: basic-auth
        workspace: git-auth

    - name: determine-image-tag
      params:
      - name: TAG_SUFFIX
        value: $(params.output-tag-suffix)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        params:
        - name: name
          value: determine-image-tag
        - name: bundle
          value: quay.io/rhacs-eng/konflux-tasks:latest@sha256:d6819ce66939d63ae878e97ab26665872570179ccd43843b93b3009f44f7e401
        - name: kind
          value: task
        resolver: bundles

    - name: determine-image-expiration
      params:
      - name: DEFAULT_IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        params:
        - name: name
          value: determine-image-expiration
        - name: bundle
          value: quay.io/rhacs-eng/konflux-tasks:latest@sha256:d6819ce66939d63ae878e97ab26665872570179ccd43843b93b3009f44f7e401
        - name: kind
          value: task
        resolver: bundles

    - name: wait-for-main-image
      params:
      - name: IMAGE
        value: "$(params.main-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)"
      taskRef:
        params:
        - name: name
          value: wait-for-image
        - name: bundle
          value: quay.io/rhacs-eng/konflux-tasks:latest@sha256:d6819ce66939d63ae878e97ab26665872570179ccd43843b93b3009f44f7e401
        - name: kind
          value: task
        resolver: bundles
      # Keep in sync with tasks timeout in main-build.yaml.
      timeout: 2h55m

    - name: build-image
      params:
      - name: IMAGE
        value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)
      - name: DOCKERFILE
        value: image/roxctl-tars/konflux.Dockerfile
      - name: CONTEXT
        value: .
      - name: HERMETIC
        value: 'false'
      - name: PREFETCH_INPUT
        value: ''
      - name: IMAGE_EXPIRES_AFTER
        value: $(tasks.determine-image-expiration.results.IMAGE_EXPIRES_AFTER)
      - name: COMMIT_SHA
        value: $(tasks.clone-repository.results.commit)
      - name: BUILD_ARGS
        value:
        - BUILD_TAG=$(tasks.determine-image-tag.results.IMAGE_TAG)
        - MAIN_IMAGE=$(params.main-image-repo)@$(tasks.wait-for-main-image.results.IMAGE_DIGEST)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      - name: BUILDAH_FORMAT
        value: docker
      - name: LABELS
        value: ["$(params.extra-labels[*])"]
      - name: BUILD_TIMESTAMP
        value: "$(tasks.clone-repository.results.commit-timestamp)"
      - name: PLATFORM
        value: linux/amd64
      - name: IMAGE_APPEND_PLATFORM
        value: 'false'
      taskRef:
        params:
        - name: name
          value: buildah-remote-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.12.0@sha256:44c1ca2e823f006ee94e066231b033b191f0f8cee51add1e908138335eba9b30
        - name: kind
          value: task
        resolver: bundles
      runAfter: [wait-for-main-image]

    - name: build-image-index
      params:
      - name: IMAGE
        value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)
      - name: IMAGES
        value:
        - $(tasks.build-image.results.IMAGE_REF)
      - name: BUILDAH_FORMAT
        value: docker
      taskRef:
        params:
        - name: name
          value: build-image-index
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.3.1@sha256:c2cda69e681c976dd5b39caf6682d1c8f8c5e5a53a67a22a5b06d4cde773bd10
        - name: kind
          value: task
        resolver: bundles
      runAfter: [build-image]

    - name: deprecated-base-image-check
      params:
      - name: IMAGE_URL
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      taskRef:
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:0ccc688a77e9b7b0b8973c132a1e840844137e77f887be4a0bec8893b0776872
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values: ["false"]

    - name: clair-scan
      params:
      - name: image-digest
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: image-platform
        value: linux/amd64
      taskRef:
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.4.0@sha256:dcc6ca58d3ec03d05ce21c03b4f51b58cac9878caa932ad06a9fdf4bc422aaab
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values: ["false"]

    - name: ecosystem-cert-preflight-checks
      params:
      - name: image-url
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: platform
        value: linux/amd64
      taskRef:
        params:
        - name: name
          value: ecosystem-cert-preflight-checks
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:4619769705d4999e129b779d7699d89d33c47f7ab80d73ad6e3dcd8a6a4e43a7
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values: ["false"]

    - name: clamav-scan
      params:
      - name: image-digest
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: image-arch
        value: linux/amd64
      taskRef:
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3.1@sha256:53a02326bfb930ca5ef6bfa7a33acca833d57752f34f3cb79255fe2e25e7d217
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values: ["false"]

    - name: rpms-signature-scan
      params:
      - name: image-digest
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-image-index.results.IMAGE_URL)
      taskRef:
        params:
        - name: name
          value: rpms-signature-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2.1@sha256:538a853c4a299216c43258ccc9894215f5440dc0c70c9c99fe22fc9633a8e79d
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values: ["false"]

    - name: push-dockerfile
      params:
      - name: IMAGE
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - name: DOCKERFILE
        value: image/roxctl-tars/konflux.Dockerfile
      - name: CONTEXT
        value: .
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        params:
        - name: name
          value: push-dockerfile-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.3.1@sha256:393b4d0b530c2657b3ff6fec714781f4938b95b699dea2b369442b7664e1cce2
        - name: kind
          value: task
        resolver: bundles
