apiVersion: v1
kind: Service
metadata:
  name: central
  namespace: stackrox
  labels:
    app.kubernetes.io/component: central
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
    app.kubernetes.io/version: 4.10.1
    helm.sh/chart: stackrox-central-services-400.10.1
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-central-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    service.beta.openshift.io/serving-cert-secret-name: central-monitoring-tls
spec:
  ports:
    - name: https
      port: 443
      targetPort: api
    - name: monitoring-tls
      port: 9091
      targetPort: monitoring-tls
  selector:
    app: central
  type: ClusterIP
