#!/usr/bin/env bash

# Note: This is also used for Scanner.

set -euo pipefail

# The function copies everything that could be found under the path provided in
# the first argument, ignoring files starting with '..' which are created by
# kubernetes secret volume mount process.
copy_existing () {
    src=$1
    if [ -d "$src" ] && [ "$(ls -A -I "..*" "$src")" ]; then
        cp -v -L "$src"/* /etc/pki/ca-trust/source/anchors
    else
        echo "No certificates found in $src"
    fi
}

copy_existing /usr/local/share/ca-certificates

# Copy the custom trusted CA bundles injected by the Openshift Network Operator.
copy_existing /etc/pki/injected-ca-trust

# TODO(DO NOT MERGE): For some reason, without the `--output` flag,
#  `update-ca-trust` expects `/etc/pki/ca-trust/extracted` to have all the
#  necessary directories created. However, if run with `--output` flag, it'll
#  create the directories :shrug:. Figure out why.
#  Possible thread to pull on: https://bugzilla.redhat.com/show_bug.cgi?id=2241240
update-ca-trust extract --output /etc/pki/ca-trust/extracted
