#!/usr/bin/env bash

# Note: This is also used for Scanner.

set -euo pipefail

[ -d /.init-dirs ] || exit 0

# We use --no-clobber here because we don't need to re-copy files on container restarts.
cp --recursive --no-dereference --no-clobber /.init-dirs/* /
