#!/usr/bin/env bash

# Note: This is also used for Scanner.

set -euo pipefail

if [ $# -lt 1 ]; then
	echo >&2 "Usage: $0 <dirs...>"
	exit 1
fi

for dir in "$@"; do
	dir_no_leading_slash="${dir#/}"

	if [ ${#dir} -eq ${#dir_no_leading_slash} ]; then
		echo >&2 "Directory must be an absolute path, is: ${dir}"
		exit 1
	fi

	target_dir="/.init-dirs/${dir_no_leading_slash}"
	mkdir -p "${target_dir}"
	cp -rpP "${dir}"/* "${target_dir}"
done
