# After build the resulting image was pushed to: "quay.io/rhacs-eng/qa:dele-scan-memcached".
#
# The resulting image should ONLY be used by the delegated scanning tests.

FROM docker.io/library/memcached:1.6.31
