{{- include "srox.init" . -}}

{{ if and ._rox.network.enableNetworkPolicies ._rox.ha.pgbouncer.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgbouncer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "pgbouncer") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "pgbouncer") | nindent 4 }}
spec:
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: central
    ports:
    - port: 5432
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: central-reports
    ports:
    - port: 5432
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: central-pruning
    ports:
    - port: 5432
      protocol: TCP
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: central-db
    ports:
    - port: 5432
      protocol: TCP
  podSelector:
    matchLabels:
      app: pgbouncer
{{- end }}
