---
global:
  gc: true
  indexerConfig:
    enabled: true
    type: elastic
    esServers: [ {{ env "ELASTICSEARCH_URL" }} ]
    defaultIndex: kube-burner-long-running-test
  measurements: []
jobs:
  - name: berserker-load
    namespace: berserker
    jobIterations: 5
    jobPause: 1000h
    qps: 20
    burst: 20
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 30s
    churn: true
    churnDuration: 1000h
    churnDelay: 10m
    churnPercent: 80
    maxWaitTimeout: 12m
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
{{- if env "BERSERKER_OBJECTS" }}
{{ env "BERSERKER_OBJECTS" | indent 6 }}
{{- else }}

      - objectTemplate: berserker-configmap.yml
        replicas: 10
        inputVars:
          configMapName: berserker-process-config
          configData: |-
            workload.toml: |
              restart_interval = 10
              workers = 1

              [workload]
              type = "processes"
              arrival_rate = 1000.0
              departure_rate = 200.0
              random_process = true

      - objectTemplate: berserker-configmap.yml
        replicas: 10
        inputVars:
          configMapName: berserker-config
          configData: |-
            workload.toml: |
              restart_interval = 10
              workers = 9

              [workload]
              type = "endpoints"
              distribution = "zipf"
              n_ports = 2000
              exponent = 1.4

      - objectTemplate: berserker-configmap.yml
        replicas: 10
        inputVars:
          configMapName: berserker-connections-config
          configData: |-
            network-server.toml: |
              restart_interval = 10
              workers = 1
              per_core = false

              [workload]
              type = "network"
              server = true
              address = "223.42.0.1"
              target_port = 1337
              arrival_rate = 10
              departure_rate = 10
              conns_per_addr = 2
              nconnections = 4000

            network-client.toml: |
              restart_interval = 10
              workers = 1
              per_core = false

              [workload]
              type = "network"
              server = false
              address = "223.42.0.1"
              target_port = 1337
              arrival_rate = 10
              departure_rate = 10
              conns_per_addr = 2
              nconnections = 4000

      - objectTemplate: berserker-configmap.yml
        replicas: 10
        inputVars:
          configMapName: berserker-file-activity-config
          configData: |-
            workload.ber: |
              machine {
                path("/tmp/data");
              }

              main (workers = 2, duration = 0) {
                open(random_path("/tmp/data"));
              } : exp {
                rate = 100.0;
              }

      - objectTemplate: berserker-daemonset.yml
        replicas: 6
        inputVars:
          namePrefix: process-load
          imageTag: "1.0-86-g3464e60064"
          args: |-
            - sleep
            - infinity
          memRequest: "10Mi"
          cpuRequest: "15m"
          memLimit: "10Mi"
          cpuLimit: "15m"
          configMapName: berserker-process-config
          extraEnv: |-
            - name: BERSERKER__WORKLOAD__ARRIVAL_RATE
              value: "1"

      - objectTemplate: berserker-daemonset.yml
        replicas: 6
        inputVars:
          namePrefix: endpoint-load
          imageTag: "1.0-86-g3464e60064"
          memRequest: "100Mi"
          cpuRequest: "25m"
          memLimit: "180Mi"
          cpuLimit: "25m"
          configMapName: berserker-config
          ports: |-
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP

      - objectTemplate: berserker-daemonset.yml
        replicas: 6
        inputVars:
          namePrefix: connection-load
          imageTag: "network-1.0-85-g1b7ab034aa"
          memRequest: "100Mi"
          cpuRequest: "25m"
          memLimit: "180Mi"
          cpuLimit: "25m"
          configMapName: berserker-connections-config
          ports: |-
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          generateIP: true
          privileged: true

      - objectTemplate: berserker-daemonset.yml
        replicas: 1
        inputVars:
          namePrefix: file-activity-load
          imageTag: "1.0-96-gc213cfd0c7"
          command: |-
            - berserker
          args: |-
            - -f
            - /etc/berserker/workload.ber
          memRequest: "200Mi"
          cpuRequest: "15m"
          memLimit: "200Mi"
          cpuLimit: "15m"
          configMapName: berserker-file-activity-config

      - objectTemplate: service.yml
        replicas: 10
{{- end }}
