name: Batch load test metrics
on:
  workflow_dispatch:
  schedule:
  - cron: 23 * * * *

# Ensure that only a single batch loader is running
concurrency: Batch load test metrics

jobs:
  batch-load-test-metrics:
    if:  ${{ github.repository_owner == 'stackrox' }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.11@sha256:df3459cf038e73775314b3a5d36d14dda41e6df438a0273c9efa8d23e0f2358a # ratchet:quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.11
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
    - name: Load
      env:
        GCP_SERVICE_ACCOUNT_STACKROX_CI: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
      shell: bash
      run: |
        source scripts/ci/lib.sh

        setup_gcp
        batch_load_test_metrics
