name: Batch load test metrics
on:
  workflow_dispatch:
  schedule:
  - cron: 23 * * * *

# Ensure that only a single batch loader is running
concurrency: Batch load test metrics

jobs:
  batch-load-test-metrics:
    if:  ${{ github.repository_owner == 'stackrox' }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.3@sha256:39fd328dcc903b7d8a2f3eb6d9e5ddbf79569227a5667296b4b927f74c11b32a # ratchet:quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.3
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
    - name: Load
      env:
        GCP_SERVICE_ACCOUNT_STACKROX_CI: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
      shell: bash
      run: |
        source scripts/ci/lib.sh

        setup_gcp
        batch_load_test_metrics
