name: e2e Sensor Upgrade Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

concurrency: upgrade-sensor-${{ github.ref }}

jobs:
  sensor-upgrade-test:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The cluster name must be no longer than 26 characters.
      CLUSTER_NAME: e2e-sens-${{ github.run_id }}-${{ github.run_attempt }}
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.3
      volumes:
        - /usr:/mnt/usr
        - /opt:/mnt/opt
    timeout-minutes: 240
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/job-preamble
        with:
          gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

      - name: Fix $PATH for infractl
        run: echo "$HOME/.local/bin" >s> "$GITHUB_PATH"

      - name: Create test cluster
        uses: stackrox/actions/infra/create-cluster@v1
        with:
          token: ${{ secrets.INFRA_TOKEN }}
          flavor: gke-default
          name: ${{ env.CLUSTER_NAME }}
          lifespan: 4h
          args: nodes=3,machine-type=e2-standard-8
          wait: false

      - name: Docker login to Quay.io
        env:
          REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        run: |
          docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Wait for the cluster and grab artifacts
        timeout-minutes: 25
        run: |
          infractl wait "${CLUSTER_NAME}"
          infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
          echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

      - name: Verify kubectl access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Run postgres sensor upgrade test
        env:
          QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
          REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
          STORAGE: pvc
          CLUSTER_TYPE_FOR_TEST: K8S
          LOAD_BALANCER: lb
          CI_JOB_NAME: gha-upgrade-postgres-sensor-test
        run: |
          tests/upgrade/postgres_sensor_run.sh /tmp/postgres-sensor-upgrade-test-logs

      - name: Delete cluster
        if: always()
        run: |
          infractl delete "${CLUSTER_NAME}"
