name: e2e-gke-upgrade-tests

on:
  workflow_call:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true
      should-run:
        description: true if should really run the job. false - otherwise, i.e. the job should be skipped.
        type: boolean
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  # Verifies Central DB upgrades/rollbacks.
  gke-upgrade-tests-central:
    if: github.event_name == 'workflow_dispatch' || inputs.should-run
    runs-on: ubuntu-latest
    env:
      MAIN_IMAGE_TAG: ${{ inputs.tag }}
      BUILD_TAG: ${{ inputs.tag }}
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The cluster name must be no longer than 26 characters.
      CLUSTER_NAME: e2e-cent-${{ github.run_id }}-${{ github.run_attempt }}
      # Not making CI_JOB_NAME match *gke-upgrade-tests because JUnit reporting will be broken since the former
      # gke-upgrade-tests expect all sensor, central and postgres tests to run together in a single sequence.
      CI_JOB_NAME: gke-upgrade-tests-central
      ARTIFACT_DIR: ./junit-reports
      # Make sure Python steps don't buffer stdout/stderr.
      PYTHONUNBUFFERED: "1"
    timeout-minutes: 180 # Keep in sync with cluster's lifespan
    steps:

    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        persist-credentials: false

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Trigger test cluster creation
      uses: stackrox/actions/infra/create-cluster@79f8a64e6701be953c23ef1718fcc186a2fb0d0d # ratchet:stackrox/actions/infra/create-cluster@v1
      with:
        token: ${{ secrets.INFRA_TOKEN }}
        flavor: gke-default
        name: ${{ env.CLUSTER_NAME }}
        lifespan: 3h # Keep in sync with job's timeout-minutes
        args: nodes=3,machine-type=e2-standard-8
        wait: false

    - name: Docker login to Quay.io
      env:
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      run: docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # ratchet:google-github-actions/setup-gcloud@v3
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Build roxctl
      run: make roxctl_linux-amd64

    - name: Wait for the cluster and grab artifacts
      timeout-minutes: 25
      run: |
        infractl wait "${CLUSTER_NAME}"
        infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
        echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

    - name: Verify kubectl access and wait for cluster to stabilize
      timeout-minutes: 5
      run: |
        kubectl cluster-info
        kubectl get nodes
        scripts/ci/gke.sh wait_for_cluster

    - name: Run pre-test
      shell: python
      env:
        QUAY_RHACS_ENG_BEARER_TOKEN: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from pre_tests import PreSystemTests
        PreSystemTests().run()

    - name: Fix GOPATH and PATH for building and running roxctl during tests
      run: |
        GOPATH="$(go env GOPATH)"
        echo "GOPATH=${GOPATH}" | tee -a "${GITHUB_ENV}"
        echo "${GOPATH}/bin" | tee -a "${GITHUB_PATH}"

    - name: Run central upgrade test
      env:
        LONGTERM_LICENSE: todo - remove me
        QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        GOOGLE_CREDENTIALS_GCR_SCANNER_V2: ${{ secrets.GOOGLE_CREDENTIALS_GCR_SCANNER_V2 }}
        GOOGLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT_V2: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT_V2 }}
        REDHAT_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME_RO }}
        REDHAT_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD_RO }}
        LOAD_BALANCER: lb
      run: |
        tests/upgrade/postgres_run.sh /tmp/postgres-upgrade-test-logs
        # This makes sure Stackrox_Deployment / Was Stackrox deployed to the cluster? test does not fail.
        touch /tmp/stackrox_ci_state_deployed

    - name: Run post-test
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import PostClusterTest
        PostClusterTest(collect_central_artifacts=True).run(['/tmp/postgres-upgrade-test-logs', '${{ env.ARTIFACT_DIR }}'])

    - name: Run final-post
      if: always()
      shell: python
      env:
        QA_TEST_DEBUG_LOGS: /tmp/qa-tests-backend-logs
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import FinalPost
        FinalPost(store_qa_tests_data=True).run()

    - name: Teardown cluster
      if: always()
      continue-on-error: true
      run: |
        if ! infractl delete "${CLUSTER_NAME}"; then
          echo "::warning::WARNING: Could not tear down cluster ${CLUSTER_NAME}. See Teardown step logs for details."
          exit 6
        fi

    - name: Publish test summary
      uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # ratchet:test-summary/action@v2
      if: always()
      with:
        paths: ${{ env.ARTIFACT_DIR }}/**/*.xml
        show: all

    - name: Report junit failures in jira
      if: (!cancelled())
      id: junit2jira
      uses: ./.github/actions/junit2jira
      with:
        create-jiras: ${{ github.event_name == 'push' }}
        jira-user: ${{ secrets.JIRA_USER }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
        directory: ${{ env.ARTIFACT_DIR }}

  # Verifies we can do Postgres major version upgrade.
  gke-upgrade-tests-postgres:
    if: github.event_name == 'workflow_dispatch' || inputs.should-run
    runs-on: ubuntu-latest
    env:
      MAIN_IMAGE_TAG: ${{ inputs.tag }}
      BUILD_TAG: ${{ inputs.tag }}
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The cluster name must be no longer than 26 characters.
      CLUSTER_NAME: e2e-pg-${{ github.run_id }}-${{ github.run_attempt }}
      # Not making CI_JOB_NAME match *gke-upgrade-tests because JUnit reporting will be broken since the former
      # gke-upgrade-tests expect all sensor, central and postgres tests to run together in a single sequence.
      CI_JOB_NAME: gke-upgrade-tests-postgres
      ARTIFACT_DIR: ./junit-reports
      # Make sure Python steps don't buffer stdout/stderr.
      PYTHONUNBUFFERED: "1"
    timeout-minutes: 180 # Keep in sync with cluster's lifespan
    steps:

    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        persist-credentials: false

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Trigger test cluster creation
      uses: stackrox/actions/infra/create-cluster@79f8a64e6701be953c23ef1718fcc186a2fb0d0d # ratchet:stackrox/actions/infra/create-cluster@v1
      with:
        token: ${{ secrets.INFRA_TOKEN }}
        flavor: gke-default
        name: ${{ env.CLUSTER_NAME }}
        lifespan: 3h # Keep in sync with job's timeout-minutes
        args: nodes=3,machine-type=e2-standard-8
        wait: false

    - name: Docker login to Quay.io
      env:
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      run: docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # ratchet:google-github-actions/setup-gcloud@v3
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Build roxctl
      run: make roxctl_linux-amd64

    - name: Wait for the cluster and grab artifacts
      timeout-minutes: 25
      run: |
        infractl wait "${CLUSTER_NAME}"
        infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
        echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

    - name: Verify kubectl access and wait for cluster to stabilize
      timeout-minutes: 5
      run: |
        kubectl cluster-info
        kubectl get nodes
        scripts/ci/gke.sh wait_for_cluster

    - name: Run pre-test
      shell: python
      env:
        QUAY_RHACS_ENG_BEARER_TOKEN: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from pre_tests import PreSystemTests
        PreSystemTests().run()

    - name: Fix GOPATH and PATH for building and running roxctl during tests
      run: |
        GOPATH="$(go env GOPATH)"
        echo "GOPATH=${GOPATH}" | tee -a "${GITHUB_ENV}"
        echo "${GOPATH}/bin" | tee -a "${GITHUB_PATH}"

    - name: Run postgres version upgrade test
      env:
        LONGTERM_LICENSE: todo - remove me
        QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        GOOGLE_CREDENTIALS_GCR_SCANNER_V2: ${{ secrets.GOOGLE_CREDENTIALS_GCR_SCANNER_V2 }}
        REDHAT_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME_RO }}
        REDHAT_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD_RO }}
        LOAD_BALANCER: lb
      run: |
        tests/upgrade/postgres_upgrade_run.sh /tmp/postgres-version-upgrade-test-logs
        # This makes sure Stackrox_Deployment / Was Stackrox deployed to the cluster? test does not fail.
        touch /tmp/stackrox_ci_state_deployed

    - name: Run post-test
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import PostClusterTest
        PostClusterTest(collect_central_artifacts=True).run(['/tmp/postgres-version-upgrade-test-logs', '${{ env.ARTIFACT_DIR }}'])

    - name: Run final-post
      if: always()
      shell: python
      env:
        QA_TEST_DEBUG_LOGS: /tmp/qa-tests-backend-logs
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import FinalPost
        FinalPost(store_qa_tests_data=True).run()

    - name: Teardown cluster
      if: always()
      continue-on-error: true
      run: |
        if ! infractl delete "${CLUSTER_NAME}"; then
          echo "::warning::WARNING: Could not tear down cluster ${CLUSTER_NAME}. See Teardown step logs for details."
          exit 6
        fi

    - name: Publish test summary
      uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # ratchet:test-summary/action@v2
      if: always()
      with:
        paths: ${{ env.ARTIFACT_DIR }}/**/*.xml
        show: all

    - name: Report junit failures in jira
      if: (!cancelled())
      id: junit2jira
      uses: ./.github/actions/junit2jira
      with:
        create-jiras: ${{ github.event_name == 'push' }}
        jira-user: ${{ secrets.JIRA_USER }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
        directory: ${{ env.ARTIFACT_DIR }}

  # Verifies Sensor/Secured Cluster `upgrader` (applicable to manifest installations only).
  gke-upgrade-tests-sensor:
    if: github.event_name == 'workflow_dispatch' || inputs.should-run
    runs-on: ubuntu-latest
    env:
      MAIN_IMAGE_TAG: ${{ inputs.tag }}
      BUILD_TAG: ${{ inputs.tag }}
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The cluster name must be no longer than 26 characters.
      CLUSTER_NAME: e2e-sens-${{ github.run_id }}-${{ github.run_attempt }}
      # Not making CI_JOB_NAME match *gke-upgrade-tests because JUnit reporting will be broken since the former
      # gke-upgrade-tests expect all sensor, central and postgres tests to run together in a single sequence.
      CI_JOB_NAME: gke-upgrade-tests-sensor
      ARTIFACT_DIR: ./junit-reports
      # Make sure Python steps don't buffer stdout/stderr.
      PYTHONUNBUFFERED: "1"
    timeout-minutes: 60 # Keep in sync with cluster's lifespan
    steps:

    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        persist-credentials: false

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Trigger test cluster creation
      uses: stackrox/actions/infra/create-cluster@79f8a64e6701be953c23ef1718fcc186a2fb0d0d # ratchet:stackrox/actions/infra/create-cluster@v1
      with:
        token: ${{ secrets.INFRA_TOKEN }}
        flavor: gke-default
        name: ${{ env.CLUSTER_NAME }}
        lifespan: 1h # Keep in sync with job's timeout-minutes
        args: nodes=3,machine-type=e2-standard-8
        wait: false

    - name: Docker login to Quay.io
      env:
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      run: docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # ratchet:google-github-actions/setup-gcloud@v3
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Build roxctl and upgrader
      run: make roxctl_linux-amd64 upgrader

    - name: Wait for the cluster and grab artifacts
      timeout-minutes: 25
      run: |
        infractl wait "${CLUSTER_NAME}"
        infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
        echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

    - name: Verify kubectl access and wait for cluster to stabilize
      timeout-minutes: 5
      run: |
        kubectl cluster-info
        kubectl get nodes
        scripts/ci/gke.sh wait_for_cluster

    - name: Run pre-test
      shell: python
      env:
        QUAY_RHACS_ENG_BEARER_TOKEN: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from pre_tests import PreSystemTests
        PreSystemTests().run()

    - name: Run sensor upgrade test
      env:
        LONGTERM_LICENSE: todo - remove me
        QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        LOAD_BALANCER: lb
      run: tests/upgrade/postgres_sensor_run.sh /tmp/postgres-sensor-upgrade-test-logs

    - name: Run post-test
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import PostClusterTest
        # The particular test removes StackRox resources, therefore not collecting their artifacts.
        PostClusterTest(collect_central_artifacts=False).run(['/tmp/postgres-sensor-upgrade-test-logs', '${{ env.ARTIFACT_DIR }}'])

    - name: Run final-post
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import FinalPost
        FinalPost(store_qa_tests_data=False).run()

    - name: Teardown cluster
      if: always()
      continue-on-error: true
      run: |
        if ! infractl delete "${CLUSTER_NAME}"; then
          echo "::warning::WARNING: Could not tear down cluster ${CLUSTER_NAME}. See Teardown step logs for details."
          exit 6
        fi

    - name: Publish test summary
      uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # ratchet:test-summary/action@v2
      if: always()
      with:
        paths: ${{ env.ARTIFACT_DIR }}/**/*.xml
        show: all

    - name: Report junit failures in jira
      if: (!cancelled())
      id: junit2jira
      uses: ./.github/actions/junit2jira
      with:
        create-jiras: ${{ github.event_name == 'push' }}
        jira-user: ${{ secrets.JIRA_USER }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
        directory: ${{ env.ARTIFACT_DIR }}
