name: e2e-nongroovy-tests-gke-konflux

on:
  workflow_call:
    inputs:
      tag:
        description: |
          Image tag to test. The caller needs to make sure that the tag carries the
          "-fast" Konflux suffix if required (e.g. for development builds).
        type: string
        required: true
      should-run:
        description: true if should really run the job. false - otherwise, i.e. the job should be skipped.
        type: boolean
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: |
          Image tag to test. You need to make sure that the tag carries the
          "-fast" Konflux suffix if required (e.g. for development builds).
        type: string
        required: true

jobs:
  run:
    uses: ./.github/workflows/e2e-nongroovy-tests.yaml
    with:
      should-run: ${{ github.event_name == 'workflow_dispatch' || inputs.should-run }}
      tag: ${{ inputs.tag }}
      ci-job-name: gke-nongroovy-e2e-tests-konflux
      extra-env-vars: |
        USE_ROXIE_DEPLOY=true
        USE_KONFLUX_IMAGES=true
    secrets: inherit
