name: e2e Sensor Upgrade Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

concurrency: upgrade-sensor-${{ github.ref }}

jobs:
  # Job 2: Run the upgrade test
  sensor-upgrade-test:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The action limits cluster name to 26 characters for maybe a valid reason.
      CLUSTER_NAME: e2e-sens-${{ github.run_id }}-${{ github.run_attempt }}
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.3
      volumes:
        - /usr:/mnt/usr
        - /opt:/mnt/opt
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/job-preamble
        with:
          gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

      - name: Docker login to Quay.io
        env:
          REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        run: |
          docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Fix path for infractl
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - uses: stackrox/actions/infra/install-infractl@v1

      - name: Create test cluster
        uses: stackrox/actions/infra/create-cluster@v1
        with:
          token: ${{ secrets.INFRA_TOKEN }}
          flavor: gke-default
          name: ${{ env.CLUSTER_NAME }}
          lifespan: 4h
          args: nodes=3,machine-type=e2-standard-8
          wait: true

      - name: Check and grab artifacts
        run: |
          STATUS="$(infractl get "${CLUSTER_NAME}" --json | jq -r .Status)"
          if [[ "$STATUS" != "READY" ]]; then
            >&2 echo "Cluster does not seem ready, status: $STATUS"
            exit 1
          fi

          infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
          echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

      - name: Verify kubectl access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Delete cluster
        if: always()
        run: |
          infractl delete "${CLUSTER_NAME}"
