name: e2e-qa-tests-gke-konflux

on:
  workflow_call:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true
      should-run:
        description: true if should really run the job. false - otherwise, i.e. the job should be skipped.
        type: boolean
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true

jobs:
  run:
    if: inputs.should-run
    uses: ./.github/workflows/e2e-qa-tests.yaml
    with:
      tag: ${{ inputs.tag }}
      ci-job-name: gke-qa-e2e-tests-konflux
      ci-job-short-name: gke-qa-e2e-konflux
      cluster-provisioning-method: direct-gke
      extra-env-vars: |
        ORCHESTRATOR_FLAVOR=k8s
        KUBERNETES_PROVIDER=gke
        SFA_AGENT=true
        USE_KONFLUX_IMAGES=true
    secrets: inherit
