name: e2e Sensor Upgrade Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

concurrency: upgrade-sensor-${{ github.ref }}

jobs:
  # Job 2: Run the upgrade test
  upgrade-test:
    name: Run Postgres Sensor Upgrade Test
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.5.3
      volumes:
        - /usr:/mnt/usr
        - /opt:/mnt/opt
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      CLUSTER_NAME: upgrade-sensor-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/job-preamble
        with:
          gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}


      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Fix path for infractl
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - uses: stackrox/actions/infra/install-infractl@v1

      - name: Create testing cluster
        run: |
          infractl create gke-default "${CLUSTER_NAME}" \
            --arg nodes=3 \
            --arg machine-type=e2-standard-8 \
            --lifespan 4h \
            --no-slack \
            --wait \
            --download-dir artifacts

          echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

        # uses: stackrox/actions/infra/create-cluster@v1
        # with:
        #   token: ${{ secrets.INFRA_TOKEN }}
        #   flavor: gke-default
        #   name: ${{ env.CLUSTER_NAME }}
        #   lifespan: '4h'
        #   args: nodes=3,machine-type=e2-standard-8
        #   wait: true

      - name: Test cluster readiness
        run: |
          STATUS=$(infractl get "${CLUSTER_NAME}" --json | jq -r .Status)
          if [ "$STATUS" != "READY" ]; then
            echo "Cluster not ready, status: $STATUS"
            exit 1
          fi

      # - name: Fetch infra artifacts
      #   run: |
      #     mkdir -p artifacts
      #     infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts
      #     echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

      - name: Verify kubectl access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Docker login to Quay.io
        env:
          REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        run: |
          docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

      - name: Delete cluster
        if: always()
        run: |
          infractl delete "${CLUSTER_NAME}"
