name: e2e-dispatch

on:
  push:
    tags:
    - '*'
    branches:
    - master
    - release-*
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - labeled

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  # Determines whether we should dispatch jobs that call real E2E workflows.
  # This allows to skip running E2E tests on draft PRs without corresponding labels or on untrusted forks.
  should-dispatch:
    needs: [ detect-changes ]
    runs-on: ubuntu-slim
    outputs:
      dispatch-any: ${{ steps.determine.outputs.dispatch-any }}
      e2e-byodb-test: ${{ steps.determine.outputs.e2e-byodb-test }}
      e2e-db-backup-restore-test: ${{ steps.determine.outputs.e2e-db-backup-restore-test }}
      e2e-gke-upgrade-tests: ${{ steps.determine.outputs.e2e-gke-upgrade-tests }}
      e2e-nongroovy-tests: ${{ steps.determine.outputs.e2e-nongroovy-tests }}
    steps:
    - name: Determine whether should dispatch workflows
      id: determine
      shell: python
      env:
        PYTHONUNBUFFERED: "1"
        event_name: ${{ github.event_name }}
        event_action: ${{ github.event.action }}
        labeled_with: ${{ github.event.label.name }}
        is_fork: ${{ github.event.pull_request.head.repo.fork }}
        is_draft: ${{ github.event.pull_request.draft }}
        all_labels: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        ui_only_change: ${{ needs.detect-changes.outputs.ui_only }}
      run: |
        import os
        from types import SimpleNamespace

        input = SimpleNamespace(
            **{var: os.environ[var] for var in (
                'event_name',
                'event_action',
                'labeled_with',
                'is_fork',
                'is_draft',
                'all_labels',
                'ui_only_change',
            )})
        for k, v in vars(input).items():
            print(f'{k} = {v}')

        def should_run(job):
            if input.is_fork == 'true':
                return False
            if input.event_action == 'labeled' and input.labeled_with != job:
                return False
            if input.event_name != 'pull_request':
                return True
            if input.ui_only_change == 'true':
                # For now, all the workflows that we dispatch should be skipped for PRs that only change UI.
                # As we add more E2E test workflows, we may want to make this more flexible.
                return False
            if input.is_draft != 'true':
                return True
            if f',{input.all_labels},'.find(f',{job},') >= 0:
                return True
            return False

        with open(os.environ['GITHUB_OUTPUT'], mode='at', encoding='utf-8') as file:
            def write(job, decision):
                line = f'{job}={str(decision).lower()}'
                print(line)
                file.write(line + '\n')

            dispatch_any = False

            for job in [
                'e2e-byodb-test',
                'e2e-db-backup-restore-test',
                'e2e-gke-upgrade-tests',
                'e2e-nongroovy-tests',
            ]:
                dispatch = should_run(job)
                dispatch_any = dispatch_any or dispatch
                write(job, dispatch)

            write('dispatch-any', dispatch_any)

  # Waits for images to be built so we don't start testing until they are available.
  wait-for-images:
    needs: [ should-dispatch ]
    if: needs.should-dispatch.outputs.dispatch-any == 'true'
    runs-on: ubuntu-slim
    outputs:
      tag: ${{ steps.build-tag.outputs.tag }}
      operator_tag: ${{ steps.build-tag.outputs.operator_tag }}
      ## MAIN_IMAGE_TAG can be used for overriding when you want to run workflows for particular images.
      # env:
      #   MAIN_IMAGE_TAG: 4.12.x-350-gc76d76b0fb
    steps:
    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        persist-credentials: false
    - uses: ./.github/actions/handle-tagged-build
    - name: Compute build tag
      id: build-tag
      run: |
        tag="${MAIN_IMAGE_TAG:-"$(make --quiet --no-print-directory tag)"}"
        echo "tag=$tag" | tee -a "$GITHUB_OUTPUT" -a "$GITHUB_ENV"
        echo "operator_tag=$(BUILD_TAG="${tag}" make -C operator --quiet --no-print-directory tag)" | tee -a "$GITHUB_OUTPUT" -a "$GITHUB_ENV"
    - name: Wait for images
      uses: stackrox/actions/release/wait-for-image@9238e423c3ae1ac4eb0f254cbb98da9daae24d86 # ratchet:stackrox/actions/release/wait-for-image@v1
      with:
        token: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
        image: |
          rhacs-eng/central-db:${{ env.tag }}
          rhacs-eng/collector:${{ env.tag }}
          rhacs-eng/fact:${{ env.tag }}
          rhacs-eng/main:${{ env.tag }}
          rhacs-eng/roxctl:${{ env.tag }}
          rhacs-eng/scanner-db-slim:${{ env.tag }}
          rhacs-eng/scanner-db:${{ env.tag }}
          rhacs-eng/scanner-slim:${{ env.tag }}
          rhacs-eng/scanner-v4-db:${{ env.tag }}
          rhacs-eng/scanner-v4:${{ env.tag }}
          rhacs-eng/scanner:${{ env.tag }}
          rhacs-eng/stackrox-operator:${{ env.operator_tag }}

  dispatch-e2e-byodb-test:
    needs: [ wait-for-images, should-dispatch ]
    uses: ./.github/workflows/e2e-byodb-test.yaml
    with:
      tag: ${{ needs.wait-for-images.outputs.tag }}
      should-run: ${{ needs.should-dispatch.outputs.e2e-byodb-test == 'true' }}
    secrets: inherit
    concurrency:
      group: e2e-byodb-test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

  dispatch-e2e-db-backup-restore-test:
    needs: [ wait-for-images, should-dispatch ]
    uses: ./.github/workflows/e2e-db-backup-restore-test.yaml
    with:
      tag: ${{ needs.wait-for-images.outputs.tag }}
      should-run: ${{ needs.should-dispatch.outputs.e2e-db-backup-restore-test == 'true' }}
    secrets: inherit
    concurrency:
      group: e2e-db-backup-restore-test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

  dispatch-e2e-gke-upgrade-tests:
    needs: [ wait-for-images, should-dispatch ]
    uses: ./.github/workflows/e2e-gke-upgrade-tests.yaml
    with:
      tag: ${{ needs.wait-for-images.outputs.tag }}
      should-run: ${{ needs.should-dispatch.outputs.e2e-gke-upgrade-tests == 'true' }}
    secrets: inherit
    concurrency:
      group: e2e-gke-upgrade-tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

  dispatch-e2e-nongroovy-tests:
    needs: [ wait-for-images, should-dispatch ]
    uses: ./.github/workflows/e2e-nongroovy-tests.yaml
    with:
      tag: ${{ needs.wait-for-images.outputs.tag }}
      should-run: ${{ needs.should-dispatch.outputs.e2e-nongroovy-tests == 'true' }}
    secrets: inherit
    concurrency:
      group: e2e-nongroovy-tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
