name: e2e-gke-upgrade-tests

on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - reopened
    - labeled
    - synchronize

concurrency: e2e-gke-upgrade-tests-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  wait-for-images:
    name: Wait for images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ main, central-db, roxctl, scanner-v4, scanner-v4-db, collector ]
    env:
      # TODO: remove the image tag override
      MAIN_IMAGE_TAG: 4.11.x-244-g092168e534
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Get PR image tag
      run: |
        echo "tag=${MAIN_IMAGE_TAG:-$(make tag)}" | tee -a "$GITHUB_ENV"
    - name: Wait for the ${{ matrix.image }}
      uses: stackrox/actions/release/wait-for-image@v1
      with:
        token: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
        image: rhacs-eng/${{ matrix.image }}:${{ env.tag }}

  sensor-gke-upgrade-tests:
    needs: [ wait-for-images ]
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
      # The cluster name must be no longer than 26 characters.
      CLUSTER_NAME: e2e-sens-${{ github.run_id }}-${{ github.run_attempt }}
      CI_JOB_NAME: sensor-gke-upgrade-tests
      ARTIFACT_DIR: ${{ github.workspace }}/logs/artifacts
      # TODO: remove the image tag override
      MAIN_IMAGE_TAG: 4.11.x-244-g092168e534
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-ui-test-0.5.3
      volumes:
      - /usr:/mnt/usr
      - /opt:/mnt/opt
    timeout-minutes: 180 # Keep in sync with cluster's lifespan
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Fix $PATH for infractl
      run: echo "$HOME/.local/bin" | tee -a "$GITHUB_PATH"

    - name: Trigger test cluster creation
      uses: stackrox/actions/infra/create-cluster@v1
      with:
        token: ${{ secrets.INFRA_TOKEN }}
        flavor: gke-default
        name: ${{ env.CLUSTER_NAME }}
        lifespan: 3h # Keep in sync with job's timeout-minutes
        args: nodes=3,machine-type=e2-standard-8
        wait: false

    - name: Docker login to Quay.io
      env:
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      run: |
        docker login -u "${REGISTRY_USERNAME}" --password-stdin quay.io <<<"${REGISTRY_PASSWORD}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Build roxctl and upgrader
      run: |
        make roxctl_linux-amd64 upgrader

    - name: Wait for the cluster and grab artifacts
      timeout-minutes: 25
      run: |
        infractl wait "${CLUSTER_NAME}"
        infractl artifacts "${CLUSTER_NAME}" --download-dir artifacts > /dev/null
        echo "KUBECONFIG=$(pwd)/artifacts/kubeconfig" >> "$GITHUB_ENV"

    - name: Verify kubectl access
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Run pre-test
      env:
        QUAY_RHACS_ENG_BEARER_TOKEN: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from pre_tests import PreSystemTests
        PreSystemTests().run()

    - name: Run postgres sensor upgrade test
      env:
        LONGTERM_LICENSE: todo - remove me
        QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
        LOAD_BALANCER: lb
        CI_JOB_NAME: gha-upgrade-postgres-sensor-test
      run: |
        tests/upgrade/postgres_sensor_run.sh /tmp/postgres-sensor-upgrade-test-logs

    - name: Run post-test
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import PostClusterTest
        # The particular test removes StackRox resources, therefore not collecting their artifacts.
        PostClusterTest(collect_central_artifacts=False).run()

    - name: Run final-post
      if: always()
      shell: python
      run: |
        import sys
        sys.path.append('.openshift-ci')
        from post_tests import FinalPost
        FinalPost(store_qa_tests_data=True).run()

    - name: Delete cluster
      if: always()
      run: |
        infractl delete "${CLUSTER_NAME}"
