name: Periodic Retest Failed Konflux Builds

on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'
  workflow_dispatch:

jobs:
  retest:
    uses: stackrox/actions/.github/workflows/periodic-retest-konflux-builds.yml@f4660e8 # ratchet:stackrox/actions/.github/workflows/periodic-retest-konflux-builds.yml@v1
    permissions:
      pull-requests: write
      issues: write
      checks: read
      contents: read
    with:
      max_retries: 3
      retest_command: '/konflux-retest'
