name: qa-e2e-tests-gke

on:
  workflow_call:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true
      should-run:
        description: true if should really run the job. false - otherwise, i.e. the job should be skipped.
        type: boolean
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true

jobs:
  run:
    if: inputs.should-run
    uses: ./.github/workflows/_qa-e2e-tests.yaml
    with:
      tag: ${{ inputs.tag }}
      ci-job-name: gke-qa-e2e-tests
      ci-job-short-name: qa-e2e-gke
      infra-flavor: gke-default
      infra-args: |
        nodes=3
        machine-type=e2-standard-8
      infra-lifespan: 5h
      extra-env-vars: |
        ORCHESTRATOR_FLAVOR=k8s
        KUBERNETES_PROVIDER=gke
    secrets: inherit
