name: qa-e2e-tests-ocp-4-22-konflux

on:
  workflow_call:
    inputs:
      tag:
        description: Image tag to test.
        type: string
        required: true
      should-run:
        description: true if should really run the job. false - otherwise, i.e. the job should be skipped.
        type: boolean
        required: true

jobs:
  run:
    if: >-
      inputs.should-run && (
        github.event_name != 'pull_request' ||
        contains(github.event.pull_request.labels.*.name, 'konflux-build')
      )
    uses: ./.github/workflows/_qa-e2e-tests.yaml
    with:
      tag: ${{ inputs.tag }}
      ci-job-name: qa-e2e-tests-ocp-4-22-konflux
      cluster-wait-timeout-minutes: 50
      infra-flavor: openshift-4
      infra-args: |
        openshift-version=ocp/stable-4.22
        master-node-type=e2-standard-4
        master-node-count=3
        worker-node-type=e2-standard-8
        worker-node-count=3
        ssd-storage-class=true
      infra-lifespan: 5h
      # To address later:
      #   SETUP_WORKLOAD_IDENTITIES=true
      extra-env-vars: |
        ORCHESTRATOR_FLAVOR=openshift
        KUBERNETES_PROVIDER=ocp
        SFA_AGENT=true
        USE_KONFLUX_IMAGES=true
    secrets: inherit
