name: Scanner E2E tests

on:
  workflow_run:
    workflows: ["Scanner build and push images"]
    types:
      - completed

  push:
    branches:
    - jvdm/*
  
jobs:
  e2e-run:
    runs-on: ubuntu-latest
    env:
      # 4.3.x-1163-g61a55af9c8
      SCANNER_E2E_IMAGE_TAG: 4.3.x-1165-g862a40727a
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/job-preamble

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: none # baremetal
          cache: false
          cpus: max
          memory: max
          
      - name: Deploy chart
        run: |
          v="${{ runner.temp }}"/pgdata
          mkdir -m 777 -p "$v"

          wait_deployment() {
              local name
              name="${1:?missing require argument 'name'}"
              while ! kubectl wait -n stackrox --for=condition=available --timeout=5s deployment/"$name"; do
                  echo "Deployment $name is not ready. Checking status..."
                  kubectl describe deployment "$name" -n stackrox
                  kubectl get pods -n stackrox -l app="$name" -o jsonpath="{.items[*].metadata.name}" \
                      | xargs -I {} kubectl logs {} -n stackrox --tail=10
              done
              echo "Deployment $name is ready" 
          }

          wait_deployment scanner-v4 &
          wait_deployment scanner-v4-db &
          make -C scanner e2e-deploy db-host-path="$v"
          wait
      - name: Services
        run: |
          minikube service list
          minikube -n stackrox service discover --url

      - name: Run tests
        run: |
          make -C scanner e2e-run
