name: Scanner E2E tests

on:
  workflow_run:
    workflows: ["Scanner build and push images"]
    types:
      - completed

  push:
    branches:
    - jvdm/*
  
jobs:
  e2e-run:
    runs-on: ubuntu-latest
    env:
      SCANNER_E2E_IMAGE_TAG: 4.3.x-1165-g862a40727a
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/job-preamble

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: none # baremetal
          cache: false
          
      - name: Deploy E2E
        run: |
          make tag
          make -C scanner e2e db-host-path=/data/scanner-v4-db
