FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm:0.7.9

RUN apt-get -y update \
 && apt-get install -y --no-install-recommends curl=7.52.1-5+deb9u9 unzip=6.0-21+deb9u1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY ./bin/roxctl-linux /usr/bin/roxctl
COPY gcp/application.yaml.tpl /data/application.yaml.tpl
COPY gcp/application-success.yaml.tpl /data/application-success.yaml.tpl
COPY gcp/create_manifests.sh /bin/create_manifests.sh
COPY gcp/deploy.sh /bin/deploy.sh
COPY gcp/kubectl /usr/local/bin/kubectl
COPY gcp/schema.yaml.tpl /data/schema.yaml.tpl

ARG MAIN_IMAGE_TAG
ARG SCANNER_IMAGE_TAG

RUN MAIN_IMAGE_TAG=$MAIN_IMAGE_TAG SCANNER_IMAGE_TAG=$SCANNER_IMAGE_TAG envsubst < /data/schema.yaml.tpl > /data/schema.yaml \
 && rm /data/schema.yaml.tpl
