FROM registry.redhat.io/rhel7:7.6-151.1550575774

LABEL name="stackrox.io/main"
LABEL vendor="StackRox (support@stackrox.com)"
LABEL summary="The StackRox Kubernetes platform"
LABEL description="This image contains everything required to operate the StackRox Kubernetes platform."

# Telegraf (for monitoring)
RUN curl -L https://github.com/connorgorman/telegraf/releases/download/1.8.0%2B49-slim/telegraf -o /telegraf && chmod +x /telegraf

# If you change this URL you must also change it in image/Dockerfile
RUN curl -o product-docs.tgz -L https://storage.googleapis.com/doc-bundles/03c318a8759d13e8ed7611bccd6618dde60d768a345ff3c0a870e60c53bcfbe9/0.0.0-82-gc16cd000.tgz && \
    tar xzf product-docs.tgz && \
    mv public /product-docs && \
    ls /product-docs/index.html && \
    rm product-docs.tgz

ENV PATH="/stackrox:$PATH"

COPY ./policies/ /data/policies
COPY ./templates/ /data/templates
COPY ./central-entrypoint.sh /stackrox/
COPY ./bin/migrator /stackrox/
COPY ./bin/central /stackrox/
COPY ./bin/compliance /stackrox/compliance
COPY ./bin/roxctl* /assets/downloads/cli/
COPY ./bin/kubernetes-sensor /stackrox/
COPY ./static-bin/* /stackrox/
COPY ./ui/build  /ui/
COPY ./docs/api/v1/swagger.json /docs/api/v1/swagger.json

COPY ./NOTICE.txt /licenses/

COPY ./assets /data/assets

EXPOSE 8443


ENTRYPOINT ["/assets/downloads/cli/roxctl-linux"]

# The following paths are written to in Central.
# Including these VOLUME instructions means that we can enable a
# read-only root file system without preventing writes to these paths.
# Trusted CA certificates are written to this path by `update-ca-trust`.
RUN chown -R 4000 /etc/pki
VOLUME /etc/pki/ca-trust
# Search indices are generated upon startup and updated thereafter.
RUN mkdir -p /tmp/search && chown -R 4000 /tmp/search
VOLUME /tmp/search
# The BoltDB is stored at this path.
RUN mkdir -p /var/lib/stackrox && chown -R 4000 /var/lib/stackrox
VOLUME /var/lib/stackrox
# The log file is stored at this path
RUN mkdir -p /var/log/stackrox && chown -R 4000 /var/log/stackrox
VOLUME /var/log/stackrox

# /tmp needs to be a read-write filesystem.
RUN chown -R 4000 /tmp
VOLUME /tmp

USER 4000
