FROM stackrox-data:latest AS data

FROM registry.redhat.io/rhel7:7.6-151.1550575774

LABEL name="stackrox.io/main"
LABEL vendor="StackRox (support@stackrox.com)"
LABEL summary="The StackRox Kubernetes platform"
LABEL description="This image contains everything required to operate the StackRox Kubernetes platform."

# Telegraf (for monitoring)
RUN curl -L https://github.com/connorgorman/telegraf/releases/download/1.8.0%2B49-slim/telegraf -o /telegraf && chmod +x /telegraf

ENV PATH="/stackrox:$PATH"

COPY ./central-entrypoint.sh /stackrox/
COPY ./bin/migrator /stackrox/
COPY ./bin/central /stackrox/
COPY ./bin/compliance /stackrox/
COPY ./bin/roxctl* /assets/downloads/cli/
COPY ./bin/kubernetes-sensor /stackrox/
COPY ./static-bin/* /stackrox/
COPY ./restricted-ui /stackrox/ui
COPY --from=data /stackrox-data.tgze /stackrox/

COPY ./NOTICE.txt /licenses/

EXPOSE 8443


ENTRYPOINT ["/assets/downloads/cli/roxctl-linux"]

# The following paths are written to in Central.
# Including these VOLUME instructions means that we can enable a
# read-only root file system without preventing writes to these paths.
# Trusted CA certificates are written to this path by `update-ca-trust`.
RUN chown -R 4000 /etc/pki
VOLUME /etc/pki/ca-trust
# Search indices are generated upon startup and updated thereafter.
RUN mkdir -p /tmp/search && chown -R 4000 /tmp/search
VOLUME /tmp/search
# The BoltDB is stored at this path.
RUN mkdir -p /var/lib/stackrox && chown -R 4000 /var/lib/stackrox
VOLUME /var/lib/stackrox
# The log file is stored at this path
RUN mkdir -p /var/log/stackrox && chown -R 4000 /var/log/stackrox
VOLUME /var/log/stackrox

# /tmp needs to be a read-write filesystem.
RUN chown -R 4000 /tmp
VOLUME /tmp

RUN mkdir -p /stackrox/data && chown -R 4000 /stackrox/data
VOLUME /stackrox/data

USER 4000
